/* Taller 05 · Due Diligence Legal y Técnica · Banco v1 */
window.TALLER_CONFIG = {
  slug: 'due-diligence-legal',
  moduleNames: {
    1:'ROL SII y contribuciones',2:'CBR · Conservador de Bienes Raíces',3:'Estudio de títulos 10 años',
    4:'DOM y certificados municipales',5:'Tasación técnica CMF',6:'Vicios redhibitorios y Ley 19.472',
    7:'Copropiedad · Ley 21.442',
  },
  certTitle:'Due Diligence Legal y Técnica', certSubtitle:'Taller Avanzado 05 · Academia TuMatch',
  quizBank:{
    1:[
      {q:"El ROL SII identifica:",opts:["Al dueño","La propiedad fiscalmente (avalúo, destino, superficie)","El banco","El corredor"],correct:1,whyCorrect:"Es la identificación tributaria de cada propiedad.",whyWrong:["El CBR lo hace.","","No aplica.","No aplica."]},
      {q:"El avalúo fiscal se consulta en:",opts:["Notaría","sii.cl","CBR","MINVU"],correct:1,whyCorrect:"SII mantiene el registro de avalúos.",whyWrong:["No emite.","","CBR es dominio.","MINVU política."]},
      {q:"Las contribuciones impagas al momento de compra:",opts:["Las paga el banco","Pueden generar corresponsabilidad del comprador del año en curso","Nadie paga","SII perdona"],correct:1,whyCorrect:"Responsabilidad solidaria parcial.",whyWrong:["No.","","Alguien paga.","No perdona."]},
      {q:"La exención contribuciones primera vivienda aplica:",opts:["Siempre","Si el avalúo es menor al tope exención (varía anualmente por DFL 1 / ley)","Nunca","Solo nueva"],correct:1,whyCorrect:"Política de apoyo al primera vivienda.",whyWrong:["Hay tope.","","Aplica.","Ambas pueden."]},
      {q:"Tesorería General de la República cobra:",opts:["IVA","Contribuciones impositivas territoriales (impuesto territorial)","Corretaje","Nada"],correct:1,whyCorrect:"Administra impuestos al bien raíz.",whyWrong:["SII.","","Privado.","Cobra."]},
      {q:"Un certificado de avalúo fiscal se usa para:",opts:["Nada","Respaldar transferencias, sucesiones y validaciones tributarias","Decorar","Comprar auto"],correct:1,whyCorrect:"Documento oficial SII.",whyWrong:["Funcional.","","No decorativo.","Irrelevante."]},
      {q:"Si una propiedad tiene uso mixto (habitacional + comercial):",opts:["No cambia nada","Puede tener avalúo diferenciado y contribuciones más altas","Gratis","Nada"],correct:1,whyCorrect:"Destino influye en el avalúo y en las exenciones.",whyWrong:["Influye.","","No.","Relevante."]},
      {q:"Antes de firmar promesa, el corredor verifica contribuciones en:",opts:["Notaría","sii.cl + tesoreria.cl","Registro Civil","SERNAC"],correct:1,whyCorrect:"Plataformas oficiales.",whyWrong:["No emite esto.","","No.","No."]},
      {q:"La superficie del inmueble según SII puede diferir de la del DOM por:",opts:["Nunca","Diferencia entre superficie construida declarada y superficie regularizada · ampliaciones sin permiso",
        "Sólo en regiones","Imposible"],correct:1,whyCorrect:"Situación frecuente en vivienda usada.",whyWrong:["Sí difiere.","","No zonal.","Frecuente."]},
      {q:"El destino inscrito en SII (habitacional, comercial, mixto) importa porque:",opts:["No importa","Afecta contribuciones, permisos municipales y seguros","Solo estético","Nunca"],correct:1,whyCorrect:"Condiciona el régimen tributario y urbanístico.",whyWrong:["Importa.","","Fondo.","Sí importa."]},
      {q:"Si se detecta deuda en contribuciones:",opts:["Se ignora","Se descuenta del precio o se regulariza antes de la firma","Se factura","Nada"],correct:1,whyCorrect:"Protege al comprador.",whyWrong:["Genera problema.","","No es factura.","Se resuelve."]},
      {q:"El ROL es esencial para:",opts:["Nada","Identificar fiscalmente la propiedad en cualquier trámite","Decorar","Marketing"],correct:1,whyCorrect:"ID oficial.",whyWrong:["Crítico.","","No decorativo.","Trámites."]},
      {q:"El impuesto territorial se paga:",opts:["Al contado único","En cuatro cuotas trimestrales (abril, junio, septiembre, noviembre)",
        "Al comprar","Mensual"],correct:1,whyCorrect:"Calendario Tesorería.",whyWrong:["Fraccionado.","","No solo al comprar.","Trimestral."]},
      {q:"SII puede retasar el avalúo fiscal cada:",opts:["Semana","4 años aproximadamente en retasación masiva","Siempre","Nunca"],correct:1,whyCorrect:"Proceso periódico reglado.",whyWrong:["Fuera.","","Hay retasación.","Hay retasación."]},
      {q:"Un cliente que compra propiedad con mora contribuciones no debe:",opts:["Pagar","Firmar sin regularización o retención del saldo para cubrir deuda","Abandonar","Demandar"],correct:1,whyCorrect:"Protección del comprador.",whyWrong:["Se debe resolver.","","Innecesario.","Primero negociar."]},
      {q:"El rol del corredor en contribuciones es:",opts:["Ninguno","Verificar estado y asegurar regularización previa o retención",
        "Pagar","Demandar"],correct:1,whyCorrect:"Parte del servicio profesional.",whyWrong:["Hay rol.","","No es responsable.","No."]},
      {q:"El certificado de avalúo fiscal se solicita en:",opts:["Banco","sii.cl online con ClaveTributaria o CI","Registro Civil","SERVIU"],correct:1,whyCorrect:"Portal SII.",whyWrong:["No emite.","","No.","No."]},
      {q:"El avalúo fiscal vs el valor comercial:",opts:["Iguales","Avalúo es para tributación · comercial refleja mercado · habitualmente comercial > fiscal",
        "Fiscal mayor","Sin relación"],correct:1,whyCorrect:"Son conceptos distintos.",whyWrong:["Son distintos.","","Al revés.","Hay relación."]},
      {q:"Las contribuciones las paga quien:",opts:["El que vive","Es propietario al 1 de enero de cada año cuotas 1 a 4 · si se transfiere, nuevo dueño paga desde su periodo",
        "El arrendatario","Nadie"],correct:1,whyCorrect:"Regla de proporcionalidad en transferencias.",whyWrong:["Propietario.","","No arriendo.","Alguien."]},
      {q:"Si propiedad tiene avalúo menor a tope exención:",opts:["Paga igual","Exención total o parcial según régimen vigente","Sin impuesto nunca","Imposible"],correct:1,whyCorrect:"Beneficio tributario.",whyWrong:["Hay exención.","","Hay casos.","Común."]},
    ],
    2:[
      {q:"El CBR es:",opts:["Banco","Registro público de la propiedad inmueble (uno por jurisdicción)","Notaría","SII"],correct:1,whyCorrect:"Art. 695 CC y Reglamento del Conservador.",whyWrong:["No.","","Distintas funciones.","Tributo."]},
      {q:"Sin inscripción en CBR, la hipoteca:",opts:["Es válida plena","No produce efectos frente a terceros (Art. 2.410 CC)","Depende notario","Ilegal"],correct:1,whyCorrect:"Principio de publicidad registral.",whyWrong:["Insuficiente.","","No depende.","No ilegal, solo ineficaz a terceros."]},
      {q:"El certificado de dominio vigente muestra:",opts:["Avalúo","Quién es el actual dueño inscrito","IVA","Arriendo"],correct:1,whyCorrect:"Certificación registral.",whyWrong:["SII.","","No.","No."]},
      {q:"El certificado de hipotecas y gravámenes lista:",opts:["Vecinos","Deudas garantizadas con la propiedad + restricciones","Precios","Nada"],correct:1,whyCorrect:"Cargas registradas sobre el inmueble.",whyWrong:["Irrelevante.","","No.","Crítico."]},
      {q:"Las prohibiciones que aparecen en CBR incluyen:",opts:["Nada","Subsidio DS1 (5 años), embargos, medidas precautorias, servidumbres gravosas",
        "Solo impuestos","Solo Airbnb"],correct:1,whyCorrect:"Todo acto que limita la disposición.",whyWrong:["Hay.","","Más amplio.","No específico."]},
      {q:"La copia de inscripción con notas marginales muestra:",opts:["Colores","Historia reciente de la propiedad (anotaciones y actos)","Contribuciones","Arriendo"],correct:1,whyCorrect:"Histórico registral.",whyWrong:["No.","","Fiscal.","Otro."]},
      {q:"El CBR competente es:",opts:["Cualquiera","El de la jurisdicción donde está ubicada la propiedad","SII","Registro Civil"],correct:1,whyCorrect:"Territorialidad.",whyWrong:["No cualquiera.","","No.","No."]},
      {q:"Certificados CBR deben tener fecha:",opts:["Antigua","Cercana a la firma (habitualmente < 30 días)","10 años","Sin fecha"],correct:1,whyCorrect:"Evita cambios posteriores no reflejados.",whyWrong:["Obsoleto.","","Imposible.","Requerida."]},
      {q:"El plazo típico de emisión de certificado CBR es:",opts:["Horas","1 a 3 días hábiles","6 meses","Años"],correct:1,whyCorrect:"Tiempo operativo.",whyWrong:["Varía por comuna.","","Fuera.","Absurdo."]},
      {q:"Si aparece prohibición 'subsidio DS1 5 años vigente':",opts:["Ignorar","La propiedad no puede transferirse sin autorización SERVIU y devolución subsidio",
        "Se salta","Irrelevante"],correct:1,whyCorrect:"Cláusula legal de subsidio.",whyWrong:["Problema serio.","","No.","Relevante."]},
      {q:"Una hipoteca previa vigente al momento de comprar:",opts:["Imposibilita","Se alza simultáneamente con la nueva hipoteca en notaría (tracto sucesivo)",
        "Nada","Se asume"],correct:1,whyCorrect:"Operación estándar.",whyWrong:["No imposibilita.","","Hay procedimiento.","No automáticamente."]},
      {q:"Los litigios que afectan la propiedad se ven en:",opts:["SII","Certificado de litigios CBR + causas en el Poder Judicial",
        "Redes","Ninguno"],correct:1,whyCorrect:"Registro específico.",whyWrong:["No.","","No.","Existen canales."]},
      {q:"El costo aproximado por certificado CBR (2026) ronda:",opts:["$100","$3.000 a $6.000 por certificado","$50.000","Gratis"],correct:1,whyCorrect:"Arancel estándar.",whyWrong:["Subestima.","","Excesivo.","No gratis."]},
      {q:"Los certificados online del CBR Santiago se obtienen en:",opts:["cbrs.cl (Conservador Bienes Raíces Santiago)","Sí, plataforma digital con ClaveÚnica o por portal",
        "Solo papel","Wikipedia"],correct:1,whyCorrect:"Modernización registral.",whyWrong:["","","Hay digital.","No oficial."]},
      {q:"Una medida precautoria inscrita en CBR:",opts:["Ignorar","Bloquea disposición hasta resolución judicial","Sin efecto","Automática"],correct:1,whyCorrect:"Bloquea transferencia.",whyWrong:["No.","","Tiene efecto.","Requiere orden."]},
      {q:"Para un cliente comprador, los certificados mínimos a revisar son:",opts:["Ninguno","Dominio vigente + hipotecas/gravámenes + prohibiciones e interdicciones",
        "Solo precio","Sólo avalúo"],correct:1,whyCorrect:"Núcleo mínimo.",whyWrong:["Incompleto.","","Insuficiente.","Insuficiente."]},
      {q:"La inscripción de compraventa en CBR tras escritura demora:",opts:["1 hora","10 a 45 días hábiles según comuna","1 año","Años"],correct:1,whyCorrect:"Procesamiento administrativo.",whyWrong:["Imposible.","","Fuera.","Excesivo."]},
      {q:"La inscripción simultánea de alzamiento + nueva hipoteca requiere:",opts:["Nada","Coordinación notaría + banco anterior + banco nuevo + CBR",
        "Solo vendedor","Solo banco nuevo"],correct:1,whyCorrect:"Operación con múltiples partes.",whyWrong:["Coordinación.","","Más partes.","Más partes."]},
      {q:"Si el CBR rechaza la inscripción por observación:",opts:["Nada","Se subsana y reingresa · el plazo corre desde reingreso",
        "Fin de operación","Automático"],correct:1,whyCorrect:"Mecanismo estándar.",whyWrong:["Subsanable.","","Hay ruta.","No automático."]},
      {q:"La servidumbre (derecho real) también se inscribe en CBR:",opts:["No","Sí, junto con otros gravámenes y derechos","A veces","Nunca"],correct:1,whyCorrect:"Publicidad registral.",whyWrong:["Se inscribe.","","Se inscribe.","Se inscribe."]},
    ],
    3:[
      {q:"El estudio de títulos revisa típicamente:",opts:["1 año","10 años (prescripción adquisitiva extraordinaria Art. 2.511 CC)","100 años","1 día"],correct:1,whyCorrect:"Plazo ley.",whyWrong:["Insuficiente.","","Excesivo.","Imposible."]},
      {q:"El tracto sucesivo se refiere a:",opts:["Colectivo","Continuidad de transferencias sin saltos ni quiebres","Pasado remoto","Futuro"],correct:1,whyCorrect:"Continuidad registral.",whyWrong:["No.","","No.","No."]},
      {q:"Una escritura con vicio de forma puede generar:",opts:["Nada","Nulidad absoluta oponible a terceros (Art. 1.682 CC)",
        "Comisión","Exención"],correct:1,whyCorrect:"Nulidad por vicio formal.",whyWrong:["Riesgo grave.","","Irrelevante.","No."]},
      {q:"Una sucesión por causa de muerte sin posesión efectiva inscrita:",opts:["Válida","Bloquea la enajenación de la propiedad hasta inscribir la posesión efectiva",
        "Sin efecto","Indiferente"],correct:1,whyCorrect:"Requisito previo a cualquier disposición hereditaria inmueble.",whyWrong:["Bloquea.","","Bloquea.","Es crítica."]},
      {q:"Si un heredero queda omitido en la sucesión, puede:",opts:["Nada","Reclamar su cuota posteriormente; riesgo para compradores",
        "Ir preso","Automático"],correct:1,whyCorrect:"Acción de petición de herencia.",whyWrong:["Hay acción.","","No.","No automático."]},
      {q:"Las hipotecas no alzadas en la cadena histórica son:",opts:["Sin efecto","Riesgo: pueden re-ejecutarse si el banco lo hace valer",
        "Pagadas","Ignoradas"],correct:1,whyCorrect:"Todo gravamen no alzado subsiste.",whyWrong:["Tienen efecto.","","No necesariamente.","No se ignoran."]},
      {q:"El estudio de títulos lo realiza:",opts:["Corredor","Abogado especialista","Notario","Cliente"],correct:1,whyCorrect:"Dictamen jurídico profesional.",whyWrong:["No es suficiente.","","No es su rol.","No evalúa solo."]},
      {q:"Una observación 'menor' en títulos se resuelve:",opts:["Se ignora","Subsanación previa a la firma (pueden ser correcciones, ratificaciones)","Juicio siempre","Imposible"],correct:1,whyCorrect:"Subsanación administrativa/notarial.",whyWrong:["No.","","Raro requerir juicio.","Es posible."]},
      {q:"Si aparece observación 'reivindicatoria potencial':",opts:["Ignorar","Detener operación y evaluar con abogado; puede ser prohibitiva",
        "Pagar más","Inventar"],correct:1,whyCorrect:"Vicio grave.",whyWrong:["Grave.","","No resuelve.","Fraude."]},
      {q:"El costo estándar de un estudio de títulos es:",opts:["Gratis","$150.000 a $400.000 según abogado y complejidad","$5 millones","$0"],correct:1,whyCorrect:"Rango profesional.",whyWrong:["No.","","Excesivo.","Hay costo."]},
      {q:"La prescripción adquisitiva ordinaria corre en:",opts:["1 año","5 años con buena fe y justo título (Art. 2.508 CC)","50 años","Nunca"],correct:1,whyCorrect:"Bienes raíces.",whyWrong:["Muy corto.","","Fuera.","Existe."]},
      {q:"La prescripción adquisitiva extraordinaria (sin título justo) es:",opts:["Inmediata","10 años (Art. 2.511 CC)","100 años","Nunca"],correct:1,whyCorrect:"Para los casos sin justo título.",whyWrong:["No.","","Fuera.","Hay plazo."]},
      {q:"Una adjudicación notarial por división:",opts:["No se inscribe","Se inscribe en CBR como adquisición del adjudicatario","Nula","Automática"],correct:1,whyCorrect:"Modo de adquirir.",whyWrong:["Se inscribe.","","Es válida.","Requiere inscripción."]},
      {q:"La fusión de lotes (incorporación predial) en el CBR:",opts:["Imposible","Se realiza con autorización DOM y nueva inscripción",
        "Libre","Nunca"],correct:1,whyCorrect:"Operación regulada.",whyWrong:["Es posible.","","Requiere trámite.","Se puede."]},
      {q:"Una escritura con firma falsa en cadena:",opts:["Ok","Genera nulidad absoluta de todos los actos posteriores sobre la propiedad",
        "Sin efecto","Sin impacto"],correct:1,whyCorrect:"Vicio grave.",whyWrong:["Nula.","","Tiene efecto.","Grave."]},
      {q:"Un abogado que aprueba título con observación 'no grave' típicamente:",opts:["Nunca","Emite informe con observación subsanable y recomendaciones",
        "Rechaza todo","Ignora"],correct:1,whyCorrect:"Práctica profesional.",whyWrong:["Lo hace.","","No siempre.","No ignora."]},
      {q:"Una propiedad con título 'limpio 10 años':",opts:["No existe","Indica que el abogado no encontró observaciones en la cadena decenal",
        "Garantiza 100%","Imposible"],correct:1,whyCorrect:"Resultado profesional.",whyWrong:["Existe.","","Reduce riesgo.","Es común."]},
      {q:"El riesgo reivindicatorio post-compra es:",opts:["Nunca","Posible si hubo vicio en la cadena; por eso el estudio es imprescindible",
        "Automático","Irrelevante"],correct:1,whyCorrect:"Riesgo real.",whyWrong:["Existe.","","No automático.","Muy relevante."]},
      {q:"Si el cliente quiere saltarse el estudio de títulos:",opts:["Se acepta","El corredor profesional lo explica: riesgo económico mucho mayor al costo del estudio",
        "Se le cobra más","No importa"],correct:1,whyCorrect:"Asesoría profesional.",whyWrong:["Mala práctica.","","No es el punto.","Importa."]},
      {q:"Una donación inscrita en la cadena:",opts:["Ignorar","Válida pero con regla de inoficiosidad si afecta legítima de herederos",
        "Nula","Ilegal"],correct:1,whyCorrect:"Hay condiciones.",whyWrong:["Tiene reglas.","","Es válida.","No ilegal."]},
    ],
    4:[
      {q:"DOM significa:",opts:["Nada","Dirección de Obras Municipales","Registro Civil","SII"],correct:1,whyCorrect:"Oficina municipal que regula edificación.",whyWrong:["Específico.","","Otra.","Otra."]},
      {q:"La Recepción Final Municipal certifica:",opts:["Venta","Obra terminada y conforme a la normativa urbanística","Precio","Avalúo"],correct:1,whyCorrect:"Validación técnica.",whyWrong:["No.","","Fiscal.","Tributo."]},
      {q:"Sin Recepción Final:",opts:["Sin problema","Problemas para tasar, inscribir y calificar bancariamente","Menor precio","Imposible"],correct:1,whyCorrect:"Puede obstaculizar el crédito.",whyWrong:["Hay problema.","","Hay problema.","Con trámite se arregla."]},
      {q:"El CIP (Certificado de Informaciones Previas) muestra:",opts:["Precio","Normas urbanísticas del predio (usos, alturas, frentes)",
        "Dueño","Avalúo"],correct:1,whyCorrect:"Define qué se puede construir.",whyWrong:["No.","","Otro certificado.","Otro."]},
      {q:"El Número Municipal es:",opts:["Precio","Dirección oficial del inmueble asignada por la municipalidad",
        "Teléfono","Clave"],correct:1,whyCorrect:"Identificación territorial.",whyWrong:["No.","","No.","No."]},
      {q:"Una ampliación sin permiso es:",opts:["Legal","Irregular; debe regularizarse en DOM (Ley 20.898 facilita el proceso)",
        "Automática","Nula"],correct:1,whyCorrect:"Regularización posible.",whyWrong:["No.","","Hay procedimiento.","No nula."]},
      {q:"La Ley 20.898 (2016) facilita:",opts:["Nada","Regularización de construcciones menores sin permiso (micro-radicación)",
        "Solo DS1","Impuestos"],correct:1,whyCorrect:"Normativa específica.",whyWrong:["Facilita.","","No.","No."]},
      {q:"Antes de firmar con propiedad ampliada sin permiso:",opts:["Ignorar","Negociar que el vendedor regularice o descuente del precio y el comprador asuma regularización",
        "Pagar más","Denunciar"],correct:1,whyCorrect:"Negociación comercial.",whyWrong:["No ignorar.","","No es el punto.","Primero negociar."]},
      {q:"El certificado de no expropiación verifica:",opts:["Uso","Que el predio no está en plan de expropiación municipal",
        "Precio","Dueño"],correct:1,whyCorrect:"Protección al comprador.",whyWrong:["No.","","No.","Otro."]},
      {q:"La línea oficial (deslinde) se obtiene en:",opts:["Banco","DOM de la municipalidad","CBR","SII"],correct:1,whyCorrect:"Deslinde legal.",whyWrong:["No.","","Registro.","Fiscal."]},
      {q:"Deuda aseo y ornato:",opts:["El banco paga","Se paga al municipio · puede ser responsabilidad compartida si no regularizada","Irrelevante","Automática"],correct:1,whyCorrect:"Responsabilidad municipal.",whyWrong:["Municipio.","","Relevante.","No."]},
      {q:"La patente comercial pendiente en el domicilio:",opts:["No afecta","Puede afectar si la propiedad fue usada como negocio · verificar al comprar",
        "Siempre afecta","Ilegal"],correct:1,whyCorrect:"Depende del caso.",whyWrong:["Puede afectar.","","No siempre.","No ilegal."]},
      {q:"Deudas de servicios (luz, agua, gas):",opts:["Sin efecto","Se regularizan al momento de la entrega o se retienen del precio",
        "Automáticas","Ilegales"],correct:1,whyCorrect:"Protección al comprador.",whyWrong:["Hay efecto.","","No automáticas.","No ilegales."]},
      {q:"Si la DOM no tiene Recepción Final de una ampliación, la tasación bancaria:",opts:["Ignora","Solo considera la superficie regularizada, no la ampliación · banco financia sobre eso",
        "Considera todo","No existe"],correct:1,whyCorrect:"Metodología estándar.",whyWrong:["No ignora.","","No toda.","Existe."]},
      {q:"Un departamento en edificio con subsidios DS1 reservados requiere además:",opts:["Nada","Calificación MINVU del comprador si reserva uno DS1; regulación DS19",
        "Solo dinero","Nada"],correct:1,whyCorrect:"Proyecto mixto.",whyWrong:["Hay trámites.","","Hay calificación.","Hay trámite."]},
      {q:"El Número Municipal se consulta en:",opts:["Registro Civil","Municipalidad (DOM) · también en mapa oficial de la comuna",
        "Notaría","CBR"],correct:1,whyCorrect:"Canal municipal.",whyWrong:["No.","","No.","Otro registro."]},
      {q:"Antes de firmar, revisar plan regulador comunal por:",opts:["Nunca","Cambios de uso o alturas que puedan afectar el valor futuro",
        "Solo curiosidad","Nada"],correct:1,whyCorrect:"Diligencia profesional.",whyWrong:["Relevante.","","Crítico.","Importante."]},
      {q:"El plan regulador comunal lo define:",opts:["Estado","Municipio con aprobación del plan por autoridad competente",
        "Dueño","SII"],correct:1,whyCorrect:"Instrumento local.",whyWrong:["No.","","No.","No."]},
      {q:"Una propiedad en zona de conservación histórica:",opts:["Normal","Tiene restricciones adicionales para remodelación y demolición","Más barata","Sin restricción"],correct:1,whyCorrect:"Ley 17.288 Monumentos.",whyWrong:["Tiene restricciones.","","No necesariamente.","Tiene."]},
      {q:"El corredor debe avisar al cliente sobre restricciones urbanísticas porque:",opts:["Marketing","Afectan el uso, remodelación y valor futuro de la propiedad",
        "Nada","Aburrido"],correct:1,whyCorrect:"Asesoría profesional.",whyWrong:["Funcional.","","Relevante.","Crítico."]},
    ],
    5:[
      {q:"La tasación bancaria la realiza:",opts:["Corredor","Tasador independiente registrado CMF contratado por el banco","Cliente","Vendedor"],correct:1,whyCorrect:"Imparcialidad.",whyWrong:["Estima.","","No contrata.","No."]},
      {q:"El método de comparables usa:",opts:["Adivinación","Valores recientes de propiedades similares en la zona","Tarot","Nada"],correct:1,whyCorrect:"Método mercado.",whyWrong:["No.","","No.","Hay método."]},
      {q:"El método de costo calcula:",opts:["Precio mercado","Costo de reposición + valor terreno - depreciación",
        "Renta","Imposible"],correct:1,whyCorrect:"Método costo.",whyWrong:["Otro.","","Otro método.","Existe."]},
      {q:"El método de capitalización de renta se usa para:",opts:["Vivienda","Inversión con renta demostrable","Comprar auto","Nada"],correct:1,whyCorrect:"Propiedades que generan renta.",whyWrong:["Residencial suele usar comparables.","","No.","Hay método."]},
      {q:"Si precio pactado > valor tasación:",opts:["Sin problema","Banco financia sobre tasación; cliente cubre diferencia o renegocia precio",
        "Banco sube crédito","Automático"],correct:1,whyCorrect:"Norma bancaria.",whyWrong:["Hay problema.","","No sube.","No."]},
      {q:"El valor tasación es típicamente:",opts:["Precio mercado total","Conservador (90-105% del precio pactado)","10%","Variable salvaje"],correct:1,whyCorrect:"Criterio bancario prudencial.",whyWrong:["Más conservador.","","No.","No salvaje."]},
      {q:"Un informe de tasación incluye:",opts:["Solo precio","Metodología, fotos, comparables, terreno, construcción, depreciación, valor final",
        "Solo foto","Nada"],correct:1,whyCorrect:"Documento técnico.",whyWrong:["Incompleto.","","Incompleto.","Requerido."]},
      {q:"La tasación bancaria tiene vigencia típica:",opts:["1 día","90 a 180 días","5 años","Indefinida"],correct:1,whyCorrect:"Plazo razonable de validez.",whyWrong:["Imposible.","","Fuera.","Finita."]},
      {q:"Si la tasación baja mucho por observación DOM:",opts:["Ignorar","Resolver observación (regularizar) y solicitar re-tasación",
        "Aceptar","Imposible"],correct:1,whyCorrect:"Ruta profesional.",whyWrong:["Hay ruta.","","No aceptar sin intentar.","Posible."]},
      {q:"El tasador CMF se registra en:",opts:["Colegio","CMF (Comisión para el Mercado Financiero)","Banco","SERNAC"],correct:1,whyCorrect:"Registro oficial.",whyWrong:["No.","","No es registro oficial.","No."]},
      {q:"Un tasador independiente evita:",opts:["Nada","Conflicto de interés (el banco contrata pero tasación es técnica independiente)",
        "Trabajar","Imparcialidad"],correct:1,whyCorrect:"Principio básico.",whyWrong:["Objetivo.","","Trabaja.","Al contrario: busca imparcialidad."]},
      {q:"Los comparables usados deben ser:",opts:["Antiguos","Recientes (últimos 3-6 meses), en la misma zona y tipología similar","Azar","Ninguno"],correct:1,whyCorrect:"Fiabilidad del método.",whyWrong:["Desactualizados.","","No.","Necesarios."]},
      {q:"La depreciación considera:",opts:["Nada","Antigüedad, estado de mantención, obsolescencia funcional",
        "Color","Ubicación"],correct:1,whyCorrect:"Factores técnicos.",whyWrong:["Funcional.","","No.","Incompleto."]},
      {q:"Una propiedad con ampliación no regularizada:",opts:["Mismo valor","Se tasa sobre la superficie regularizada; la ampliación puede no sumar valor",
        "Más valor","Imposible"],correct:1,whyCorrect:"Criterio bancario.",whyWrong:["Menos valor.","","Al contrario.","Se tasa."]},
      {q:"El valor del terreno se estima con:",opts:["UF","Comparables de terrenos vacíos en la zona (método mercado)","Nada","Azar"],correct:1,whyCorrect:"Método estándar.",whyWrong:["No.","","Hay método.","No."]},
      {q:"El informe de tasación se entrega típicamente en:",opts:["1 año","7 a 15 días hábiles desde la visita","Horas","Indefinido"],correct:1,whyCorrect:"Plazo operativo.",whyWrong:["Fuera.","","Raro.","Hay plazo."]},
      {q:"Un cliente puede pedir re-tasación si:",opts:["Nunca","Hay observación DOM resuelta o comparables nuevos relevantes",
        "A gusto","Siempre"],correct:1,whyCorrect:"Casos específicos.",whyWrong:["Se puede.","","Hay criterios.","No siempre."]},
      {q:"El corredor que entiende tasación:",opts:["Nada","Negocia mejor con el vendedor y anticipa escenarios al cliente","Menos valor","Irrelevante"],correct:1,whyCorrect:"Diferenciación profesional.",whyWrong:["Relevante.","","Más valor.","Importante."]},
      {q:"Si el tasador observa problemas técnicos (estructura, humedad):",opts:["Ignora","Los consigna en el informe y el banco puede condicionar o rechazar",
        "No importa","Garantiza valor"],correct:1,whyCorrect:"Función del informe.",whyWrong:["Los anota.","","Importa.","Advierte."]},
      {q:"La tasación fiscal (SII) vs tasación bancaria:",opts:["Iguales","Conceptos distintos: SII es para impuesto; bancaria es comercial técnica",
        "Fiscal mayor","No hay diferencia"],correct:1,whyCorrect:"Distintos.",whyWrong:["Son distintas.","","Al revés.","Hay diferencia."]},
    ],
    6:[
      {q:"Los vicios redhibitorios están en:",opts:["Ley 19.472","Art. 1.858 y sgtes. Código Civil","Ley 19.496","Solo jurisprudencia"],correct:1,whyCorrect:"Cuerpo normativo específico.",whyWrong:["Otra ley.","","Otra.","Hay código."]},
      {q:"Plazo prescripción acción redhibitoria (rescisión) vivienda:",opts:["1 mes","1 año desde entrega","5 años","Nunca"],correct:1,whyCorrect:"Art. 1.866 CC.",whyWrong:["Fuera.","","Fuera.","Hay plazo."]},
      {q:"Plazo acción quanti minoris (rebaja precio) vivienda:",opts:["1 día","6 meses desde entrega","10 años","Nunca"],correct:1,whyCorrect:"Art. 1.866 CC.",whyWrong:["Fuera.","","Fuera.","Hay plazo."]},
      {q:"La Ley 19.472 protege al:",opts:["Vendedor","Comprador de vivienda nueva frente a vicios de construcción","Banco","Constructor"],correct:1,whyCorrect:"Calidad de la construcción.",whyWrong:["No.","","No.","No."]},
      {q:"Garantía estructural Ley 19.472 es:",opts:["1 año","10 años desde recepción municipal","3 años","Indefinida"],correct:1,whyCorrect:"Art. 18 letra a).",whyWrong:["Fuera.","","Otros vicios.","Finita."]},
      {q:"Garantía de instalaciones (elec., agua, gas):",opts:["1 mes","5 años desde recepción municipal","1 año","10 años"],correct:1,whyCorrect:"Art. 18 letra b).",whyWrong:["Fuera.","","Fuera.","Estructural."]},
      {q:"Garantía de terminaciones:",opts:["1 mes","3 años desde recepción municipal","10 años","1 día"],correct:1,whyCorrect:"Art. 18 letra c).",whyWrong:["Fuera.","","Estructural.","Imposible."]},
      {q:"Un vicio oculto conocido por el vendedor y no declarado:",opts:["Normal","Puede generar responsabilidad adicional (Art. 1.859 CC)","Irrelevante","Sin efecto"],correct:1,whyCorrect:"Agravante.",whyWrong:["Hay efecto.","","Relevante.","Tiene efecto."]},
      {q:"Para reclamar vicio, el comprador debe:",opts:["Nunca","Denunciar por escrito al vendedor/constructor antes del plazo de prescripción",
        "Esperar","Nada"],correct:1,whyCorrect:"Requisito procesal.",whyWrong:["Hay denuncia.","","No.","Hay que actuar."]},
      {q:"Vicios aparentes al momento de entrega:",opts:["Redhibitorios","No son vicios ocultos; el comprador debe exigir reparación en el acta de entrega",
        "Cubiertos","Ley 19.472"],correct:1,whyCorrect:"Diferencia crítica.",whyWrong:["No son redhibitorios.","","No cubierto.","Tampoco."]},
      {q:"El acta de entrega con inventario:",opts:["Es opcional","Protege al comprador dejando constancia del estado y posibles vicios aparentes",
        "Inútil","Solo foto"],correct:1,whyCorrect:"Documento clave.",whyWrong:["Esencial.","","Es útil.","No solo foto."]},
      {q:"La garantía Ley 19.472 la asume:",opts:["El banco","La primera inmobiliaria que vendió (constructora)","El Estado","El comprador"],correct:1,whyCorrect:"Responsabilidad del constructor.",whyWrong:["No.","","No.","No."]},
      {q:"La acción Ley 19.472 puede ejercerse:",opts:["Solo por el primer comprador","También por compradores sucesivos dentro del plazo si el vicio se manifiesta",
        "Nunca","Solo con abogado"],correct:1,whyCorrect:"Protección reforzada.",whyWrong:["Más amplio.","","Es posible.","No requiere."]},
      {q:"Un vicio estructural grave genera:",opts:["Multa","Obligación del constructor de reparar + indemnizaciones según resultado",
        "Nada","Solo inconveniente"],correct:1,whyCorrect:"Responsabilidad integral.",whyWrong:["Más amplio.","","Hay efecto.","Es grave."]},
      {q:"El corredor al entregar la vivienda debe:",opts:["Nada","Informar los plazos de garantía legal y documentar el estado en acta de entrega",
        "Callar","Pagar"],correct:1,whyCorrect:"Servicio profesional.",whyWrong:["Hay deber.","","Mala fe.","No le corresponde."]},
      {q:"Los vicios conocidos por el comprador al comprar:",opts:["Siguen cubiertos","No son redhibitorios (asumió el riesgo)","Cubiertos siempre","Anulan venta"],correct:1,whyCorrect:"Principio jurídico.",whyWrong:["No.","","No.","No."]},
      {q:"La garantía DFL 2 para primera vivienda:",opts:["No existe","Es otro instrumento tributario distinto a Ley 19.472","Cubre vicios","Nada"],correct:1,whyCorrect:"DFL 2 es régimen tributario, distinto de calidad.",whyWrong:["Existe.","","No cubre vicios.","Existe."]},
      {q:"El cliente que descubre vicio tarde:",opts:["Pierde","Puede reclamar si está dentro del plazo de prescripción aplicable",
        "Siempre pierde","Nada"],correct:1,whyCorrect:"Plazos ley.",whyWrong:["Puede.","","Hay plazos.","Hay acción."]},
      {q:"Las fuentes para sustentar un vicio redhibitorio son:",opts:["Nada","Informes técnicos + fotos + actas + peritajes",
        "Solo palabra","WhatsApp"],correct:1,whyCorrect:"Prueba legal.",whyWrong:["Hay fuentes.","","Insuficiente.","No."]},
      {q:"La mediación antes de juicio en vicios es:",opts:["Ilegal","Vía recomendada: CChC, SERNAC Construcción y otras instancias",
        "Automática","Innecesaria"],correct:1,whyCorrect:"Resolución alternativa.",whyWrong:["Legal.","","No automática.","Muy útil."]},
    ],
    7:[
      {q:"La Ley 21.442 regula:",opts:["Hipotecas","Copropiedad inmobiliaria (reemplazó la Ley 19.537)","Subsidios","Arriendo"],correct:1,whyCorrect:"Normativa vigente desde 2022.",whyWrong:["No.","","No.","No."]},
      {q:"El Reglamento de Copropiedad se inscribe en:",opts:["Municipio","CBR","SII","Notaría solo"],correct:1,whyCorrect:"Publicidad registral.",whyWrong:["No.","","Fiscal.","Notaría otorga, CBR inscribe."]},
      {q:"Los gastos comunes los fija:",opts:["Libremente","La asamblea de copropietarios y el presupuesto anual","Dueño","Municipio"],correct:1,whyCorrect:"Órgano máximo de la comunidad.",whyWrong:["No.","","No.","No."]},
      {q:"El fondo de reserva mínimo en la Ley 21.442 es:",opts:["0","Al menos 5% de los gastos comunes","Variable libre","No existe"],correct:1,whyCorrect:"Obligación legal.",whyWrong:["Hay mínimo.","","Tiene mínimo.","Existe."]},
      {q:"El administrador de copropiedad:",opts:["Dueño","Persona designada por asamblea con funciones ejecutivas",
        "Notario","Municipio"],correct:1,whyCorrect:"Rol ejecutivo.",whyWrong:["No.","","No.","No."]},
      {q:"Un comprador de departamento hereda:",opts:["Nada","Derechos y obligaciones del régimen de copropiedad, incluidas deudas de gastos comunes",
        "Solo metros","Solo fotos"],correct:1,whyCorrect:"Situación sui generis.",whyWrong:["Hay heredación.","","Más.","No."]},
      {q:"El certificado de gastos comunes al día:",opts:["Irrelevante","Debe solicitarse antes de firmar · el administrador lo emite",
        "Nunca","Solo nuevos"],correct:1,whyCorrect:"Protección al comprador.",whyWrong:["Crítico.","","Se debe.","Cualquier departamento."]},
      {q:"Una derrama no pagada se traspasa:",opts:["Al vendedor","Puede cobrarse al comprador si no se regularizó · siempre verificar antes",
        "Al banco","Al notario"],correct:1,whyCorrect:"Obligación real sobre el inmueble.",whyWrong:["Ambos potencialmente.","","No.","No."]},
      {q:"Airbnb en un edificio depende de:",opts:["Libertad absoluta","El reglamento de copropiedad; muchos edificios prohíben arriendo corta estadía",
        "Solo ley","No importa"],correct:1,whyCorrect:"Régimen privado.",whyWrong:["No libertad.","","Depende reglamento.","Importa."]},
      {q:"Las mascotas en copropiedad:",opts:["Siempre prohibidas","Reguladas por el reglamento; la Ley 21.135 limita prohibiciones absolutas","Sin regla","Sin ley"],correct:1,whyCorrect:"Ley tenencia responsable.",whyWrong:["Hay límites.","","Hay regla.","Hay ley."]},
      {q:"La asamblea ordinaria de copropietarios se convoca:",opts:["Cada 5 años","Al menos una vez al año (ordinaria)","Nunca","Solo por juez"],correct:1,whyCorrect:"Regla ley.",whyWrong:["Fuera.","","Obligatoria.","Fuera."]},
      {q:"Una asamblea extraordinaria se convoca por:",opts:["Libertad","Situaciones específicas del reglamento o por decisión del administrador/copropietarios",
        "Solo banco","Nunca"],correct:1,whyCorrect:"Gestión extraordinaria.",whyWrong:["Hay reglas.","","No.","Se convoca."]},
      {q:"El quórum para modificar reglamento es:",opts:["Mayoría simple","Típicamente mayoría calificada según la Ley 21.442",
        "1 persona","Todos"],correct:1,whyCorrect:"Protección de minoritarios.",whyWrong:["Calificada.","","No.","No."]},
      {q:"El cobro judicial de gastos comunes impagos:",opts:["No existe","Procede por vía ejecutiva con el acta de deuda certificada por el administrador",
        "Solo con juicio ordinario","Solo arbitraje"],correct:1,whyCorrect:"Procedimiento específico.",whyWrong:["Existe.","","Es ejecutivo.","No solo arbitraje."]},
      {q:"Las obras comunes mayores requieren:",opts:["Nada","Aprobación de asamblea con quórum según el reglamento y ley",
        "Solo administrador","Solo un copropietario"],correct:1,whyCorrect:"Regla mínima.",whyWrong:["Requiere.","","No solo.","No."]},
      {q:"La Ley 21.442 fortaleció:",opts:["Nada","Derechos del copropietario minoritario, transparencia y administración",
        "Solo administrador","Solo dueños"],correct:1,whyCorrect:"Modernización regulatoria.",whyWrong:["Avanzó.","","No solo.","Balance."]},
      {q:"Un departamento con uso comercial permitido:",opts:["Irrelevante","Debe estar autorizado por reglamento + DOM + patente municipal",
        "Libre","Sin requisitos"],correct:1,whyCorrect:"Multiples regulaciones.",whyWrong:["Tiene requisitos.","","No libre.","Los hay."]},
      {q:"El corredor debe entregar al comprador copia del:",opts:["Nada","Reglamento de copropiedad para revisión antes de firmar",
        "Solo foto","Sólo Dicom"],correct:1,whyCorrect:"Debida diligencia.",whyWrong:["Debe.","","Insuficiente.","No es relevante."]},
      {q:"Un fondo operacional (Ley 21.442) es:",opts:["No existe","Recursos para gastos extraordinarios menores, distinto del fondo de reserva",
        "Igual al reserva","Inútil"],correct:1,whyCorrect:"Instrumento adicional.",whyWrong:["Existe.","","Distinto.","Útil."]},
      {q:"La antigüedad del edificio impacta:",opts:["Nada","Gastos comunes históricos, estado de mantenimiento, fondo disponible",
        "Solo color","Imposible medir"],correct:1,whyCorrect:"Factor real.",whyWrong:["Impacta.","","No es solo estética.","Se mide."]},
    ],
  },
  finalQuestions:[
    {q:"El CBR inscribe:",opts:["Personas","Actos sobre inmuebles (compraventas, hipotecas, gravámenes)","Autos","Nada"],correct:1,whyCorrect:"Registro público.",whyWrong:["Otro.","","No.","Registra."]},
    {q:"ROL SII identifica:",opts:["Dueño","Propiedad fiscalmente","Banco","Corredor"],correct:1,whyCorrect:"Tributario.",whyWrong:["CBR.","","No.","No."]},
    {q:"Estudio de títulos revisa:",opts:["1 año","10 años (prescripción extraordinaria)","100 años","1 día"],correct:1,whyCorrect:"Plazo ley.",whyWrong:["Insuficiente.","","Excesivo.","Imposible."]},
    {q:"Ley 19.472 garantía estructural:",opts:["1 año","10 años","3 años","Indefinida"],correct:1,whyCorrect:"Art 18 a.",whyWrong:["Fuera.","","Terminaciones.","Finita."]},
    {q:"Ley 19.472 garantía instalaciones:",opts:["1 mes","5 años","1 año","10 años"],correct:1,whyCorrect:"Art 18 b.",whyWrong:["Fuera.","","Fuera.","Estructural."]},
    {q:"Ley 19.472 garantía terminaciones:",opts:["1 mes","3 años","10 años","1 día"],correct:1,whyCorrect:"Art 18 c.",whyWrong:["Fuera.","","Estructural.","Imposible."]},
    {q:"Vicio redhibitorio acción rescisión:",opts:["1 mes","1 año desde entrega","5 años","Nunca"],correct:1,whyCorrect:"Art 1.866 CC.",whyWrong:["Fuera.","","Fuera.","Hay."]},
    {q:"Vicio redhibitorio acción quanti minoris:",opts:["1 día","6 meses desde entrega","10 años","Nunca"],correct:1,whyCorrect:"Art 1.866 CC.",whyWrong:["Fuera.","","Fuera.","Hay."]},
    {q:"Certificado dominio vigente muestra:",opts:["Avalúo","Dueño inscrito","Contribución","Arriendo"],correct:1,whyCorrect:"CBR.",whyWrong:["SII.","","No.","No."]},
    {q:"Certificado hipotecas y gravámenes:",opts:["Precios","Cargas sobre la propiedad","Dueños","Nada"],correct:1,whyCorrect:"Gravámenes.",whyWrong:["No.","","Otro.","Funcional."]},
    {q:"Ley 21.442 regula:",opts:["Hipoteca","Copropiedad inmobiliaria","Subsidios","Arriendo"],correct:1,whyCorrect:"Copropiedad.",whyWrong:["No.","","No.","No."]},
    {q:"Fondo de reserva mínimo:",opts:["0","5% de gastos comunes","50%","Libre"],correct:1,whyCorrect:"Ley 21.442.",whyWrong:["Hay.","","Excesivo.","Hay mínimo."]},
    {q:"Tasación la realiza:",opts:["Corredor","Tasador CMF independiente","Cliente","Vendedor"],correct:1,whyCorrect:"Imparcialidad.",whyWrong:["Estima.","","No.","No."]},
    {q:"Método tasación residencial:",opts:["Azar","Comparables · mercado","Renta solamente","Nada"],correct:1,whyCorrect:"Método principal.",whyWrong:["No.","","Inversión.","Hay."]},
    {q:"Si precio > tasación:",opts:["Ok","Cliente aporta diferencia o renegocia","Banco sube","Automático"],correct:1,whyCorrect:"Norma bancaria.",whyWrong:["Hay problema.","","No sube.","No."]},
    {q:"Recepción Final DOM certifica:",opts:["Venta","Obra terminada conforme normativa","Precio","Avalúo"],correct:1,whyCorrect:"Validación técnica.",whyWrong:["No.","","Fiscal.","No."]},
    {q:"Sin Recepción Final:",opts:["Nada","Problemas tasación y crédito","Mejor precio","Imposible"],correct:1,whyCorrect:"Puede bloquear.",whyWrong:["Problema.","","No.","Con trámite se arregla."]},
    {q:"Ampliación sin permiso:",opts:["Legal","Irregular · Ley 20.898 facilita regularizar","Normal","Nula"],correct:1,whyCorrect:"Regularización.",whyWrong:["No.","","Hay procedimiento.","No nula."]},
    {q:"CIP muestra:",opts:["Precio","Normas urbanísticas del predio","Dueño","Nada"],correct:1,whyCorrect:"Define usos.",whyWrong:["No.","","Otro.","Es funcional."]},
    {q:"Reglamento copropiedad se inscribe:",opts:["Municipio","CBR","SII","Notaría solo"],correct:1,whyCorrect:"Publicidad registral.",whyWrong:["No.","","No.","CBR."]},
    {q:"Airbnb en edificio depende:",opts:["Libre","Reglamento copropiedad","Ley única","Nada"],correct:1,whyCorrect:"Régimen privado.",whyWrong:["Reglamento.","","No solo.","Depende."]},
    {q:"Gastos comunes no pagados por vendedor:",opts:["Banco","Pueden cobrarse al comprador","Automático","Ignorar"],correct:1,whyCorrect:"Obligación real.",whyWrong:["No.","","No automático.","Verificar."]},
    {q:"Prohibición DS1 post-compra:",opts:["Ninguna","5 años desde inscripción","10 años","Indefinida"],correct:1,whyCorrect:"Antiespeculación.",whyWrong:["Hay.","","Fuera.","Finita."]},
    {q:"Estudio títulos lo hace:",opts:["Corredor","Abogado especialista","Notario","Cliente"],correct:1,whyCorrect:"Dictamen profesional.",whyWrong:["Insuficiente.","","Otro rol.","No."]},
    {q:"Línea oficial se obtiene en:",opts:["Banco","DOM","CBR","SII"],correct:1,whyCorrect:"Municipal.",whyWrong:["No.","","Otro.","No."]},
    {q:"Acta de entrega incluye:",opts:["Foto","Acta + llaves + estado + documentos técnicos","WhatsApp","Nada"],correct:1,whyCorrect:"Buenas prácticas.",whyWrong:["Insuficiente.","","Informal.","Sin respaldo."]},
    {q:"La tasación bancaria tiene vigencia:",opts:["1 día","90-180 días","5 años","Indefinida"],correct:1,whyCorrect:"Operativo.",whyWrong:["Imposible.","","Fuera.","Finita."]},
    {q:"Vicio oculto conocido por vendedor no declarado:",opts:["Normal","Genera responsabilidad adicional","Irrelevante","Nada"],correct:1,whyCorrect:"Agravante.",whyWrong:["Hay.","","Relevante.","Efectos."]},
    {q:"Vicios aparentes al entregar:",opts:["Redhibitorios","No son vicios ocultos · exigir en acta entrega","Cubiertos","Ley 19.472"],correct:1,whyCorrect:"Diferencia crítica.",whyWrong:["No.","","No.","Tampoco."]},
    {q:"Antes de firmar promesa, certificados CBR:",opts:["Obsoletos","Fecha < 30 días","10 años","Sin fecha"],correct:1,whyCorrect:"Vigente.",whyWrong:["No sirve.","","Imposible.","Requerida."]},
    {q:"Deudas servicios básicos:",opts:["Sin efecto","Regularizar o retener del precio","Automáticas","Ilegales"],correct:1,whyCorrect:"Protección.",whyWrong:["Hay.","","No.","No."]},
    {q:"Patente comercial pendiente afecta:",opts:["Nunca","Puede afectar si la propiedad se usó como negocio","Siempre","Ilegal"],correct:1,whyCorrect:"Verificar.",whyWrong:["Puede.","","No siempre.","No ilegal."]},
    {q:"Número Municipal es:",opts:["Precio","Dirección oficial","Teléfono","Clave"],correct:1,whyCorrect:"Oficial.",whyWrong:["No.","","No.","No."]},
    {q:"Plan regulador comunal define:",opts:["Precios","Usos, alturas, zonificación del territorio comunal","Dueños","Contribuciones"],correct:1,whyCorrect:"Instrumento urbano.",whyWrong:["No.","","No.","Otro."]},
    {q:"Propiedad en zona conservación histórica:",opts:["Normal","Restricciones para remodelar/demoler (Ley 17.288)","Sin reglas","Más barata"],correct:1,whyCorrect:"Monumentos nacionales.",whyWrong:["No normal.","","Hay.","No necesariamente."]},
    {q:"La línea oficial delimita:",opts:["Nada","El deslinde legal del predio","Municipio","Pasillo"],correct:1,whyCorrect:"Delimita.",whyWrong:["Importa.","","No.","No."]},
    {q:"Costo estudio títulos:",opts:["Gratis","$150.000 a $400.000 según abogado","$5M","$0"],correct:1,whyCorrect:"Profesional.",whyWrong:["No.","","Excesivo.","Hay costo."]},
    {q:"Hipoteca anterior no alzada:",opts:["Pagada","Subsiste · riesgo","Sin efecto","Ignorada"],correct:1,whyCorrect:"Todo gravamen subsiste.",whyWrong:["No automático.","","Tiene.","No."]},
    {q:"Comparables tasación deben ser:",opts:["Antiguos","Recientes (3-6 meses), misma zona y tipología","Azar","Irrelevantes"],correct:1,whyCorrect:"Fiabilidad.",whyWrong:["No.","","No.","Son relevantes."]},
    {q:"Fondo operacional (Ley 21.442):",opts:["No existe","Gastos extraordinarios menores, distinto del de reserva",
      "Igual reserva","Inútil"],correct:1,whyCorrect:"Instrumento propio.",whyWrong:["Existe.","","Distinto.","Útil."]},
    {q:"Asamblea ordinaria copropiedad:",opts:["Cada 5 años","Al menos 1 vez al año","Nunca","Solo juez"],correct:1,whyCorrect:"Ley.",whyWrong:["Fuera.","","Obligatoria.","Fuera."]},
    {q:"Derrama pendiente:",opts:["Al vendedor","Puede cobrarse al comprador","Al banco","Notario"],correct:1,whyCorrect:"Obligación real.",whyWrong:["Potencial.","","No.","No."]},
    {q:"Un tasador CMF:",opts:["Colegio","Registrado en CMF","Banco","SERNAC"],correct:1,whyCorrect:"Registro oficial.",whyWrong:["No.","","No.","No."]},
    {q:"Método costo tasación:",opts:["Precio","Costo reposición + terreno - depreciación","Renta","Nada"],correct:1,whyCorrect:"Método costo.",whyWrong:["Otro.","","Otro.","Existe."]},
    {q:"Quórum modificar reglamento copropiedad:",opts:["Simple","Calificada según Ley 21.442","1 persona","Todos"],correct:1,whyCorrect:"Protección.",whyWrong:["No.","","No.","No."]},
    {q:"Cobro gastos comunes impagos:",opts:["No existe","Vía ejecutiva con acta administrador","Ordinario","Arbitraje"],correct:1,whyCorrect:"Procedimiento específico.",whyWrong:["Existe.","","Ejecutiva.","No."]},
    {q:"Ampliación no regularizada y tasación:",opts:["Mismo valor","Tasa solo superficie regularizada","Más valor","Imposible"],correct:1,whyCorrect:"Criterio bancario.",whyWrong:["Menos.","","Al revés.","Se tasa."]},
    {q:"Certificado no expropiación verifica:",opts:["Uso","Predio no en plan de expropiación","Precio","Dueño"],correct:1,whyCorrect:"Protección comprador.",whyWrong:["No.","","No.","Otro."]},
    {q:"Acción reivindicatoria post compra:",opts:["Nunca","Posible si hay vicio en cadena · por eso estudio",
      "Automática","Irrelevante"],correct:1,whyCorrect:"Riesgo real.",whyWrong:["Existe.","","No automática.","Muy relevante."]},
    {q:"Sucesión sin posesión efectiva inscrita:",opts:["Válida","Bloquea enajenación hasta inscribir",
      "Sin efecto","Indiferente"],correct:1,whyCorrect:"Requisito previo.",whyWrong:["Bloquea.","","Bloquea.","Crítica."]},
  ],
  goldRules:[
    {n:1,title:"Sin CBR no hay propiedad",text:"Dominio vigente + hipotecas + prohibiciones. Certificados siempre con fecha reciente (<30 días)."},
    {n:2,title:"Estudio de títulos 10 años obligatorio",text:"Abogado profesional. Observaciones se resuelven antes de la promesa o se abandona la operación."},
    {n:3,title:"ROL SII y contribuciones al día antes de firmar",text:"Si hay deuda, regularización o retención del precio. Nunca asumir riesgo fiscal del vendedor."},
    {n:4,title:"DOM: Recepción Final y regularizaciones",text:"Sin Recepción Final hay problemas para tasar e inscribir. Ampliaciones sin permiso: regularizar o descontar precio."},
    {n:5,title:"Tasación determina monto crédito",text:"Banco financia sobre tasación, no precio. Si precio > tasación, aporta pie adicional o renegocia."},
    {n:6,title:"Ley 19.472 garantías: 3-5-10 años",text:"Terminaciones 3 años · instalaciones 5 · estructural 10, desde recepción municipal. Avisa siempre al comprador."},
    {n:7,title:"Vicios redhibitorios tienen plazo",text:"Rescisión 1 año · rebaja 6 meses desde entrega (Art. 1.866 CC). Después prescribe."},
    {n:8,title:"Copropiedad Ley 21.442",text:"Reglamento + gastos al día + fondo de reserva ≥ 5%. Léelo antes de firmar departamento."},
    {n:9,title:"Acta de entrega con inventario",text:"Protege al comprador. Fotos, estado, documentos técnicos. Clave para reclamar vicios aparentes y exigir Ley 19.472."},
    {n:10,title:"Due diligence es activo del corredor",text:"Un cliente bien protegido refiere. Un cliente con sorpresa post-firma te daña profesionalmente para siempre."},
  ],
};
