/* Taller 06 · Negociación y Cierre · Banco v1
   Fuentes: Código Civil Chile, Art. 1.554, 1.803, 1.805, 1.535; Fisher-Ury "Getting to Yes" */
window.TALLER_CONFIG = {
  slug: 'negociacion-cierre',
  moduleNames: {
    1:'Fundamentos negociación · Fisher-Ury',2:'Oferta, contraoferta y tempo',3:'Promesa compraventa · Art. 1.554 CC',
    4:'Arras, multas y cláusulas penales',5:'Escritura pública y mutuo',
    6:'Caídas y contingencias',7:'Entrega material y acta',
  },
  certTitle:'Negociación y Cierre', certSubtitle:'Taller Avanzado 06 · Academia TuMatch',
  quizBank: buildBank(), finalQuestions: buildFinal(), goldRules: buildGold(),
};

function buildBank(){
  const Q = (q,opts,correct,wc,ww)=>({q,opts,correct,whyCorrect:wc,whyWrong:ww});
  const filler = (n, base)=>{
    const r = []; for(let i=0;i<n;i++) r.push(base[i%base.length]); return r;
  };
  const m1 = [
    Q("El método Principled de Fisher-Ury (Harvard 1981) se basa en:",["Imponer posición","Separar personas, centrar en intereses, generar opciones, usar criterios objetivos","Engañar","Manipular"],1,"Cuatro principios centrales.",["No.","","Antiético.","Antiético."]),
    Q("BATNA es:",["Banco","Best Alternative To Negotiated Agreement (alternativa si no hay acuerdo)","Oferta","Ningún"],1,"Poder relativo del negociador.",["No.","","No.","Existe."]),
    Q("ZOPA es:",["Sin sentido","Zone Of Possible Agreement (intersección precios min vendedor / max comprador)","Banco","Ley"],1,"Donde el acuerdo es posible.",["Existe.","","No.","No."]),
    Q("Interés vs posición:",["Son iguales","Posición es 'quiero X'; interés es 'por qué' (motivación subyacente)","Interés es lo mismo","No importa"],1,"Clave para desatorar negociación.",["Distintos.","","Lo opuesto.","Crítico."]),
    Q("Una opción creativa en compraventa es:",["Sin posibilidad","Incluir muebles, diferir entrega, pago diferido, parte en UF parte en pesos","Solo precio","Imposible"],1,"Expande ZOPA.",["Existe.","","Limitado.","Posible."]),
    Q("Separar personas del problema significa:",["Culpar","No llevar ego a la mesa; foco en el asunto objetivo","Atacar","Ignorar"],1,"Reduce escalada.",["Contraproducente.","","Daña.","Abdica."]),
    Q("Criterios objetivos incluyen:",["Capricho","Tasación, comparables, avalúo, índices oficiales","Nada","Color"],1,"Anclaje racional.",["No.","","Hay.","Irrelevante."]),
    Q("Escuchar activamente al vendedor te revela:",["Nada","Intereses ocultos (mudanza, urgencia, rango aceptable) que permiten crear valor","Solo precio","Secretos"],1,"Oro para el negociador.",["Hay.","","Mucho más.","No manipulación."]),
    Q("El poder en negociación viene de:",["Agresividad","BATNA: entre mejor alternativa, más poder real","Gritar","Mentir"],1,"Fundamento del método.",["No.","","Antiprofesional.","Antiético."]),
    Q("Si tu cliente tiene mejor alternativa (otra propiedad aceptable):",["Debilita","Fortalece; puedes negociar con más tranquilidad","Igual","Obliga"],1,"BATNA alto = más poder.",["Al contrario.","","Depende.","No."]),
    Q("Una negociación competitiva pura (win-lose):",["Ideal","Inferior a principled en transacciones de largo plazo o con repercusión reputacional","Siempre gana","Única vía"],1,"Daña relaciones y referidos.",["Mala.","","No siempre.","Hay mejores."]),
    Q("La preparación previa a negociar incluye:",["Nada","Investigar intereses, tasación, comparables, BATNA propio y del otro","Solo precio","Improvisar"],1,"Inversión que decide resultado.",["Necesaria.","","Insuficiente.","Mala."]),
    Q("Hacer la primera oferta en compraventa:",["Nunca","Con ancla fundamentada (tasación + comparables) puede marcar el marco de la negociación","Siempre evítalo","Sin efecto"],1,"Efecto anclaje.",["Depende.","","Hay casos.","Tiene efecto."]),
    Q("Cuando el otro hace una oferta muy baja:",["Ofendes","Pides fundamento técnico y contrarrestas con comparables + tasación","Aceptas","Abandonas"],1,"Respuesta profesional.",["Mala.","","Inaceptable.","Prematuro."]),
    Q("Si el vendedor dice 'es mi precio final':",["Te vas","Exploras si hay intereses detrás no cubiertos (plazo, condiciones) para crear valor","Aceptas","Peleas"],1,"Opciones creativas.",["Antes explora.","","Sin intentar.","Improductivo."]),
    Q("Una concesión en negociación debe:",["Darse libre","Intercambiarse por algo de valor similar; nunca gratis","Siempre ceder","Nunca"],1,"Reciprocidad estructurada.",["Mala.","","Indulgente.","No."]),
    Q("El corredor en la negociación representa:",["Ambos","Formalmente uno de los lados; debe declarar representación y mantener ética",
      "Ninguno","Al banco"],1,"Transparencia profesional.",["Depende contrato.","","Representa.","No."]),
    Q("Doble representación (ambas partes):",["Libre","Posible con consentimiento informado escrito de ambas partes; requiere máxima transparencia","Prohibida","Normal"],1,"Riesgo ético que debe documentarse.",["No libre.","","Posible con requisitos.","Requiere cuidados."]),
    Q("Si se atora la negociación sobre precio:",["Acabar","Buscar otras variables (plazo, entrega, condiciones, muebles) para desatar",
      "Rigidez","Mentir"],1,"Opciones creativas.",["Mala.","","Mala práctica.","Antiético."]),
    Q("El cierre principled se caracteriza por:",["Trampa","Acuerdo donde ambas partes sienten que ganaron valor real","Ganas todo","Pierdes"],1,"Acuerdo sostenible.",["No.","","Lose para otro.","No."]),
  ];
  const m2 = [
    Q("La oferta escrita debe incluir:",["Solo precio","Precio + plazo respuesta + condiciones suspensivas + validez + modo de pago","Firma","Nada"],1,"Elementos formales.",["Insuficiente.","","Incompleto.","Sin contrato."]),
    Q("El plazo de respuesta típico en oferta primera vivienda es:",["10 min","48 a 72 horas habituales","1 día","Un mes"],1,"Permite análisis sin urgencia fabricada.",["Demasiado corto.","","Insuficiente.","Excesivo."]),
    Q("La contraoferta:",["Nunca","Modificación de la oferta original; inicia nueva negociación formal","Siempre","Solo verbal"],1,"Respuesta estándar.",["Es natural.","","Depende.","Debe ser escrita."]),
    Q("El tempo entre oferta y contraoferta:",["Irrelevante","Comunica seriedad o desespero; mantener ritmo profesional",
      "Inmediato siempre","Años"],1,"Coreografía comunicacional.",["Importa.","","Agresivo.","Imposible."]),
    Q("La seña / reserva habitual en compraventa es:",["0%","3-5% del precio pactado","50%","100%"],1,"Práctica estándar.",["Sin reserva no hay seriedad.","","Fuera.","Fuera."]),
    Q("Una oferta con condiciones ambiguas:",["Vale","Abre puerta a disputas; condiciones siempre específicas y verificables","Mejor","Ilegal"],1,"Riesgo interpretativo.",["Problemas.","","Al contrario.","Legal pero mala."]),
    Q("Si el vendedor acepta parcialmente (contraoferta):",["Acuerdo","No hay acuerdo aún; es nueva oferta que el comprador acepta/rechaza",
      "Sin efecto","Litigio"],1,"Principio de correspondencia.",["No hay.","","Tiene.","No."]),
    Q("La oferta vinculante entrega al vendedor:",["Nada","Obligación de responder en el plazo antes del vencimiento","Tiempo ilimitado","Libertad"],1,"Efecto temporal.",["Hay obligación.","","Hay plazo.","Limitada."]),
    Q("Una contraoferta demasiado alta (anclaje extremo):",["Funciona siempre","Puede cerrar la conversación; requiere sensibilidad al mercado",
      "Ideal","Irrelevante"],1,"Límites del anclaje.",["No siempre.","","Riesgoso.","Relevante."]),
    Q("El corredor al recibir contraoferta del vendedor:",["Acepta","La transmite formalmente al comprador con fundamentos y recomendación","Rechaza","Oculta"],1,"Servicio profesional.",["Sin analizar no.","","No prejuicio.","Fraude."]),
    Q("Una oferta válida solo 24 horas:",["Normal","Puede ser percibida como presión si no hay razón objetiva","Absurda","Ilegal"],1,"Sensibilidad al contexto.",["Depende.","","No.","No ilegal."]),
    Q("Ofertas vinculantes múltiples por un comprador:",["Sin riesgo","Si hay aceptación simultánea puede comprometerse doble; riesgo real",
      "Bien","Ilegal"],1,"Cuidado jurídico.",["Hay.","","Riesgoso.","No ilegal per se."]),
    Q("Ofertas múltiples para el vendedor (varios compradores):",["Solo acepta una","Puede negociar con todas, aceptar la mejor una vez decidida","Prohibido","Sin regla"],1,"Mercado libre.",["Sí puede negociar.","","Legal.","Hay."]),
    Q("Si el vendedor acepta fuera del plazo:",["Vinculante","Ya no es aceptación; es contraoferta (oferta cruzada)",
      "Nulo","Sin efecto"],1,"Efecto temporal.",["No.","","Transformación.","Tiene efecto."]),
    Q("La condición 'sujeto a pre-aprobación bancaria':",["Vago","Debe indicar banco, monto mínimo, plazo y ruta de verificación","Solo firma","Nada"],1,"Especificidad legal.",["Específico.","","Insuficiente.","Crítico."]),
    Q("El anclaje numérico inicial:",["Sin efecto","Influye la ZOPA final estadísticamente; usar con fundamento","Siempre error","Sin relevancia"],1,"Fenómeno validado.",["Tiene.","","Herramienta.","Relevante."]),
    Q("La urgencia fabricada:",["Efectiva","Funciona corto plazo pero daña reputación; no usar en transacciones grandes","Sin efecto","Prohibida"],1,"Ética profesional.",["Daña.","","Tiene efecto corto.","No prohibida pero mala práctica."]),
    Q("Un vendedor que pide 'contra-oferta mejor':",["Frustrante","Oportunidad para pedir su rango y proponer variables creativas","Peleable","Abandonar"],1,"Exploración.",["Oportunidad.","","Improductivo.","Prematuro."]),
    Q("El precio pactado en UF vs en pesos:",["Iguales","UF se reajusta con IPC · en compraventa estándar se pacta en UF",
      "Pesos preferible","Sin diferencia"],1,"Práctica chilena.",["Distintos.","","Raro.","Hay."]),
    Q("La mejor oferta suele estar:",["Al comienzo","En un rango negociado con respeto y fundamento técnico",
      "Al final siempre","Imprevisible"],1,"Negociación madura.",["Depende.","","No siempre.","Analizable."]),
  ];
  const m3 = [
    Q("La promesa se rige por:",["Ley 19.281","Art. 1.554 del Código Civil","Ley 18.010","CMF"],1,"Norma específica.",["Es leasing.","","Créditos.","No."]),
    Q("La promesa debe ser:",["Verbal","Escrita (privada con firmas autorizadas o escritura pública)","Verbal o escrita","Silencio"],1,"Requisito solemnidad.",["Nula.","","Escrita.","Absurdo."]),
    Q("Plazo o condición que fije época del contrato definitivo:",["Innecesario","Requisito esencial del Art. 1.554 CC","Opcional","Nunca"],1,"Requisito de validez.",["Es esencial.","","Opcional.","Siempre requerido."]),
    Q("Identificación del contrato futuro en la promesa:",["Vaga","Tal que solo falten declaraciones o tradición","Genérica","Opcional"],1,"Especificidad requerida.",["Problema.","","Insuficiente.","Requerida."]),
    Q("Cosa lícita en la promesa:",["Cualquiera","Objeto lícito · no enajenable o gravado inejecutablemente",
      "No importa","Prohibida"],1,"Requisito sustantivo.",["No cualquiera.","","Importa.","No permitida en objetos ilícitos."]),
    Q("Condición suspensiva 'pre-aprobación bancaria' se cumple cuando:",["Nunca","El banco emite carta pre-aprobación por monto y plazo específico",
      "Al solicitar","Depende cliente"],1,"Hito objetivo.",["Hay hito.","","Insuficiente.","Objetivo."]),
    Q("Condición suspensiva 'alzamiento hipoteca vendedor':",["No existe","Se cumple al obtener certificado de alzamiento del banco vendedor",
      "Automática","Irrelevante"],1,"Hito documental.",["Existe.","","No automática.","Crítica."]),
    Q("Si una condición suspensiva no se cumple en plazo:",["Se cierra","La promesa queda sin efecto (si así se pactó) y partes recuperan seña",
      "Multa","Ignorar"],1,"Régimen de condiciones.",["No necesariamente.","","Depende.","No."]),
    Q("La promesa por instrumento privado:",["Válida","Requiere firmas autorizadas ante notario para alcance probatorio",
      "Siempre suficiente","Nunca"],1,"Formalización.",["Requiere formalización.","","Hay exigencias.","Es posible."]),
    Q("La promesa inscribible en CBR:",["Siempre","No se inscribe como regla · salvo leasing habitacional u otros casos especiales",
      "Obligatorio","Nunca"],1,"Distinto de la compraventa definitiva.",["Generalmente no.","","No es obligatoria.","Hay excepciones."]),
    Q("Plazo típico entre promesa y escritura:",["1 día","30 a 60 días","5 años","1 hora"],1,"Plazo operativo.",["Imposible.","","Fuera.","Imposible."]),
    Q("Si el vendedor no comparece a la firma de escritura pactada en promesa:",["Nada","Incumplimiento que activa cláusula penal si existe o indemnización",
      "Pierde casa","Ignorar"],1,"Responsabilidad contractual.",["Hay consecuencia.","","Medida extrema.","No."]),
    Q("Si el comprador no comparece:",["Nada","Incumplimiento recíproco · puede perder seña o asumir multa según pactado","Libre","Sin efecto"],1,"Simetría contractual.",["Consecuencia.","","No.","Tiene."]),
    Q("La promesa con 'condición potestativa pura':",["Válida","Art. 1.478 CC limita validez de condiciones que dependen de voluntad del deudor",
      "Libre","Siempre nula"],1,"Régimen de condiciones.",["Hay limitación.","","Hay reglas.","No siempre."]),
    Q("La promesa con plazo indefinido:",["Válida","Plazo razonable o condición que fije época · 1.554 CC exige delimitación",
      "Libre","Sin problema"],1,"Requisito esencial.",["Requiere.","","Hay requisito.","Hay problema."]),
    Q("Multa en promesa:",["Ilegal","Válida como cláusula penal (Art. 1.535 CC) dentro de los límites",
      "Sin efecto","Prohibida"],1,"Fundamento legal.",["Legal.","","Tiene.","No prohibida."]),
    Q("La cesión del contrato de promesa:",["Nunca","Posible si se pactó o con consentimiento de ambas partes",
      "Libre","Prohibida"],1,"Pacto o consenso.",["Es posible.","","No libre.","No prohibida."]),
    Q("Si en promesa se pactó 'entrega 60 días' y se atrasa:",["Inmodificable","Se puede ampliar de mutuo acuerdo mediante anexo a la promesa",
      "Rompe todo","Sin efecto"],1,"Flexibilidad consensual.",["Flexible.","","No rompe.","Hay solución."]),
    Q("Si un inmueble objeto de promesa se destruye:",["Irrelevante","Se aplican reglas de riesgo; contrato puede resolverse",
      "Compra igual","Multa enorme"],1,"Teoría de riesgos.",["Hay reglas.","","No.","Depende."]),
    Q("Promesa con firma privada sin autorización notarial:",["Plena valor","Puede tener problemas probatorios · mejor con firmas autorizadas",
      "Nula","Siempre válida"],1,"Prueba legal.",["Débil.","","No nula automático.","Hay riesgo."]),
  ];
  const m4 = [
    Q("Arras confirmatorias (por defecto):",["Autorizan retracto","Parte anticipada del precio; no autorizan retractarse","Libres","Ilegales"],1,"Presunción legal.",["No.","","No libres.","Legales."]),
    Q("Arras penitenciales (Art. 1.803 CC):",["Igual a confirmatorias","Autorizan retracto · comprador pierde arras · vendedor restituye el doble",
      "Prohibidas","Sin efecto"],1,"Figura clásica.",["Distintas.","","Válidas.","Tienen."]),
    Q("Para que sean penitenciales, las arras deben:",["Solo entregarse","Pactarse expresamente como tales; de lo contrario son confirmatorias",
      "Siempre","Nunca"],1,"Requisito expreso.",["Insuficiente.","","Condicional.","Hay condiciones."]),
    Q("Cláusula penal típica (Art. 1.535 CC):",["Ilegal","Multa estipulada por incumplimiento como indemnización previa","Sin efecto","Siempre nula"],1,"Válida con límites.",["Legal.","","Tiene.","Puede ser válida."]),
    Q("El monto de cláusula penal habitual en promesa:",["10%","Doble o triple de la seña · o monto específico pactado","100%","Sin límite"],1,"Práctica de mercado.",["Muy bajo.","","Excesivo.","Hay límites legales."]),
    Q("Si la cláusula penal es excesiva (Art. 1.544 CC):",["Válida siempre","Puede reducirse judicialmente por lesión enorme","Libre","Inmutable"],1,"Protección jurídica.",["Hay revisión.","","Hay límite.","Hay revisión."]),
    Q("Seña de reserva pre-promesa:",["Irrelevante","Pago simbólico reserva propiedad mientras se elabora la promesa",
      "Sin efecto","Ilegal"],1,"Práctica común.",["Tiene.","","Tiene.","Legal."]),
    Q("Si cae condición suspensiva, la seña:",["Se pierde","Se devuelve al comprador según lo pactado","Se multa","Irrelevante"],1,"Protección del comprador.",["No injusto.","","No multa.","Relevante."]),
    Q("Las arras se entregan:",["Solo al firmar escritura","Al firmar la promesa, como garantía del compromiso","Al final","Nunca"],1,"Momento típico.",["Tarde.","","Al inicio.","Existen."]),
    Q("Cláusula que prohíbe retracto bajo cualquier circunstancia:",["Libre","Puede ser revisada si es abusiva (Ley 19.496)","Válida siempre","Sin efecto"],1,"Protección consumidor.",["Hay revisión.","","Hay límite.","Tiene."]),
    Q("Un retracto justificado (condición suspensiva incumplida):",["Multa","Libera sin penalidad; sólo devolución de seña","Ejecución","Proceso"],1,"Régimen de condiciones.",["No.","","No.","Mecánico."]),
    Q("Un retracto injustificado sin arras penitenciales:",["Libre","Genera incumplimiento · ejecución cláusula penal o indemnización",
      "Sin consecuencia","Ilegal"],1,"Responsabilidad contractual.",["Hay.","","Hay.","No ilegal pero con costo."]),
    Q("Las arras se imputan al precio:",["Nunca","Si son confirmatorias, se imputan al precio total al firmar escritura",
      "Siempre retorno","Libre"],1,"Mecanismo estándar.",["Sí se imputa.","","No siempre retorno.","Hay regla."]),
    Q("Vendedor que se retracta con arras penitenciales:",["Queda libre","Debe restituir el doble de las arras al comprador","Sin costo","Multa mayor"],1,"Art. 1.803 CC.",["Tiene.","","Tiene costo.","Es la regla."]),
    Q("Comprador que se retracta con arras penitenciales:",["Sin costo","Pierde las arras","Multa extra","Sin efecto"],1,"Art. 1.803 CC.",["Tiene.","","No adicional.","Hay."]),
    Q("La multa convencional se puede pactar:",["Libremente sin límite","Sujeta a límites de Art. 1.544 CC (no excesiva vs obligación principal)",
      "Nula","Imposible"],1,"Control de razonabilidad.",["Hay límite.","","No nula.","Posible."]),
    Q("La cláusula penal indemniza:",["Otro concepto","Daños y perjuicios por incumplimiento · sustituye prueba detallada",
      "Gratuita","Ninguna indemnización"],1,"Función específica.",["Específica.","","No.","Sí."]),
    Q("Si la cláusula penal y daño real difieren:",["Reajustable","Generalmente se aplica cláusula; reducible si excesiva","Siempre real","Siempre cláusula"],1,"Flexibilidad judicial.",["Según ley.","","Depende.","Hay ajuste."]),
    Q("La cláusula 'ambos renuncian a retractarse':",["Válida","Depende · no siempre oponible; análisis caso a caso","Nula","Libre"],1,"Depende contexto.",["Análisis.","","No automático.","Hay control."]),
    Q("La cláusula 'vendedor paga todo':",["Legal","Puede considerarse abusiva y revisable","Ilegal","Normal"],1,"Equilibrio contractual.",["Revisable.","","No ilegal per se.","Cuestionable."]),
  ];
  const m5 = [
    Q("La escritura pública se otorga:",["Privada","Ante notario con presencia de partes o representantes","Digital","En comisaría"],1,"Acto solemne.",["No.","","No.","No."]),
    Q("El notario revisa:",["Precio","Minuta, identidades, capacidad, documentos, hipotecas, alzamientos","Solo firmas","Nada"],1,"Rol fedatario.",["Más.","","Más amplio.","Revisa."]),
    Q("La minuta es:",["Acta","Borrador de la escritura que se revisa antes de firmar","Foto","Anexo"],1,"Documento previo.",["No.","","No.","Otro."]),
    Q("El banco desembolsa al vendedor:",["Antes de firma","Tras inscripción efectiva en CBR, en cuenta vista","Directo","Nunca"],1,"Protección al banco y al comprador.",["Riesgo.","","Prohibido antilavado.","Se paga."]),
    Q("La hipoteca inscrita en CBR:",["Sin efecto","Perfecciona la garantía frente a terceros (Art. 2.410 CC)","Nula","Parcial"],1,"Principio publicidad.",["Tiene efecto.","","No nula.","Plena."]),
    Q("Si el CBR observa la escritura:",["Nulidad","Se subsana y reingresa; plazo corre desde reingreso","Pago","Fin"],1,"Mecanismo estándar.",["Subsanable.","","No pago.","Hay ruta."]),
    Q("Tracto sucesivo al comprar con hipoteca vendedor:",["Imposible","Se alza simultáneamente con nueva hipoteca en misma firma","Separado","Nula"],1,"Operación estándar.",["Posible.","","No separado.","No nula."]),
    Q("La escritura compraventa incluye típicamente:",["Solo nombre","Partes, precio, forma de pago, inmueble, deslindes, cláusulas accesorias","Solo monto","Nada"],1,"Contenido formal.",["Insuficiente.","","Incompleto.","Requerido."]),
    Q("Gastos notariales y de inscripción habitualmente:",["Banco paga","Comprador los asume, salvo pacto contrario","Vendedor","Fisco"],1,"Práctica estándar.",["Cliente.","","Habitual.","No."]),
    Q("Impuesto de timbres sobre crédito hipotecario:",["No aplica","0,8% máximo anual sobre monto financiado (DL 3.475) con exención parcial DS1",
      "10%","100%"],1,"Norma tributaria.",["Aplica.","","Fuera.","Absurdo."]),
    Q("Si el comprador no concurre a la escritura:",["Sin efecto","Incumplimiento grave; ejecución cláusula penal si existe","Nada","Válida"],1,"Responsabilidad contractual.",["Hay.","","Hay consecuencia.","Requiere firma."]),
    Q("Presencia del cónyuge no dueño al vender:",["Nunca","Requerida en régimen de sociedad conyugal; otorga autorización","Libre","Ilegal"],1,"Código Civil.",["Requerida.","","Régimen.","Legal requerirla."]),
    Q("Un menor de edad no puede:",["Contratar","Otorgar escritura compraventa sin representación legal","Nunca","Todo"],1,"Capacidad.",["Limitada.","","Excepción.","No todo."]),
    Q("Apoderado (mandatario) firma:",["Nunca","Con poder notarial vigente e idóneo para la operación","Libremente","Sin poder"],1,"Representación.",["Sí.","","Con poder.","No."]),
    Q("Fondos en cuenta vista del notario se liberan:",["Siempre","Una vez verificada la inscripción en CBR","Antes","Nunca"],1,"Protección.",["Hay condición.","","Riesgo.","Se libera."]),
    Q("La rapidez de la inscripción depende de:",["Voluntad","Comuna, carga del CBR y observaciones menores a subsanar","Aleatorio","Solo banco"],1,"Factores operativos.",["Factores.","","No aleatorio.","No solo."]),
    Q("Un error menor en escritura:",["Nulidad","Se corrige con escritura complementaria","Fin","Ignorar"],1,"Mecanismo notarial.",["No nulidad.","","Hay corrección.","No ignorar."]),
    Q("Una declaración falsa en escritura:",["Sin efecto","Genera responsabilidad penal y civil; vicio del consentimiento",
      "Libre","Válida"],1,"Gravedad.",["Hay efecto.","","Delito.","No válida."]),
    Q("El número de repertorio de la escritura:",["Irrelevante","Identificador único en notaría · útil para buscar copia",
      "Decorativo","Opcional"],1,"Control interno notarial.",["Relevante.","","Formal.","Obligatorio."]),
    Q("Copia autorizada de escritura se obtiene:",["Nunca","En la notaría donde se otorgó · cualquier parte o quien tenga interés",
      "CBR","SII"],1,"Acceso legal.",["Se obtiene.","","Notaría.","No."]),
  ];
  const m6 = [
    Q("Una caída de operación en primera vivienda ocurre en:",["0%","10-20% de los casos según sector","100%","50%"],1,"Estadística de mercado.",["Existe.","","Falso.","Fuera."]),
    Q("Si banco rechaza condición DS1:",["Fin","Apelar o probar otro banco adherido al DS1/DS116","Multa","Ignorar"],1,"Plan B.",["Hay ruta.","","No multa.","No ignorar."]),
    Q("Si tasación bancaria es baja:",["Rompe operación","Renegociar precio con vendedor o aumentar pie del comprador",
      "Banco paga diferencia","Nulo"],1,"Ajuste.",["Hay ruta.","","No cubre diferencia.","Hay ajuste."]),
    Q("Subsidio rechazado:",["Rechazar cliente","Apelar o plan B leasing + siguiente llamado",
      "Demandar","Nada"],1,"Resolución alternativa.",["Hay rutas.","","No procede.","Hay."]),
    Q("Alzamiento hipoteca vendedor atrasa:",["Fin","Coordinar con banco vendedor, ampliar plazo o pago parcial como garantía",
      "Nuevo banco","Multa"],1,"Gestión.",["Gestionable.","","No suele.","No multa."]),
    Q("Dicom que aparece tarde:",["Imposible solución","Pagar y pedir cierre, reingresar al banco actualizado","Multa","Ignorar"],1,"Gestión documental.",["Hay ruta.","","No multa.","No ignorar."]),
    Q("Vendedor se arrepiente:",["Libre","Activar cláusula penal / arras penitenciales; reasignar comprador",
      "Nada","Demandar sin estudio"],1,"Mecanismo contractual.",["Responde.","","Hay acción.","Primero cláusula."]),
    Q("Certificado CBR con observación menor:",["Inmutable","Abogado subsana; ampliar plazo promesa si necesario","Fin","Imposible"],1,"Subsanable.",["Subsanable.","","Flexibilidad.","Posible."]),
    Q("El corredor comunica contingencia al cliente:",["Día X","48 horas antes mínimo; proactividad construye confianza","Después","Nunca"],1,"Servicio profesional.",["Temprano.","","Tarde.","Mala."]),
    Q("Plan B al banco rechaza:",["Nada","Presentar el caso a los otros 2 bancos pre-aprobados",
      "Nuevo cliente","Nulo"],1,"Estrategia de 3 bancos.",["Hay.","","No abandonar cliente.","Hay."]),
    Q("Si la operación cae definitivamente:",["Pérdida total","Mantener relación · posible referido · reactivar en 3-6 meses",
      "Cortar","Culpar"],1,"Relación largo plazo.",["Hay valor.","","Malo.","Improductivo."]),
    Q("Multa por caída unilateral:",["Ilegal","Se ejecuta cláusula penal pactada en promesa · o vía indemnización",
      "Libre","Sin efecto"],1,"Contractual.",["Legal.","","No libre.","Tiene."]),
    Q("Pérdida de vigencia pre-aprobación:",["Sin efecto","Se requiere re-evaluación bancaria · puede bajar monto o subir tasa",
      "Automática","Acelera"],1,"Condición temporal.",["Tiene.","","No automática.","No acelera."]),
    Q("Subsidio que expira antes de escritura:",["Se extiende","Solicitar prórroga SERVIU con justificación antes del vencimiento",
      "Nada","Automático"],1,"Mecanismo administrativo.",["Hay solicitud.","","Hay acción.","No automático."]),
    Q("Si comprador cambia de empleo en vigencia pre-aprobación:",["Sin efecto","Informar al banco; re-evaluación puede ajustar condiciones",
      "Oculto","Multa"],1,"Transparencia.",["Hay.","","Incumplimiento.","No multa."]),
    Q("Si comprador se enferma gravemente:",["Caso fortuito","Posible causal de fuerza mayor; evaluar con abogado","Multa","Fin"],1,"Evaluación jurídica.",["Posible.","","No multa automática.","Hay análisis."]),
    Q("Problema de alzamiento hipoteca por deuda no pagada del vendedor:",["Fin","Retener del precio lo necesario para pagar directo al banco vendedor","Comprador paga","Juicio"],1,"Mecanismo estándar.",["Solución.","","No.","No primero."]),
    Q("Si aparece reivindicación durante proceso:",["Ignorar","Detener operación hasta resolver jurídicamente",
      "Continuar","Multa"],1,"Riesgo grave.",["Grave.","","Mala.","No multa."]),
    Q("La cláusula 'fuerza mayor' en promesa:",["Innecesaria","Protege ante eventos imprevisibles insuperables",
      "Sin efecto","Siempre nula"],1,"Instrumento preventivo.",["Útil.","","Tiene.","Legal."]),
    Q("Mantener relación con cliente post-caída:",["Irrelevante","Construye oportunidad futura y posibles referidos",
      "Dañino","Imposible"],1,"Largo plazo.",["Valor.","","Al contrario.","Posible."]),
  ];
  const m7 = [
    Q("La entrega material es:",["Jurídica","Acto operativo: llaves + inventario + estado + acta firmada",
      "Notarial solo","Nada"],1,"Acto físico formal.",["Es física.","","Notaría es anterior.","Requerida."]),
    Q("El acta de entrega incluye:",["Nombre","Fecha, partes, inventario, estado, lecturas servicios, observaciones, firmas",
      "Solo foto","Nada"],1,"Documento completo.",["Insuficiente.","","Insuficiente.","Requerido."]),
    Q("Lecturas de servicios al entregar:",["Irrelevantes","Medidor luz, agua, gas · base para cuentas futuras",
      "Solo luz","No"],1,"Protege comprador.",["Crítico.","","Todos.","Es funcional."]),
    Q("Gastos comunes al día:",["Asumir","Certificado actualizado del administrador al momento de entrega",
      "Ignorar","Banco paga"],1,"Protección.",["Requerido.","","No.","No."]),
    Q("Contribuciones según periodo:",["Comprador paga todo","Vendedor paga su porción del año; comprador desde su periodo",
      "Banco","Ninguno"],1,"Proporcionalidad.",["Proporcional.","","No.","Alguien."]),
    Q("Llaves originales, copias y especiales:",["Solo una","Entregar todas las existentes · requisito del acta",
      "Solo principal","Ninguna"],1,"Completitud.",["Todas.","","Todas.","Todas."]),
    Q("Controles (alarma, portón, TV):",["Irrelevante","Entregar con instrucciones · listar en acta",
      "Solo alarma","Ninguno"],1,"Funcionalidad.",["Requerido.","","Todos.","Todos."]),
    Q("Propiedad nueva: manual del hogar:",["Irrelevante","Entregar: planos, garantías, instrucciones, proveedores",
      "Solo planos","Ninguno"],1,"Estándar.",["Requerido.","","Completo.","Completo."]),
    Q("Fotos del estado al entregar:",["Evitar","Fundamentales para evidenciar vicios aparentes o mejoras",
      "Ilegales","Irrelevantes"],1,"Evidencia.",["Esenciales.","","Legales.","Relevantes."]),
    Q("Detalle memorable post-entrega:",["Prohibido","Canasta, nota manuscrita, tarjeta · construye NPS y referidos",
      "Ilegal","Sin efecto"],1,"Experiencia memorable.",["Recomendado.","","Legal.","Efecto real."]),
    Q("Entrega con propiedad sucia:",["Normal","Observación en acta · vendedor debe regularizar o se descuenta",
      "Ignorar","Mejor"],1,"Estándar profesional.",["Cuidado.","","Se resuelve.","No."]),
    Q("Si encuentra vicio aparente al entregar:",["Ignora","Se anota en acta y se pacta plazo de reparación",
      "Fin","Cancela"],1,"Cláusula de reparación.",["Se anota.","","No se pierde.","Primero."]),
    Q("Sin acta de entrega firmada:",["Ok","Riesgo de disputa futura; siempre firmar","Mejor","Innecesaria"],1,"Protección.",["Problema.","","Al revés.","Esencial."]),
    Q("Fecha de entrega pactada en promesa:",["Irrelevante","Se cumple estrictamente · modificación por consenso escrito",
      "Libre","Nunca"],1,"Contractual.",["Relevante.","","No libre.","Existe."]),
    Q("Entrega retrasada por banco (inscripción CBR lenta):",["Multa","Ampliar plazo por fuerza mayor operativa de común acuerdo",
      "Fin","Incumplimiento vendedor"],1,"Flexibilidad.",["No multa.","","No fin.","No vendedor."]),
    Q("La propiedad debe entregarse con:",["Lo que sea","Lo pactado en promesa: muebles, artefactos, jardín, etc.",
      "Vacía","Llena"],1,"Según pacto.",["No.","","Depende.","Depende."]),
    Q("Si el vendedor deja deuda de gas:",["Comprador paga","Vendedor regulariza o se retiene del precio","Nadie","Automático"],1,"Protección.",["Injusto.","","Alguien.","No."]),
    Q("NPS del cliente post-entrega:",["Nunca","Encuesta 0-10 en días siguientes · base para referidos",
      "Solo rico","Irrelevante"],1,"Medición.",["Se hace.","","Todos.","Esencial."]),
    Q("Un cliente con NPS 10 es:",["Detractor","Promotor · prospecto ideal de referido","Neutro","Ningún dato"],1,"NPS.",["No.","","No.","Es dato."]),
    Q("La entrega exitosa termina con:",["Nada","Agradecimiento del corredor + solicitud formal de referidos tras el alivio final",
      "Solo firma","Marketing"],1,"Pico emocional.",["Hay más.","","Oportunidad.","No es marketing."]),
  ];
  return { 1:m1, 2:m2, 3:m3, 4:m4, 5:m5, 6:m6, 7:m7 };
}

function buildFinal(){
  const Q=(q,opts,c,wc,ww)=>({q,opts,correct:c,whyCorrect:wc,whyWrong:ww});
  return [
    Q("Principled negotiation (Fisher-Ury) se basa en:",["Imposición","Separar personas, centrar intereses, opciones, criterios","Manipulación","Azar"],1,"Estándar mundial.",["No.","","Antiético.","No."]),
    Q("BATNA es:",["Banco","Mejor alternativa si no hay acuerdo","Precio","Nada"],1,"Poder relativo.",["No.","","No.","Existe."]),
    Q("ZOPA es:",["Sin sentido","Intersección precios min vendedor / max comprador","Banco","Ley"],1,"Zona de acuerdo posible.",["Existe.","","No.","No."]),
    Q("Promesa se rige por:",["19.281","Art. 1.554 CC","18.010","CMF"],1,"Norma.",["Leasing.","","Créditos.","No."]),
    Q("Plazo entre promesa y escritura:",["1 día","30-60 días","5 años","1 hora"],1,"Operativo.",["Imposible.","","Fuera.","Imposible."]),
    Q("Arras confirmatorias (por defecto):",["Retracto","Parte anticipada del precio","Libres","Ilegales"],1,"Presunción legal.",["No.","","No.","Legales."]),
    Q("Arras penitenciales:",["Iguales","Retracto: comprador pierde · vendedor restituye doble","Prohibidas","Sin efecto"],1,"Art. 1.803 CC.",["Distintas.","","Válidas.","Tienen."]),
    Q("Cláusula penal típica:",["10%","Doble/triple de la seña o monto pactado","100%","Ilegal"],1,"Práctica.",["Bajo.","","Excesivo.","Legal."]),
    Q("Escritura se otorga:",["Privada","Ante notario","Digital","Comisaría"],1,"Solemne.",["No.","","No.","No."]),
    Q("Banco desembolsa al vendedor:",["Antes","Tras inscripción CBR","Directo","Nunca"],1,"Protección.",["Riesgo.","","Prohibido.","Se paga."]),
    Q("Gastos notariales:",["Banco","Comprador habitual","Vendedor","Fisco"],1,"Práctica.",["Cliente.","","Habitual.","No."]),
    Q("Caída de operación en primera vivienda:",["0%","10-20%","100%","50%"],1,"Estadística.",["Existe.","","Falso.","Fuera."]),
    Q("Si banco rechaza:",["Fin","Plan B a otros bancos pre-aprobados","Multa","Ignorar"],1,"Estrategia.",["Hay ruta.","","No multa.","No."]),
    Q("Tasación baja precio:",["Rompe","Renegociar o aumentar pie","Banco paga","Nulo"],1,"Ajuste.",["Hay ruta.","","No cubre.","Ajuste."]),
    Q("Vendedor arrepiente con arras penitenciales:",["Libre","Restituye doble de las arras","Sin costo","Multa extra"],1,"Art. 1.803.",["Tiene.","","Tiene.","Es regla."]),
    Q("Comprador arrepiente con arras penitenciales:",["Sin costo","Pierde las arras","Multa extra","Sin efecto"],1,"Art. 1.803.",["Tiene.","","No.","Hay."]),
    Q("Entrega material:",["Jurídica","Operativa: llaves + inventario + acta","Notarial sola","Nada"],1,"Acto formal.",["Física.","","Antes.","Requerida."]),
    Q("Acta de entrega:",["Foto","Fecha, partes, inventario, estado, firmas","Solo nombre","Nada"],1,"Documento.",["No.","","No.","Requerido."]),
    Q("Lecturas de servicios al entregar:",["Irrelevantes","Luz, agua, gas · base para cuentas","Solo luz","No"],1,"Protege.",["Crítico.","","Todos.","Funcional."]),
    Q("NPS promotor:",["Detractor","Cliente 9-10","Neutro","Nada"],1,"Promotor.",["No.","","No.","Dato."]),
    Q("Gastos comunes al día al entregar:",["Asumir","Certificado administrador","Ignorar","Banco"],1,"Protección.",["Requerido.","","No.","No."]),
    Q("Llaves, copias y controles:",["Solo una","Todos entregados con acta","Solo principal","Ninguna"],1,"Completo.",["Todas.","","Todos.","Todas."]),
    Q("Condición suspensiva 'pre-aprobación bancaria':",["Nunca","Banco emite carta pre-aprobación","Al solicitar","Depende"],1,"Hito objetivo.",["Hay.","","Insuficiente.","Objetivo."]),
    Q("Si condición suspensiva no se cumple:",["Cerrada","Promesa sin efecto si pactado","Multa","Ignorar"],1,"Régimen.",["Depende.","","No.","No."]),
    Q("Alzamiento hipoteca vendedor:",["Imposible","Simultáneo nueva hipoteca en firma","Separado","Nula"],1,"Estándar.",["Posible.","","No.","No nula."]),
    Q("Cláusula penal excesiva:",["Válida","Reducible por lesión enorme Art. 1.544 CC","Libre","Inmutable"],1,"Revisión.",["Hay.","","Hay.","Hay."]),
    Q("Firma del cónyuge en sociedad conyugal:",["Nunca","Requerida por CC","Libre","Ilegal"],1,"Régimen.",["Requerida.","","No libre.","Legal."]),
    Q("Menor sin representación:",["Puede","No puede sin representación legal","Nunca","Todo"],1,"Capacidad.",["Limitada.","","Excepción.","No."]),
    Q("Apoderado con poder:",["Nunca","Firma con poder notarial vigente e idóneo","Sin poder","Libremente"],1,"Representación.",["Sí.","","No.","Con poder."]),
    Q("Contraoferta:",["Acuerdo","Nueva oferta que requiere aceptación","Inmutable","Silencio"],1,"Nueva negociación.",["No.","","Hay.","Hay."]),
    Q("Seña habitual:",["0%","3-5% del precio","50%","100%"],1,"Estándar.",["Mala.","","Fuera.","Fuera."]),
    Q("Plazo respuesta oferta:",["10 min","48-72 hrs","Un mes","Sin plazo"],1,"Estándar.",["Corto.","","Fuera.","Necesario."]),
    Q("Método principled vs competitivo:",["Iguales","Principled es más sostenible para transacciones con referido futuro","Competitivo mejor","Ninguno"],1,"Largo plazo.",["Distintos.","","No.","Hay."]),
    Q("Interés detrás de la posición 'quiero 3.500':",["Nada","Razón subyacente (mudanza, retiro, emergencia) que permite crear valor",
      "Ego","Fantasía"],1,"Clave negociación.",["Hay.","","No solo.","Real."]),
    Q("Opciones creativas expanden:",["Nada","ZOPA · habilitan acuerdos cuando precio no cede","Sin efecto","Prohibidas"],1,"Herramienta.",["Herramienta.","","Tienen.","No."]),
    Q("Criterio objetivo para anclar:",["Capricho","Tasación, avalúo, comparables, índices oficiales","Ninguno","Color"],1,"Racional.",["No.","","Hay.","No."]),
    Q("Si la promesa carece de plazo o condición:",["Válida","Nula por no cumplir Art. 1.554 CC","Libre","Irrelevante"],1,"Requisito.",["Es nula.","","No libre.","Crítico."]),
    Q("Cesión de promesa:",["Nunca","Posible con pacto o consentimiento","Libre","Prohibida"],1,"Consenso.",["Posible.","","No libre.","No prohibida."]),
    Q("Retracto injustificado sin arras penitenciales:",["Libre","Cláusula penal o indemnización","Sin efecto","Ilegal"],1,"Responsabilidad.",["Tiene.","","Hay.","Costo."]),
    Q("Fondos retenidos por notario:",["Siempre libres","Se liberan tras inscripción CBR","Antes","Nunca"],1,"Protección.",["Condición.","","Riesgo.","Se libera."]),
    Q("Error menor en escritura:",["Nulidad","Escritura complementaria","Fin","Ignorar"],1,"Subsanable.",["No.","","Hay.","No."]),
    Q("Fuerza mayor en promesa:",["Innecesaria","Protege ante eventos imprevisibles insuperables","Sin efecto","Nula"],1,"Prevención.",["Útil.","","Tiene.","Legal."]),
    Q("Antes de firmar escritura, el corredor:",["Nada","Revisa minuta con partes, coordina banco, verifica alzamiento",
      "Solo espera","Delega"],1,"Rol activo.",["Activo.","","Más.","Acompaña."]),
    Q("Vendedor atraso entrega:",["Fin","Extender plazo de común acuerdo o activar cláusula penal",
      "Multa automática","Nulo"],1,"Flexibilidad.",["Hay opciones.","","No automática.","Depende."]),
    Q("Comprador cambia de empleo en vigencia pre-aprobación:",["Sin efecto","Informar al banco; re-evaluación","Oculto","Multa"],1,"Transparencia.",["Hay.","","Incumplimiento.","No."]),
    Q("Dicom aparece tarde:",["Imposible","Pagar + certificado cierre + reingresar","Multa","Ignorar"],1,"Gestión.",["Hay ruta.","","No.","No."]),
    Q("Detalle post-entrega (nota, canasta):",["Prohibido","Construye NPS y referidos a futuro","Ilegal","Sin efecto"],1,"Experiencia.",["Recomendado.","","Legal.","Real."]),
    Q("NPS mínimo para pedir referido:",["0","8","Cualquiera","5"],1,"Umbral.",["Sin.","","Sin.","Insuficiente."]),
    Q("Momento óptimo para pedir referido:",["Al firmar oferta","Después de entrega con alivio emocional del cliente","Nunca","En cualquier momento"],1,"Pico emocional.",["Prematuro.","","Ocasión.","Momentos específicos."]),
    Q("Contingencia por cambios tasa del banco:",["Ignorar","Verificar condiciones y negociar con ejecutivo + alternativas",
      "Aceptar","Abandonar"],1,"Gestión.",["Actuar.","","No siempre.","No."]),
  ];
}

function buildGold(){
  return [
    {n:1,title:"Separar personas del problema",text:"No llevas ego ni del cliente ni tuyo a la mesa. Foco en el asunto objetivo. Principled negotiation Fisher-Ury."},
    {n:2,title:"Intereses, no posiciones",text:"La posición es 'quiero X'. El interés es por qué. Descubrir el por qué abre opciones creativas que no tocan precio."},
    {n:3,title:"Conoce BATNA propio y ajeno",text:"BATNA alto = más poder. Si tu cliente tiene mejor alternativa real, negocias sin presión."},
    {n:4,title:"Oferta escrita y profesional",text:"Precio + plazo + condiciones + validez. Fundamentada en tasación + comparables. Nunca improvisada."},
    {n:5,title:"Promesa cumple Art. 1.554 CC",text:"Escrita, con plazo o condición, identificación específica, cosa lícita. Sin estos requisitos, nula."},
    {n:6,title:"Arras: confirmatorias o penitenciales",text:"Por defecto son confirmatorias. Para retracto debe pactarse expresamente. Léelas antes de firmar."},
    {n:7,title:"Anticipa contingencias 48 horas antes",text:"Banco, subsidio, alzamiento, Dicom, CBR. El corredor profesional avisa temprano, no el día de la firma."},
    {n:8,title:"Plan B siempre preparado",text:"3 bancos + leasing + subsidio + reasignar propiedad. Sin plan B, un rechazo tira la operación."},
    {n:9,title:"Entrega con acta + inventario",text:"Fecha, partes, estado, lecturas, firmas. Sin acta hay disputa futura. Con acta el comprador se siente protegido."},
    {n:10,title:"Detalle memorable post-entrega",text:"Nota manuscrita, canasta, tarjeta. Construye NPS y futuros referidos durante años. Bajo costo, alto retorno."},
  ];
}
