/* Taller 07 · Postventa, Fidelización y Sistema de Referidos · Banco v1 */
window.TALLER_CONFIG = {
  slug: 'postventa-fidelizacion',
  moduleNames: {
    1:'Postventa inmediata',2:'Garantías legales Ley 19.472',3:'Acompañamiento primer año',
    4:'NPS · Medir satisfacción',5:'Sistema de Referidos · Pirámide 100',
    6:'Reactivación Capa C',7:'Marca personal digital',
  },
  certTitle:'Postventa, Fidelización y Referidos', certSubtitle:'Taller Avanzado 07 · Academia TuMatch',
  quizBank: buildBank(), finalQuestions: buildFinal(), goldRules: buildGold(),
};
function buildBank(){
  const Q=(q,opts,c,wc,ww)=>({q,opts,correct:c,whyCorrect:wc,whyWrong:ww});
  const m1=[
    Q("La 'duda post-cierre' aparece:",["Nunca","48-72 horas tras firmar · fenómeno psicológico normal","5 años","Todos"],1,"Sesgo Kahneman.",["Existe.","","No.","No todos."]),
    Q("El mensaje de refuerzo post-firma es:",["Spam","Texto breve con data que confirma buena decisión","Ilegal","Prohibido"],1,"Calma ansiedad.",["No.","","Legal.","Recomendado."]),
    Q("El primer check-in WhatsApp se hace:",["Nunca","Día 5-7 post entrega","Año","10 años"],1,"Anticipar dudas.",["Se hace.","","Tardísimo.","Absurdo."]),
    Q("Canasta de bienvenida al entregar:",["Ilegal","Detalle memorable · eleva NPS","Prohibida","Fin"],1,"Experiencia.",["Legal.","","Legal.","No fin."]),
    Q("Nota manuscrita con el agradecimiento:",["Antiguo","Más memorable que un mail · recordada durante años","Absurdo","Inútil"],1,"Alto impacto.",["Vigente.","","Profesional.","Útil."]),
    Q("Encuesta NPS se envía:",["Nunca","A los 30 días post entrega","Al día siguiente","Año 5"],1,"Timing óptimo.",["Se envía.","","Precipitado.","Fuera."]),
    Q("La guía primer mes incluye:",["Solo mail","Contribuciones + seguros + servicios + comunidad","Solo fotos","Nada"],1,"Útil práctico.",["Insuficiente.","","No.","Requerido."]),
    Q("Llamada día 10-14:",["Nunca","Verificar instalación servicios y resolver fricciones tempranas","Mes","Año"],1,"Acompañamiento.",["Se hace.","","Tarde.","Tarde."]),
    Q("Invitación a café 30 días:",["Prohibida","Consolida vínculo humano post transacción","Ilegal","Innecesaria"],1,"Relación.",["Recomendada.","","Legal.","Valor real."]),
    Q("Primer mes es decisivo porque:",["Nada","Define NPS y disposición a referir","Solo facturación","Solo legal"],1,"Fase crítica.",["Crítico.","","Más.","Más."]),
    Q("Mensaje refuerzo con data:",["Invento","Usar tasación, comparables, validaciones objetivas","Solo emocional","Nada"],1,"Fundamento.",["Datos reales.","","Falta.","Hay."]),
    Q("Cliente detractor detectado temprano:",["Ignorar","Contactar de inmediato, escuchar y resolver",
      "Dejarlo","Demandar"],1,"Gestión fricción.",["Amplifica.","","Mal.","Absurdo."]),
    Q("Recordatorio fechas clave primer mes:",["Inútil","Contribuciones, gastos comunes, seguros, vencimientos importantes",
      "Solo luz","Nada"],1,"Servicio útil.",["Relevante.","","Incompleto.","Requerido."]),
    Q("Tarjeta con contactos del corredor:",["Obsoleta","Útil al entregar · recordatorio permanente","Ilegal","Prohibida"],1,"Posicionamiento.",["Vigente.","","Legal.","Legal."]),
    Q("Detalle memorable cuesta típicamente:",["Mucho","UF 1-3 · alto ROI por referidos generados","Miles","Nada"],1,"Inversión con retorno.",["Moderado.","","Excesivo.","Hay."]),
    Q("El corredor no disponible los primeros 30 días:",["Normal","Rompe la experiencia · evitar viajes largos sin backup",
      "Mejor","Sin efecto"],1,"Crítica la presencia.",["Malo.","","Al contrario.","Afecta."]),
    Q("Si el cliente detecta vicio leve primer mes:",["Ignorar","Acompañar reclamo formal a constructora / vendedor",
      "Fin","Multar"],1,"Rol del corredor.",["Acompañar.","","No fin.","No."]),
    Q("Documentación técnica entregada al cliente:",["Nada","Planos, manuales, garantías, proveedores recomendados","Solo llaves","Fotos"],1,"Paquete completo.",["Insuficiente.","","Insuficiente.","Incompleto."]),
    Q("Tip cultural importante en primer mes:",["Ninguno","Explicar régimen de copropiedad, gastos comunes, asamblea",
      "Solo precio","Nada"],1,"Adaptación.",["Hay.","","Incompleto.","Relevante."]),
    Q("Ritual de cierre de postventa día 30:",["Nada","NPS + testimonio (si alto) + agenda próxima interacción en día 90",
      "Solo firma","Fin"],1,"Sistema.",["Crítico.","","Insuficiente.","Sigue."]),
  ];
  const m2=[
    Q("La Ley 19.472 protege al:",["Vendedor","Comprador de vivienda nueva frente a vicios de construcción","Banco","Inmobiliaria"],1,"Finalidad.",["No.","","No.","No."]),
    Q("Garantía terminaciones:",["1 mes","3 años desde recepción municipal","10 años","1 día"],1,"Art 18 c.",["Fuera.","","Estructural.","Absurdo."]),
    Q("Garantía instalaciones:",["1 mes","5 años","1 año","10 años"],1,"Art 18 b.",["Fuera.","","Fuera.","Estructural."]),
    Q("Garantía estructural:",["1 año","10 años","3 años","Indefinida"],1,"Art 18 a.",["Fuera.","","Otros vicios.","Finita."]),
    Q("Responsable legal por garantía:",["Banco","Primera inmobiliaria constructora","Estado","Comprador"],1,"Ley 19.472.",["No.","","No.","No."]),
    Q("Procedimiento de reclamo:",["Verbal","Escrito con fecha a la constructora","Solo llamada","Nada"],1,"Prueba.",["Débil.","","Insuficiente.","Absurdo."]),
    Q("Instancias de mediación:",["Nada","CChC, SERNAC Construcción","Solo juzgado","Ninguna"],1,"Alternativas.",["Hay.","","No solo.","Hay."]),
    Q("Los compradores sucesivos:",["Sin acceso","Pueden ejercer acción si vicio se manifiesta dentro del plazo",
      "Nunca","Solo primer comprador"],1,"Protección reforzada.",["Pueden.","","Pueden.","No solo."]),
    Q("Vicios aparentes al entregar no cubiertos por Ley 19.472:",["Cubiertos","No son ocultos · debe reclamarse en acta entrega",
      "Redhibitorios","Irrelevantes"],1,"Diferencia.",["No.","","No.","Cruciales."]),
    Q("El corredor al entregar informa:",["Nada","Plazos de garantía Ley 19.472 y procedimiento","Solo precio","Mudanza"],1,"Servicio profesional.",["Obligación.","","Insuficiente.","No."]),
    Q("Mecanismo de reclamo CChC:",["Nada","Sistema de mediación sectorial para disputas con constructoras",
      "Solo juicio","Automático"],1,"Resolución alternativa.",["Hay.","","Mediación.","No automática."]),
    Q("Vicios que reaparecen tras reparación:",["Pierde","Re-reclamar; la garantía cubre vicios no una sola vez",
      "Sin solución","Absurdo"],1,"Cobertura real.",["No.","","Cubre.","No."]),
    Q("Sanción a constructora que no responde:",["Nada","Multa + ejecución + indemnización por daños","Irrelevante","Cero"],1,"Responsabilidad.",["Hay.","","Tiene.","Hay."]),
    Q("Garantía para vivienda usada (no nueva):",["Nada","Vicios redhibitorios Art. 1.858 CC con plazos menores",
      "Ley 19.472","Indefinida"],1,"Régimen Código Civil.",["Hay.","","Ley 19.472 nueva.","Finita."]),
    Q("Plazo vicio redhibitorio rescisión:",["1 mes","1 año desde entrega","10 años","Nunca"],1,"Art 1.866 CC.",["Fuera.","","Fuera.","Hay."]),
    Q("Plazo acción quanti minoris (rebaja):",["1 día","6 meses","10 años","Nunca"],1,"Art 1.866.",["Fuera.","","Fuera.","Hay."]),
    Q("Fotos al entregar son:",["Inútiles","Evidencia clave para reclamos vicios aparentes",
      "Ilegales","Prohibidas"],1,"Prueba.",["Esenciales.","","Legales.","Legales."]),
    Q("Acta de entrega firmada:",["Inútil","Protege a comprador y delimita responsabilidad","Opcional","Sin efecto"],1,"Documento.",["Útil.","","Esencial.","Tiene."]),
    Q("La Ley 19.472 se considera:",["Obsoleta","Vigente y de orden público · no se puede renunciar",
      "Opcional","Privada"],1,"Imperativa.",["Vigente.","","Imperativa.","Pública."]),
    Q("Reclamo prescripción:",["Nunca","Si se pasa el plazo, prescribe la acción",
      "Indefinida","Eterna"],1,"Plazos ley.",["Hay.","","Finitos.","Prescribe."]),
  ];
  const m3=[
    Q("El plan 30-90-180-365:",["Inútil","Sistema de contactos programados primer año","Solo 30 días","Nada"],1,"Estructura.",["Útil.","","Más.","Hay."]),
    Q("Día 30 ideal para:",["Nada","NPS + tips primer mes","Solo firmar","10 años"],1,"Crítico.",["Hay.","","Tarde.","Absurdo."]),
    Q("Día 90 ideal para:",["Ignorar","Testimonio + primer pedido formal de referido","Facturar","Demandar"],1,"Cliente instalado.",["Mal.","","No.","No."]),
    Q("Día 180 contenido:",["Nada","Actualización mercado + valor estimado actual propiedad","Solo llamada","10 años"],1,"Autoridad.",["Hay.","","Mejor con contenido.","Absurdo."]),
    Q("Aniversario 1 año:",["Fin","Mensaje + invitación café + segunda solicitud referidos","Solo facturar","Nada"],1,"Momento pico.",["Inicio.","","Insuficiente.","Requerido."]),
    Q("Aniversario 2+:",["Ignorar","Ciclo cultivo relacional 21 días (Capa A)","Solo final","Nada"],1,"Largo plazo.",["Sigue.","","Sigue.","Activo."]),
    Q("El cliente instalado 90 días:",["Detractor","Promotor típico si postventa fue buena · momento ideal para testimonio",
      "Pasivo","Indiferente"],1,"Oportunidad.",["Suele.","","Puede mejorar.","Depende."]),
    Q("Si a los 90 días hay problema abierto:",["Pedir referido","Resolver primero · nunca pedir referido con fricción abierta","Ignorar","Abandonar"],1,"Ética.",["Mala.","","No.","No."]),
    Q("Un cliente contento a los 6 meses:",["Fin","Enviar newsletter + casos · mantener cultivo",
      "Solo facturar","Nada"],1,"Continuidad.",["Continúa.","","Más.","Requerido."]),
    Q("Valor estimado actual propiedad a los 6 meses:",["Inútil","Refuerza buena decisión y construye autoridad","Imposible","Secreto"],1,"Refuerzo.",["Útil.","","Posible.","Público."]),
    Q("Mensaje aniversario 1 año:",["Frío","Cálido, con cumpleaños de la nueva casa · celebra el hito",
      "Solo firma","Nada"],1,"Humano.",["Cálido.","","Insuficiente.","Pobre."]),
    Q("Segunda solicitud referidos:",["Nunca","Al año, con argumento de haber cumplido expectativas",
      "Al día 1","Mensual"],1,"Cadencia.",["Bien cadenciado.","","Prematuro.","Sat."]),
    Q("Cliente que cumple 1 año sin contacto:",["Perdido","Reactivar activamente con plan específico","Fin","Ignorar"],1,"Recuperable.",["Aún no.","","Hay ruta.","Mal."]),
    Q("Ritual aniversario mejora NPS:",["No","Sí, demostrado · intención consolidada","Sin efecto","Automático"],1,"Demostrado.",["Hay efecto.","","Hay.","Con ritual."]),
    Q("Acompañamiento primer año cuesta:",["Mucho","Tiempo moderado vs ROI de referidos vitalicios","Nada","Millones"],1,"ROI.",["Modesto.","","Cuesta tiempo.","Exagerado."]),
    Q("Corredor sin plan postventa:",["Elite","Pierde 70% de operaciones que podrían originarse","Igual","Mejor"],1,"Costo oportunidad.",["No.","","Pierde.","Peor."]),
    Q("Aniversario 2+ se reactiva:",["Solo","Integrar a Capa A del Círculo con ciclo 21 días","Ignorar","Fin"],1,"Largo plazo.",["Activamente.","","Integración.","Sigue."]),
    Q("Cliente con problema legal en garantía:",["Fin","Acompañar en reclamo a constructora / instancias mediación",
      "No ayudar","Solo cobrar"],1,"Servicio extendido.",["Hay.","","Mal.","No."]),
    Q("Cambio vital del cliente (hijos, trabajo):",["Nada","Oportunidad de volver a asesorar (ampliar, mudar, invertir)",
      "Cortar","Ignorar"],1,"Actualización.",["Hay.","","Mal.","No."]),
    Q("Plan 30-90-180-365 se cumple:",["Memoria","Recordatorios automáticos CRM · disciplina profesional",
      "Al azar","Nunca"],1,"Sistematizado.",["Mala.","","Mal.","Hay."]),
  ];
  const m4=[
    Q("NPS fue creado por:",["Google","Reichheld (2003) · Bain & Harvard Business Review","Microsoft","Nadie"],1,"Origen.",["No.","","No.","No."]),
    Q("Pregunta NPS estándar:",["Calidad","Del 0 al 10, ¿cuán probable es que me recomiende?","Precio","Ninguna"],1,"Pregunta icónica.",["Otra.","","No.","Hay."]),
    Q("Promotor:",["0-6","9-10","7-8","Nada"],1,"Clasificación.",["Detractor.","","Pasivo.","Hay."]),
    Q("Detractor:",["9-10","0-6","7-8","Nada"],1,"Clasificación.",["Promotor.","","Pasivo.","Hay."]),
    Q("Pasivo:",["0-6","7-8","9-10","Nada"],1,"Clasificación.",["Detractor.","","Promotor.","Hay."]),
    Q("NPS final =",["Nada","%Promotores − %Detractores","Suma","Promedio"],1,"Fórmula.",["Hay.","","Incorrecto.","Distinto."]),
    Q("NPS corredor top:",["0","≥ 8","≤ 3","50"],1,"Estándar TuMatch.",["Malo.","","Malo.","Alto pero menos preciso."]),
    Q("Umbral para pedir referidos:",["0","NPS ≥ 8","Cualquier","1"],1,"Legitimidad.",["Sin.","","Sin.","Insuficiente."]),
    Q("Encuesta NPS idealmente:",["Larga","3 preguntas (NPS + valoración + mejora)","20 preguntas","Ninguna"],1,"Breve = más respuestas.",["Baja.","","Baja.","Hay."]),
    Q("NPS vs CSAT:",["Iguales","NPS predice referencia; CSAT mide interacción específica","NPS peor","Solo uno"],1,"Diferencias.",["Distintos.","","Complementarios.","Ambos útiles."]),
    Q("Responder a detractor:",["Ignorar","En menos de 24 horas para resolver fricción","Semana","Nada"],1,"Gestión crítica.",["Empeora.","","Tarde.","Negligencia."]),
    Q("Promotor responder:",["Nada","Agradecer + invitar a referir + pedir testimonio",
      "Descuento","Solo cobrar"],1,"Sistema.",["Oportunidad.","","No es canje.","Mal."]),
    Q("NPS cambia con el tiempo:",["Fijo","Se re-mide; trayectoria importa","Nunca","Imposible"],1,"Dinámico.",["Cambia.","","Se remide.","Fácil."]),
    Q("Detractor público (redes):",["Ignorar","Responder con empatía profesional · daño reputacional si se deja sin respuesta",
      "Borrar","Demandar"],1,"Gestión online.",["Peor.","","Mal.","Exceso."]),
    Q("Incentivos NPS al cliente:",["Gratis","Pequeños detalles por responder · no sesgar con grandes premios","Grandes","Ninguno"],1,"Ética metodológica.",["Con cuidado.","","Sesga.","Menos respuestas."]),
    Q("NPS = 0 significa:",["Malo absoluto","Promotores = Detractores · punto de equilibrio","Falla","Desastre"],1,"Matemática.",["No.","","No.","Punto base."]),
    Q("NPS = 50:",["Malo","Excelente (corredor top)","Malo","Falso"],1,"Alto.",["Bueno.","","Bueno.","Real."]),
    Q("Mejora NPS con:",["Nada","Reducir fricción detectada en respuestas · iterar servicio",
      "Solo marketing","Precios bajos"],1,"Mejora continua.",["Mejora.","","Incompleto.","Irrelevante."]),
    Q("Medición NPS en corredores:",["Inútil","Diferenciador profesional y base de Sistema de Referidos","Opcional","Obsoleta"],1,"Clave.",["Útil.","","Recomendado.","Vigente."]),
    Q("Comunicar NPS al equipo TuMatch:",["Nada","Benchmarking interno · elevar estándar colectivo",
      "Confidencial","Ignorar"],1,"Learning.",["Útil.","","No necesariamente.","Mal."]),
  ];
  const m5=[
    Q("El Círculo de Influencia del corredor top genera:",["10%","60-80% de operaciones de carrera","0%","Todo"],1,"Regla Pareto.",["Subestima.","","Absurdo.","Improbable."]),
    Q("Pirámide de los 100 se divide en:",["Al azar","Capa A 20 + Capa B 50 + Capa C 30","Solo 100","Solo A"],1,"Estructura.",["Estructurada.","","Con segmentación.","Más."]),
    Q("Capa A son:",["Desconocidos","Top 20 red primaria (familia, clientes recientes, aliados)","50 tibios","30 dormidos"],1,"Alta prioridad.",["No.","","B.","C."]),
    Q("Capa B son:",["Desconocidos","50 medios · cultivo relacional 21 días","20 primarios","Nada"],1,"Tibios.",["No.","","A.","Hay."]),
    Q("Capa C son:",["Primarios","30 dormidos (sin interacción +12 meses) · reactivación",
      "Medios","Nadie"],1,"Reactivación.",["No.","","B.","Hay."]),
    Q("Solicitud formal referidos debe ser:",["Vaga","Acotada ('1 o 2 personas') y segmentada ('en tu trabajo')","Genérica","Cualquiera"],1,"Mejor recuerdo.",["Mala.","","Mala.","Vaga."]),
    Q("Script recomendado:",["Informal","'¿Se te ocurren 1 o 2 personas en una situación similar a la tuya?'","Directo","Agresivo"],1,"Profesional.",["Informal.","","Brusco.","Repelente."]),
    Q("Timing pedido referido:",["Al inicio","Tras hito de valor entregado (firma, entrega, aniversario)","Sin momento","Mensual"],1,"Reciprocidad.",["Prematuro.","","Improductivo.","Sat."]),
    Q("Tras recibir referido, agradecer en:",["Meses","Menos de 48 horas · nota o llamada","Años","Nunca"],1,"Reciprocidad.",["Tarde.","","Absurdo.","Daña."]),
    Q("Reporte al referidor:",["Secreto","Con autorización del referido · mantiene compromiso",
      "Ilegal","Innecesario"],1,"Con consentimiento.",["Cuidado.","","Legal con permiso.","Valorado."]),
    Q("Pagar por referido:",["Normal","Puede ser problemático ético y regulatorio; reciprocidad mejor en servicios",
      "Único","Obligatorio"],1,"Con cuidado.",["Con cuidado.","","No único.","No obligatorio."]),
    Q("KPI solicitudes referido TuMatch:",["0","≥ 4 mensuales","100 mensuales","No KPI"],1,"Disciplina.",["Malo.","","Absurdo.","Crítico."]),
    Q("KPI referidos recibidos:",["0","≥ 2 mensuales","100","Ninguno"],1,"Éxito ~50% solicitudes.",["Malo.","","Absurdo.","Hay."]),
    Q("Capa A contactos mensuales:",["0","≥ 8 (40% de los 20)","Todos","Uno"],1,"Equilibrio.",["Malo.","","Saturación.","Insuficiente."]),
    Q("Capa B ciclo:",["Nunca","21 días con contenido 80% formativo / 20% comercial",
      "Mensual","Anual"],1,"Validado.",["Se pierde.","","Muy poco.","Muy poco."]),
    Q("Reactivación Capa C mensual:",["0","≥ 5 contactos","50","100"],1,"Recuperación paulatina.",["Se pierde.","","Excesivo.","Excesivo."]),
    Q("Conversión red caliente:",["1%","≥ 30%","100%","Cualquier"],1,"Estándar.",["Malo.","","Imposible.","Vago."]),
    Q("NPS umbral pedir referidos:",["0","≥ 8","≤ 5","Cualquiera"],1,"Legitimidad.",["No.","","No.","Sin umbral."]),
    Q("Error común referidos:",["Nada","Pedir sin haber dado valor · romper reciprocidad",
      "Organizar","Agradecer"],1,"Error común.",["Hay.","","Organizar es bueno.","Es correcto."]),
    Q("Sistema referidos es:",["Azar","Método replicable con KPI · no eventos fortuitos","Suerte","Milagro"],1,"Metodológico.",["No.","","No.","No."]),
  ];
  const m6=[
    Q("Capa C definición:",["Nuevos","Contactos sin interacción +12 meses","Actuales","Enemigos"],1,"Dormidos.",["No.","","No.","Mal."]),
    Q("Tasa respuesta masiva vs personalizada:",["Iguales","3% vs 25% (personalizada es 8x mejor)","Inversa","Nula"],1,"Validado.",["Distintas.","","No.","Hay."]),
    Q("Mensaje reactivación debe tener:",["Nada","Motivo concreto y verificable + propuesta valor",
      "Solo venta","Automatización"],1,"Personalización.",["Hay.","","Mal.","Daña."]),
    Q("Eventos vitales que gatillan reactivación:",["Ninguno","Matrimonio, hijos, promoción, mudanza","Solo muerte","Al azar"],1,"Cambios reales.",["Hay.","","No solo.","Estructurado."]),
    Q("Cambio macroeconómico relevante:",["Ninguno","Nuevo subsidio, cambios de tasa, cambio normativo","Solo clima","Nada"],1,"Relevante.",["Hay.","","No clima.","Sí."]),
    Q("Mensaje agresivo en reactivación:",["Óptimo","Falla · contraproducente","Único","Recomendado"],1,"Tono cálido.",["Mal.","","No.","Mal."]),
    Q("Frecuencia reactivación Capa C:",["Diaria","Mensual con 5 contactos distintos · recorrer capa anualmente",
      "Por año total","Una vez"],1,"Sistemático.",["Saturación.","","Excesivo.","Insuficiente."]),
    Q("Primer mensaje reactivación:",["Propuesta comercial","Personal con motivo · sin exigencia inmediata",
      "Masivo","Sin contenido"],1,"Reciprocidad.",["Daña.","","Mal.","Mal."]),
    Q("Si no responde primer mensaje:",["Spam","Segundo intento en 30-45 días con nuevo motivo · luego descansar",
      "Bloquear","Fin"],1,"Insistencia proporcional.",["Mal.","","Excesivo.","Hay ruta."]),
    Q("Reactivación por WhatsApp:",["Prohibido","Válido si hay relación previa · respeta privacidad",
      "Único","Nunca"],1,"Canal válido.",["Legal.","","Uno más.","Hay."]),
    Q("Cliente reactivado en +6 meses relación:",["Sigue detractor","Puede pasar a Capa B con ciclo relacional",
      "Siempre frío","Inútil"],1,"Mejora.",["Mejora.","","No.","Hay valor."]),
    Q("Pretexto válido reactivación:",["Cualquiera","Contexto: zona del cliente, consulta pasada, noticia relevante",
      "Invento","Mentira"],1,"Contexto real.",["Mala.","","Fraude.","Fraude."]),
    Q("Reactivación masiva en redes:",["Óptima","Pierde efectividad · personalizada siempre mejor",
      "Única","Ilegal"],1,"Pareto.",["Peor.","","Hay otras.","Legal."]),
    Q("El objetivo de reactivación es:",["Venta inmediata","Restablecer relación · no forzar transacción",
      "Ignorar","Romper"],1,"Relacional.",["Prematuro.","","Mal.","Mal."]),
    Q("Capa C reactivada exitosamente:",["Pérdida","Sube a Capa B · ciclo 21 días + eventualmente A","Nunca","Se mantiene"],1,"Progresión.",["Oportunidad.","","Sí sube.","Puede subir."]),
    Q("Tiempo invertido reactivación:",["Mucho","Moderado · alto ROI si se sistematiza","Eterno","Cero"],1,"ROI.",["Manejable.","","Finito.","Hay inversión."]),
    Q("Error en reactivación:",["Personalizar","Envíos masivos sin contexto · daña percepción","Preguntar","Valor"],1,"Error común.",["Bien.","","Sí.","Bien.","Bien."]),
    Q("Capa C ignorada permanentemente:",["Sin problema","Pérdida de oportunidades latentes sustanciales",
      "Mejor","Automático"],1,"Oportunidad perdida.",["Problema.","","Mal.","No."]),
    Q("Reactivación profesional distingue al corredor de:",["Igual","Vendedores transaccionales · construye relación larga",
      "Ejecutivos","Clientes"],1,"Diferenciación.",["Distingue.","","No.","No."]),
    Q("Capa C nunca contactada pierde:",["Nada","~25% de oportunidades latentes medidas","Todo","Irrelevante"],1,"Cifra conservadora.",["Hay.","","Exagerado.","Relevante."]),
  ];
  const m7=[
    Q("Marca personal del corredor en 2026:",["Irrelevante","Clave para diferenciación profesional digital","Secundaria","Prohibida"],1,"Contexto.",["Crítica.","","Primaria.","Legal."]),
    Q("Regla 80/20 contenido:",["100% comercial","80% formativo / 20% comercial","Todo","Ninguno"],1,"Validado.",["Invasivo.","","No.","Hay."]),
    Q("LinkedIn del corredor se usa para:",["Jokes","Contenido técnico (hipotecaria, subsidios, mercado) B2B","Fotos","Ninguna"],1,"Autoridad técnica.",["No.","","Sí pero con más.","Hay uso."]),
    Q("Instagram del corredor:",["Solo personal","Propiedades curadas + testimonios + tips + stories diarios","Prohibido","Privado"],1,"Canal propio.",["Mezcla.","","Legal.","Abierto."]),
    Q("Frecuencia mínima LinkedIn:",["Nunca","1 post semanal mínimo","Diario","Mensual"],1,"Consistencia.",["Peor.","","Excesivo.","Muy poco."]),
    Q("Reels Instagram barrio:",["Inútil","Alta viralidad + autoridad territorial",
      "Obsoleto","Ilegal"],1,"Herramienta.",["Efectivo.","","Vigente.","Legal."]),
    Q("Contenido exclusivamente de propiedades:",["Ideal","Volantero digital · baja autoridad","Top","Único"],1,"Evitarlo.",["Mal.","","Peor.","No."]),
    Q("Casos de estudio con autorización:",["Riesgo","Alto valor · autenticidad + aprendizaje","Ilegales","Sin efecto"],1,"Con permiso.",["Legal.","","Legal.","Efecto real."]),
    Q("Newsletter corredor:",["Spam","Segmentado por Capa · contenido 80/20","Masivo","Ilegal"],1,"Canal directo.",["Con cuidado.","","No masivo.","Legal."]),
    Q("Contenido sobre tasas BCCh:",["Inútil","Referencia oficial + interpretación aplicada al cliente",
      "Copia","Prohibido"],1,"Valor añadido.",["Útil.","","Análisis propio.","Legal."]),
    Q("Entrevistas a proveedores del ecosistema:",["Irrelevantes","Alto valor de autoridad + red profesional",
      "Prohibidas","Egos"],1,"Estrategia.",["Valor.","","Legal.","Profesional."]),
    Q("Contenido sobre errores del comprador:",["Evitar","Alto valor educativo · construye autoridad","Ilegal","Sin valor"],1,"Útil.",["Útil.","","Legal.","Hay valor."]),
    Q("Herramientas TuMatch en contenido:",["Evitarlas","Demos auténticas en posts · valor práctico",
      "Prohibidas","Obsoletas"],1,"Autenticidad.",["Útiles.","","Promoción legítima.","Vigentes."]),
    Q("Respuestas oportunas a comentarios:",["Ignorar","En menos de 24 horas · construye comunidad",
      "Meses","Automatizadas"],1,"Interacción real.",["Mala.","","Tarde.","Frías."]),
    Q("Consistencia temporal del contenido:",["Irregular","Calendario + planificación semanal",
      "Inconexo","Aleatorio"],1,"Marca requiere.",["Peor.","","Peor.","Peor."]),
    Q("Marca personal vs marca corporativa:",["Excluyentes","Complementarias: corredor + TuMatch Inmobiliario se potencian",
      "Opuestas","Iguales"],1,"Sinergia.",["Suman.","","Pueden sumar.","No."]),
    Q("Reportes de impacto del contenido:",["Nulo","Métricas (alcance, engagement, conversión a leads) guían iteración",
      "Solo likes","Desconocido"],1,"Data-driven.",["Hay.","","Parcial.","Medible."]),
    Q("LinkedIn Live / podcast:",["Obsoleto","Formato alto valor · conversaciones profesionales profundas","Prohibido","Sin efecto"],1,"Tendencia.",["Vigente.","","Legal.","Alto efecto."]),
    Q("Uso ChatGPT u otros AI en contenido:",["Evitarlos","Útiles si se verifican y aportan valor real, no copypaste",
      "Prohibidos","Único"],1,"Con criterio.",["Pueden ayudar.","","Legales.","No único."]),
    Q("Marca personal sin foto:",["Ideal","Inusual · transparencia personal clave en corretaje",
      "Prohibida","Fin"],1,"Humanización.",["Peor.","","Legal.","Hay opciones."]),
  ];
  return {1:m1,2:m2,3:m3,4:m4,5:m5,6:m6,7:m7};
}
function buildFinal(){
  const Q=(q,opts,c,wc,ww)=>({q,opts,correct:c,whyCorrect:wc,whyWrong:ww});
  return [
    Q("La 'duda post-cierre' aparece:",["Nunca","48-72 horas tras firmar","5 años","Todos"],1,"Sesgo psicológico.",["Existe.","","No.","No todos."]),
    Q("Ley 19.472 garantía estructural:",["1 año","10 años","3 años","Indefinida"],1,"Art 18 a.",["Fuera.","","Otros vicios.","Finita."]),
    Q("Garantía instalaciones:",["1 mes","5 años","1 año","10 años"],1,"Art 18 b.",["Fuera.","","Fuera.","Estructural."]),
    Q("Garantía terminaciones:",["1 mes","3 años","10 años","1 día"],1,"Art 18 c.",["Fuera.","","Estructural.","Imposible."]),
    Q("NPS fue creado por:",["Google","Reichheld (2003)","Microsoft","Nadie"],1,"Origen.",["No.","","No.","No."]),
    Q("Promotor:",["0-6","9-10","7-8","Nada"],1,"Clasificación.",["Detractor.","","Pasivo.","Hay."]),
    Q("Detractor:",["9-10","0-6","7-8","Nada"],1,"Clasificación.",["Promotor.","","Pasivo.","Hay."]),
    Q("NPS =",["Suma","%Promotores − %Detractores","Promedio","Nada"],1,"Fórmula.",["Mal.","","Distinto.","Hay."]),
    Q("Umbral pedir referidos:",["0","NPS ≥ 8","Cualquier","1"],1,"Legitimidad.",["Sin.","","Sin.","Insuficiente."]),
    Q("Red caliente genera:",["10%","60-80% operaciones carrera","0%","Todo"],1,"Pareto.",["Bajo.","","Absurdo.","Improbable."]),
    Q("Pirámide 100:",["Al azar","Capa A 20 + B 50 + C 30","Solo 100","Solo A"],1,"Estructura.",["Estructurada.","","Segmentada.","Más."]),
    Q("Capa A:",["Desconocidos","Top 20 primarios","50 tibios","30 dormidos"],1,"Alta prioridad.",["No.","","B.","C."]),
    Q("Capa B:",["Desconocidos","50 medios (cultivo 21 días)","20 primarios","Nada"],1,"Tibios.",["No.","","A.","Hay."]),
    Q("Capa C:",["Primarios","30 dormidos (reactivar)","Medios","Nadie"],1,"Reactivación.",["No.","","B.","Hay."]),
    Q("Script solicitud referidos:",["Genérico","'1 o 2 personas en situación similar'",
      "Agresivo","Informal"],1,"Acotado.",["Mala.","","Brusco.","Informal."]),
    Q("Timing pedir referido:",["Inicio","Post hito de valor entregado","Sin momento","Mensual"],1,"Reciprocidad.",["Prematuro.","","Improductivo.","Sat."]),
    Q("Agradecimiento post referido:",["Meses","Menos 48h","Años","Nunca"],1,"Reciprocidad.",["Tarde.","","Absurdo.","Daña."]),
    Q("KPI solicitudes referidos:",["0","≥ 4/mes","100","No KPI"],1,"Disciplina.",["Malo.","","Absurdo.","Crítico."]),
    Q("Capa A contactos/mes:",["0","≥ 8 (40%)","Todos","Uno"],1,"Equilibrio.",["Malo.","","Saturación.","Insuficiente."]),
    Q("Ciclo Capa B:",["Nunca","21 días","Mensual","Anual"],1,"Validado.",["Se pierde.","","Pobre.","Pobre."]),
    Q("Reactivación Capa C/mes:",["0","≥ 5","50","100"],1,"Paulatina.",["Se pierde.","","Excesivo.","Excesivo."]),
    Q("Tasa reactivación personalizada:",["3%","25%","100%","Ninguna"],1,"8x mejor.",["Masiva.","","Imposible.","Hay."]),
    Q("Eventos vitales reactivación:",["Ninguno","Matrimonio, hijo, promoción, mudanza","Solo muerte","Azar"],1,"Gatillos.",["Hay.","","No solo.","Estructurado."]),
    Q("Mensaje reactivación:",["Sin contenido","Motivo concreto + propuesta valor","Solo venta","Masivo"],1,"Personalización.",["Hay.","","Daña.","Mal."]),
    Q("Regla 80/20 contenido:",["Todo comercial","80% formativo / 20% comercial","Ninguno","Todo"],1,"Validado.",["Mal.","","Peor.","Mal."]),
    Q("Frecuencia LinkedIn:",["Nunca","1 post semanal mínimo","Diario","Mensual"],1,"Consistencia.",["Peor.","","Excesivo.","Poco."]),
    Q("Plan 30-90-180-365:",["Inútil","Sistema contactos primer año","Solo 30","Nada"],1,"Estructura.",["Útil.","","Más.","Hay."]),
    Q("Día 30:",["Nada","NPS + tips","Facturar","10 años"],1,"Crítico.",["Hay.","","Tarde.","Absurdo."]),
    Q("Día 90:",["Ignorar","Testimonio + pedido referido","Facturar","Demandar"],1,"Instalado.",["Mal.","","No.","No."]),
    Q("Día 365:",["Fin","Aniversario + café + 2º pedido referidos","Solo facturar","Nada"],1,"Pico.",["Inicio.","","Pobre.","Requerido."]),
    Q("Vicio redhibitorio acción rescisión:",["1 mes","1 año","5 años","Nunca"],1,"Art 1.866 CC.",["Fuera.","","Fuera.","Hay."]),
    Q("Vicio redhibitorio acción quanti minoris:",["1 día","6 meses","10 años","Nunca"],1,"Art 1.866.",["Fuera.","","Fuera.","Hay."]),
    Q("Responsable Ley 19.472:",["Banco","Inmobiliaria constructora","Estado","Comprador"],1,"Responsable.",["No.","","No.","No."]),
    Q("Procedimiento reclamo:",["Verbal","Escrito con fecha a la constructora","Llamada","Nada"],1,"Prueba.",["Débil.","","Insuficiente.","No."]),
    Q("Mediación reclamos:",["Nada","CChC, SERNAC Construcción","Solo juzgado","Ninguna"],1,"Alternativa.",["Hay.","","No solo.","Hay."]),
    Q("Canasta bienvenida:",["Ilegal","Detalle memorable · ROI alto","Prohibida","Sin efecto"],1,"Experiencia.",["Legal.","","Legal.","Real."]),
    Q("Nota manuscrita:",["Obsoleto","Más memorable que mail","Inútil","Absurdo"],1,"Impacto.",["Vigente.","","Útil.","Profesional."]),
    Q("Encuesta NPS:",["Nunca","A los 30 días","Mañana","5 años"],1,"Timing.",["Se envía.","","Prematuro.","Fuera."]),
    Q("Corredor sin postventa:",["Elite","Pierde ~70% operaciones potenciales",
      "Igual","Mejor"],1,"Costo oportunidad.",["No.","","Pierde.","Peor."]),
    Q("Detractor público:",["Ignorar","Responder con empatía profesional","Borrar","Demandar"],1,"Gestión online.",["Peor.","","Mal.","Exceso."]),
    Q("Promotor responder:",["Nada","Agradecer + invitar referido + testimonio","Descuento","Solo cobrar"],1,"Sistema.",["Oportunidad.","","No canje.","Mal."]),
    Q("NPS = 50:",["Malo","Excelente","Malo","Falso"],1,"Alto.",["Bueno.","","Bueno.","Real."]),
    Q("Marca personal corredor 2026:",["Irrelevante","Clave para diferenciación digital","Secundaria","Prohibida"],1,"Contexto.",["Crítica.","","Primaria.","Legal."]),
    Q("LinkedIn del corredor:",["Jokes","Contenido técnico B2B","Fotos","Nada"],1,"Autoridad.",["No.","","Más.","Hay uso."]),
    Q("Instagram del corredor:",["Personal","Propiedades curadas + testimonios + tips","Prohibido","Privado"],1,"Canal propio.",["Mezcla.","","Legal.","Abierto."]),
    Q("Newsletter corredor:",["Spam","Segmentado por Capa · 80/20","Masivo","Ilegal"],1,"Directo.",["Cuidado.","","No masivo.","Legal."]),
    Q("Reels Instagram:",["Inútil","Alta viralidad + territorial","Obsoleto","Ilegal"],1,"Herramienta.",["Efectivo.","","Vigente.","Legal."]),
    Q("Contenido sólo propiedades:",["Ideal","Volantero digital · baja autoridad","Top","Único"],1,"Evitarlo.",["Mal.","","Peor.","No."]),
    Q("Casos de estudio:",["Riesgo","Alto valor · con autorización","Ilegales","Sin efecto"],1,"Con permiso.",["Legal.","","Legal.","Efecto."]),
    Q("Capa C reactivada exitosa:",["Pérdida","Sube a Capa B, luego A","Nunca","Se mantiene"],1,"Progresión.",["Oportunidad.","","Sube.","Puede."]),
  ];
}
function buildGold(){
  return [
    {n:1,title:"Mensaje de refuerzo 48 hrs post-firma",text:"Anticipa la duda post-cierre. Datos, no emociones vacías. Calma ansiedad y solidifica vínculo."},
    {n:2,title:"Plan 30-90-180-365 obligatorio",text:"Sistema de contactos programados. Sin plan, el cliente se olvida de ti. Con plan, NPS sube y referidos fluyen."},
    {n:3,title:"Informa Ley 19.472 al entregar",text:"3 años terminaciones · 5 instalaciones · 10 estructural. Es tu deber profesional informarlo."},
    {n:4,title:"Encuesta NPS día 30",text:"3 preguntas · respuesta en 24h. Promotores: pide referido. Detractores: resuelve fricción."},
    {n:5,title:"Pirámide de los 100 estructurada",text:"A 20 + B 50 + C 30. Sin estructura, la red caliente se desvanece."},
    {n:6,title:"Solicitud acotada '1 o 2 personas'",text:"Segmentada ('en tu trabajo' / 'en situación similar'). Acotación activa memoria."},
    {n:7,title:"Reciprocidad estructurada",text:"Agradecimiento <48h. Reporte autorizado del avance. Sin reciprocidad, se seca la fuente."},
    {n:8,title:"KPI 4 solicitudes, 2 referidos/mes",text:"Sistema, no azar. Meta mensual mínima del corredor profesional TuMatch."},
    {n:9,title:"Reactivación personalizada (no masiva)",text:"Tasa 25% vs 3%. Motivo concreto + propuesta de valor sin exigencia inmediata."},
    {n:10,title:"Marca personal 80% formativo",text:"LinkedIn + Instagram + newsletter. Autoridad se construye antes que transacción. Evita ser volantero digital."},
  ];
}
