/* Taller 04 · Subsidios Habitacionales Chile 2026
   Banco v1 — ampliable. Fuentes: MINVU, MIDESO, bcn.cl, chileatiende.gob.cl */
window.TALLER_CONFIG = {
  slug: 'subsidios-chile-2026',
  moduleNames: {
    1:'Arquitectura del sistema MINVU',
    2:'DS49 · Fondo Solidario',
    3:'DS1 Tramo 1',
    4:'DS1 Tramo 2 y 3',
    5:'DS19 · Integración Social',
    6:'DS116 Subsidio al Crédito y otros',
    7:'Postulación, documentos y objeciones',
  },
  certTitle: 'Subsidios Habitacionales Chile 2026',
  certSubtitle: 'Taller Avanzado 04 · Academia TuMatch',
  quizBank: {
    1: [
      {q:"El organismo que diseña la política habitacional en Chile es:",opts:["SERNAC","MINVU (Ministerio de Vivienda y Urbanismo)","CMF","ABIF"],correct:1,whyCorrect:"MINVU es el ministerio responsable de diseñar los decretos supremos que regulan subsidios y política habitacional.",whyWrong:["Protección al consumidor.","","Regulador financiero.","Gremio bancario."]},
      {q:"SERVIU es:",opts:["Banco","Órgano regional del MINVU que opera postulaciones y paga subsidios","Ministerio","ONG"],correct:1,whyCorrect:"Servicio de Vivienda y Urbanización — uno por región — ejecuta operativamente los programas del MINVU.",whyWrong:["No es banco.","","No es ministerio, es servicio regional.","Es estatal."]},
      {q:"El RSH es administrado por:",opts:["MINVU","MIDESO (Ministerio de Desarrollo Social)","SERVIU","Municipio"],correct:1,whyCorrect:"El Registro Social de Hogares es instrumento MIDESO que califica vulnerabilidad socioeconómica.",whyWrong:["No lo emite.","","Lo usa pero no lo administra.","Puede actualizarlo, no lo administra."]},
      {q:"La plataforma oficial para consulta del RSH es:",opts:["minvu.cl","registrosocial.gob.cl","sernac.cl","sii.cl"],correct:1,whyCorrect:"Plataforma MIDESO con ClaveÚnica del postulante.",whyWrong:["Es MINVU.","","Protección consumidor.","Tributario."]},
      {q:"Los llamados a DS49 se abren típicamente:",opts:["Mensualmente","Anualmente (ventana habitual abril-junio)","Diariamente","Cada 5 años"],correct:1,whyCorrect:"Ventana anual. Siempre verificar calendario vigente en minvu.cl.",whyWrong:["No es mensual.","","Absurdo.","Fuera de periodicidad."]},
      {q:"ChileAtiende es:",opts:["Banco","Canal integrado de atención ciudadana y consultas de trámites","SII","SERNAC"],correct:1,whyCorrect:"Portal de servicio del Estado para orientación sobre trámites y beneficios.",whyWrong:["No es banco.","","Tributario.","Consumidor."]},
      {q:"El corredor que orienta a un cliente sobre subsidios debe:",opts:["Inventar","Consultar fuentes oficiales (MINVU, SERVIU, ChileAtiende) y citar montos del llamado vigente",
        "Solo memoria","Ignorar"],correct:1,whyCorrect:"Siempre fuentes oficiales; los montos cambian llamado a llamado.",whyWrong:["Grave error.","","Desactualiza.","Abdica."]},
      {q:"Un cliente con RSH tramo 60% puede postular a:",opts:["Solo DS49","DS1 Tramo 1 o Tramo 2 (según condiciones específicas)","Ningún subsidio","DS19 exclusivamente"],correct:1,whyCorrect:"DS1 T1 acepta hasta 60%. T2 hasta 70%. T3 hasta 90%.",whyWrong:["Está sobre el límite de DS49.","","Hay rutas disponibles.","No excluyente."]},
      {q:"Los DS (Decretos Supremos) habitacionales se consultan legalmente en:",opts:["Wikipedia","bcn.cl (Biblioteca del Congreso Nacional de Chile)","Redes sociales","Blog"],correct:1,whyCorrect:"Fuente oficial de legislación chilena.",whyWrong:["No oficial.","","No oficial.","No oficial."]},
      {q:"Un subsidio MINVU vigente no combinable con otro es:",opts:["Todos combinan","DS49 no combina con crédito hipotecario (es subsidio directo sin crédito)","Ninguno","Todos exclusivos"],correct:1,whyCorrect:"DS49 es pago directo al SERVIU por vivienda social.",whyWrong:["No todos.","","Hay subsidios.","No todos exclusivos."]},
      {q:"La vigencia típica del certificado de subsidio DS1 para comprar vivienda es:",opts:["5 días","21 meses desde la emisión (con posibilidad de prórroga justificada)","Ilimitada","1 semana"],correct:1,whyCorrect:"Plazo estándar para utilizar el subsidio.",whyWrong:["Imposible.","","Ninguno es ilimitado.","Fuera."]},
      {q:"La prohibición de venta típica de vivienda con subsidio DS1 es:",opts:["Ninguna","5 años desde la inscripción a nombre del subsidiado","10 años","Indefinida"],correct:1,whyCorrect:"Evita especulación con vivienda subsidiada.",whyWrong:["Hay prohibición.","","Mayor que la real.","Hay plazo."]},
      {q:"Si el cliente quiere vender antes de los 5 años de subsidio DS1, debe:",opts:["No puede nunca","Solicitar autorización SERVIU y devolver subsidio actualizado","Libremente","Multar"],correct:1,whyCorrect:"Procedimiento de desafectación del subsidio.",whyWrong:["Puede con trámite.","","No libremente.","No es multa."]},
      {q:"MINVU atiende al corredor profesional:",opts:["Nunca","Vía SERVIU regional o ChileAtiende; también informa a inmobiliarias con proyectos DS19",
        "Solo abogados","Solo notarios"],correct:1,whyCorrect:"Canales institucionales de consulta.",whyWrong:["Es accesible.","","No limitado.","No limitado."]},
      {q:"El principal valor del corredor para un cliente con potencial subsidio es:",opts:["Ninguno","Orientarlo y acompañarlo en postulación + buscar propiedad compatible + derivación bancaria coordinada",
        "Solo venta","Facturar doble"],correct:1,whyCorrect:"El servicio integral multiplica el valor percibido.",whyWrong:["Es muy alto.","","Es venta asesorada.","Absurdo."]},
      {q:"Los bancos adheridos al Subsidio al Crédito Hipotecario DS116 incluyen:",opts:["Ninguno","BancoEstado (principal) y convenios con otros bancos según llamado","Solo privados","Ninguna cooperativa"],correct:1,whyCorrect:"BancoEstado lidera históricamente por su rol estatal; la lista varía por llamado.",whyWrong:["Hay bancos.","","También convenios varios.","Depende llamado."]},
      {q:"La carpeta de postulación típica a DS1 incluye:",opts:["Solo CI","CI + RSH + ahorro mínimo + declaración no propietario + certificado CBR + liquidaciones",
        "Solo F22","Nada"],correct:1,whyCorrect:"Lista mínima de postulación sector medio.",whyWrong:["Insuficiente.","","Incompleto.","Sin postulación."]},
      {q:"Si el cliente es rechazado por MINVU en un llamado, puede:",opts:["Nada","Apelar y volver a postular en el siguiente llamado","Denunciar","Ir a otra provincia"],correct:1,whyCorrect:"Sin límite de intentos si mantiene requisitos.",whyWrong:["Hay apelación.","","No procede.","No resuelve."]},
      {q:"El MINVU publica los resultados de postulación en:",opts:["Redes sociales","minvu.cl y SERVIU regional en nómina oficial","WhatsApp","Solo papel"],correct:1,whyCorrect:"Canales oficiales.",whyWrong:["No oficial.","","No oficial.","Digital disponible."]},
      {q:"El sistema de subsidios chileno es:",opts:["Centralizado en Santiago","Territorializado vía SERVIU regional bajo lineamiento MINVU",
        "Privado","Internacional"],correct:1,whyCorrect:"Operación descentralizada con política centralizada.",whyWrong:["Es descentralizado operativo.","","Estatal.","Nacional."]},
    ],
    2: [
      {q:"El DS49 financia hasta:",opts:["UF 500","~UF 950 (referencial urbano RM 2026, varía por región)","UF 5.000","Ilimitado"],correct:1,whyCorrect:"Monto típico urbano; rural/extremo mayor. Siempre verifica llamado vigente.",whyWrong:["Subestima.","","Fuera de DS49.","Siempre hay tope."]},
      {q:"El RSH máximo para postular a DS49 es:",opts:["90%","40% más vulnerable (tramos 0-40)","100%","Sin límite"],correct:1,whyCorrect:"Focaliza en sectores vulnerables.",whyWrong:["Fuera.","","Sin focalización.","Sin focalización."]},
      {q:"El ahorro mínimo DS49 es:",opts:["UF 100","10 UF en cuenta vivienda","UF 500","Cero"],correct:1,whyCorrect:"Aporte simbólico de compromiso del postulante.",whyWrong:["Fuera.","","Excesivo.","Existe ahorro."]},
      {q:"DS49 combina con crédito hipotecario:",opts:["Siempre","No combina; es pago directo al SERVIU sin crédito bancario","Solo un banco","Depende"],correct:1,whyCorrect:"Característica distintiva del DS49 — subsidio total.",whyWrong:["No.","","No.","No."]},
      {q:"El perfil típico DS49 es:",opts:["Ejecutivo senior","Familia vulnerable RSH ≤40%, ahorro irregular, sin acceso a banca",
        "Inversionista","Jubilado con patrimonio"],correct:1,whyCorrect:"Focalización de política social.",whyWrong:["Fuera.","","Fuera.","Fuera."]},
      {q:"La vivienda DS49 se entrega:",opts:["Libremente","Inscrita a nombre del subsidiado con prohibición de venta 5 años",
        "En arriendo","Nunca"],correct:1,whyCorrect:"Garantiza uso habitacional del subsidio.",whyWrong:["Hay restricciones.","","Es propiedad.","Sí se entrega."]},
      {q:"El corredor en DS49 típicamente:",opts:["Gana mucha comisión","No genera comisión directa; acompaña al cliente y deriva a otras oportunidades",
        "Es el único intermediario","No aplica"],correct:1,whyCorrect:"Valor profesional en asesoría, no en comisión directa.",whyWrong:["Irreal.","","No exclusivo.","Puede acompañar."]},
      {q:"DS49 se postula:",opts:["Diariamente","En llamados anuales publicados por MINVU","Solo en enero","Nunca"],correct:1,whyCorrect:"Ventana anual habitual.",whyWrong:["No.","","Varía.","Sí hay postulaciones."]},
      {q:"Un postulante con vivienda ya inscrita a su nombre NO puede:",opts:["Postular","Postular a DS49 (requisito: no tener vivienda propia)","Solo migrantes","Solo chilenos"],correct:1,whyCorrect:"Característica de focalización.",whyWrong:["Es restricción.","","Aplica a todos.","Requisito igual."]},
      {q:"La construcción en sitio propio con DS49:",opts:["No existe","Es una modalidad: familia con terreno propio accede a subsidio para construir su casa",
        "Solo en región","No hay variaciones"],correct:1,whyCorrect:"Modalidad específica del DS49.",whyWrong:["Existe.","","Es nacional.","Hay modalidades."]},
      {q:"Un cliente DS49 rechazado puede:",opts:["Nunca más postular","Apelar y volver a postular siguiente llamado","Ir a juicio","Abandonar"],correct:1,whyCorrect:"Sin límite de postulaciones mientras mantenga requisitos.",whyWrong:["Puede reintentar.","","No procede.","Hay oportunidad."]},
      {q:"La residencia definitiva es requerida en DS49 para:",opts:["No se requiere","Extranjeros (chilenos no la requieren por ser nacionales)","Todos","Ningún caso"],correct:1,whyCorrect:"Aplicación estándar para acceso a subsidios.",whyWrong:["Se requiere.","","Chilenos no.","Sí se requiere."]},
      {q:"DS49 rural ofrece típicamente:",opts:["Menos subsidio","Montos superiores al urbano por costos logísticos y aislamiento",
        "Mismo monto","Sin subsidio"],correct:1,whyCorrect:"Reconoce mayor costo de construcción y transporte en zonas rurales.",whyWrong:["Al contrario.","","Diferenciación.","Es inclusivo."]},
      {q:"Un migrante con residencia definitiva puede postular a DS49:",opts:["No","Sí, si cumple RSH y demás requisitos","Solo después de 10 años","Solo si tiene pareja chilena"],correct:1,whyCorrect:"Política inclusiva.",whyWrong:["Puede.","","Requisito legal mínimo.","No se requiere."]},
      {q:"Los resultados DS49 se publican en:",opts:["Diario","Nómina oficial en minvu.cl y SERVIU regional","WhatsApp","Correo privado"],correct:1,whyCorrect:"Canales oficiales transparentes.",whyWrong:["No oficial.","","No oficial.","No público."]},
      {q:"El DS49 atiende principalmente:",opts:["Clase media alta","Familias vulnerables sin historial bancario ni capacidad de crédito",
        "Solo migrantes","Solo adultos mayores"],correct:1,whyCorrect:"Política pública de acceso.",whyWrong:["Fuera del foco.","","No exclusivo.","No exclusivo."]},
      {q:"La vivienda DS49 típica está en:",opts:["Cualquier barrio libremente","Conjuntos habitacionales sociales o sitio propio con proyecto aprobado",
        "Zonas VIP","En el extranjero"],correct:1,whyCorrect:"Proyectos definidos por SERVIU.",whyWrong:["No es libre.","","Fuera del perfil.","Es Chile."]},
      {q:"La familia DS49 acumuló típicamente:",opts:["UF 500","UF 10-15 en cuenta vivienda durante varios años","UF 1.000","Cero"],correct:1,whyCorrect:"Esfuerzo progresivo de ahorro.",whyWrong:["Fuera.","","Fuera.","Hay ahorro mínimo."]},
      {q:"El DS49 se opera operativamente a través de:",opts:["Privado","SERVIU regional que adjudica viviendas y paga construcción",
        "Empresas","Embajadas"],correct:1,whyCorrect:"Operación estatal descentralizada.",whyWrong:["Es estatal.","","Estado.","No aplica."]},
      {q:"Al corredor que acompaña cliente DS49 le conviene:",opts:["Rechazarlo","Mantener la relación (referirá cuando esté en posición de mercado) y ofrecer asesoría gratuita de orientación",
        "Cobrar altísimo","Ignorarlo"],correct:1,whyCorrect:"Cultivo relacional de largo plazo.",whyWrong:["Daña marca.","","No hay comisión alta.","Abdica."]},
    ],
    3: [
      {q:"DS1 Tramo 1 tiene RSH máximo:",opts:["40%","60% más vulnerable","90%","100%"],correct:1,whyCorrect:"Sector medio-vulnerable.",whyWrong:["DS49.","","T3.","Sin focalización."]},
      {q:"Ahorro mínimo DS1 T1:",opts:["10 UF","30 UF","80 UF","200 UF"],correct:1,whyCorrect:"Característica T1.",whyWrong:["DS49.","","T3.","Fuera."]},
      {q:"Precio vivienda máximo DS1 T1:",opts:["UF 950","UF 1.600 referencial","UF 2.600","UF 5.000"],correct:1,whyCorrect:"Sector medio-vulnerable.",whyWrong:["DS49.","","T3.","Fuera."]},
      {q:"DS1 T1 combina con:",opts:["Nada","Crédito hipotecario obligatorio + ahorro + subsidio","Solo arriendo","Solo leasing"],correct:1,whyCorrect:"Estructura de financiamiento estándar.",whyWrong:["Requiere crédito.","","No es arriendo.","Puede combinar, no exclusivo."]},
      {q:"Un cliente DS1 T1 con renta líquida $1M:",opts:["No califica","Puede aspirar a vivienda UF 1.400-1.500 con subsidio + crédito ~UF 700",
        "Accede a T3","Nada"],correct:1,whyCorrect:"Ejemplo típico del tramo.",whyWrong:["Califica.","","No corresponde.","Hay ruta."]},
      {q:"El perfil típico DS1 T1 es:",opts:["Ejecutivo","Empleado formal joven o pareja con primer hijo, RSH medio-vulnerable",
        "Inversionista","Jubilado"],correct:1,whyCorrect:"Focalización.",whyWrong:["Fuera.","","Fuera.","Fuera."]},
      {q:"La exención impuesto timbres DS1 T1 aplica:",opts:["Nunca","Parcialmente sobre crédito complementario hasta cierto tope UF",
        "Total siempre","Solo con aval"],correct:1,whyCorrect:"Beneficio tributario complementario.",whyWrong:["Aplica.","","No total.","No depende aval."]},
      {q:"La prohibición de venta DS1 T1 es:",opts:["Ninguna","5 años desde inscripción","10 años","Indefinida"],correct:1,whyCorrect:"Evita especulación.",whyWrong:["Hay.","","Mayor al real.","Finita."]},
      {q:"DS1 T1 es compatible con leasing habitacional:",opts:["No","Sí (Tanner, Caja Los Andes)","Solo DS49","Ningún caso"],correct:1,whyCorrect:"Convenios con sociedades de leasing.",whyWrong:["Compatible.","","DS49 no combina con leasing.","Es compatible."]},
      {q:"El monto típico del subsidio DS1 T1 es:",opts:["UF 50","~UF 500-700 según condiciones","UF 5.000","Cero"],correct:1,whyCorrect:"Rango típico; siempre verificar llamado.",whyWrong:["Subestima.","","Fuera.","Sí hay subsidio."]},
      {q:"Los llamados DS1 se abren:",opts:["Mensuales","Semestrales típicamente (marzo y agosto en llamados recientes)",
        "Anuales","Nunca"],correct:1,whyCorrect:"Ventana habitual.",whyWrong:["Varía.","","DS49 es anual.","Sí hay llamados."]},
      {q:"Un cliente DS1 T1 con banco pre-aprobado debe mostrar al MINVU:",opts:["Nada","Carta pre-aprobación como validación de capacidad crediticia complementaria",
        "Solo Dicom","Solo CI"],correct:1,whyCorrect:"Validación de ruta financiera.",whyWrong:["Debe.","","Incompleto.","Incompleto."]},
      {q:"Un rechazo DS1 T1 puede apelarse dentro de:",opts:["1 día","Plazo establecido en bases del llamado (típicamente 30-45 días)",
        "5 años","Nunca"],correct:1,whyCorrect:"Proceso administrativo reglado.",whyWrong:["Fuera.","","Fuera.","Hay apelación."]},
      {q:"La vivienda DS1 T1 típicamente es:",opts:["Solo nueva","Nueva o usada, dentro del precio máximo del tramo",
        "Solo casa","Solo departamento"],correct:1,whyCorrect:"Flexibilidad típica.",whyWrong:["Flexible.","","Ambas tipologías.","Ambas tipologías."]},
      {q:"Un cliente DS1 T1 independiente debe demostrar:",opts:["Nada","Ingresos F22 últimos 2 años + carpeta tributaria para acceder al crédito complementario",
        "Solo boleta","Sin requerimientos"],correct:1,whyCorrect:"Requisito del banco complementario.",whyWrong:["Requerimiento.","","Insuficiente.","Hay requerimientos."]},
      {q:"DS1 T1 puede combinarse con DS116:",opts:["No","Sí; DS116 baja tasa del crédito complementario",
        "Solo T3","Nunca"],correct:1,whyCorrect:"Complemento compatible.",whyWrong:["Compatible.","","Compatible en todos tramos con condiciones.","Compatible."]},
      {q:"Una familia DS1 T1 que se muda fuera de la vivienda antes de 5 años:",opts:["Sin problema","Debe autorizar SERVIU y potencialmente devolver subsidio",
        "Automático","Pierde todo"],correct:1,whyCorrect:"Control del uso habitacional del subsidio.",whyWrong:["Hay obligaciones.","","Hay trámite.","Hay proceso."]},
      {q:"El corredor en DS1 T1 puede cobrar comisión:",opts:["No","Sí, al cliente y al vendedor como en operación compraventa estándar",
        "Solo vendedor","Solo comprador"],correct:1,whyCorrect:"Operación inmobiliaria estándar con subsidio.",whyWrong:["Sí puede.","","Ambas partes.","Ambas partes."]},
      {q:"DS1 T1 requiere RSH:",opts:["No","Sí, actualizado · se descarga desde registrosocial.gob.cl con ClaveÚnica",
        "Solo municipio","Nada"],correct:1,whyCorrect:"Documento fundamental de focalización.",whyWrong:["Requiere.","","También online.","Crítico."]},
      {q:"Un cliente DS1 T1 cuyo RSH mejora (sube a tramo no elegible) antes de postular:",opts:["Sigue elegible","Pierde elegibilidad; debe esperar a actualización favorable",
        "Indiferente","Sube a T3"],correct:1,whyCorrect:"Elegibilidad se verifica al momento de postular.",whyWrong:["Cambio afecta.","","Afecta.","No automático."]},
    ],
    4: [
      {q:"Precio máximo DS1 Tramo 2 es:",opts:["UF 950","UF 2.200","UF 3.500","Sin límite"],correct:1,whyCorrect:"Sector medio estándar.",whyWrong:["DS49.","","Fuera.","Siempre tope."]},
      {q:"Precio máximo DS1 Tramo 3 es:",opts:["UF 1.600","UF 2.600","UF 3.500","UF 10.000"],correct:1,whyCorrect:"Tramo superior del sector medio.",whyWrong:["T1.","","Fuera.","Fuera."]},
      {q:"RSH máximo DS1 T2:",opts:["40%","70% más vulnerable","90%","100%"],correct:1,whyCorrect:"Sector medio.",whyWrong:["DS49.","","T3.","Sin focalización."]},
      {q:"RSH máximo DS1 T3:",opts:["60%","90% más vulnerable","100%","Sin límite"],correct:1,whyCorrect:"Tramo más alto de elegibilidad.",whyWrong:["T1.","","Sin focalización.","Sin focalización."]},
      {q:"Ahorro mínimo DS1 T2:",opts:["10 UF","50 UF","200 UF","Cero"],correct:1,whyCorrect:"Tramo intermedio.",whyWrong:["DS49.","","Fuera.","Hay ahorro mínimo."]},
      {q:"Ahorro mínimo DS1 T3:",opts:["30 UF","80 UF","500 UF","Cero"],correct:1,whyCorrect:"Tramo más alto exige más ahorro.",whyWrong:["T1.","","Fuera.","Hay ahorro mínimo."]},
      {q:"DS1 T2/T3 es compatible con leasing habitacional:",opts:["No","Sí, especialmente con Tanner y Caja Los Andes que tienen convenios formales con MINVU",
        "Solo DS49","Ningún caso"],correct:1,whyCorrect:"Convenio formal para combinar subsidio con arriendo-promesa.",whyWrong:["Compatible.","","DS49 no combina.","Es compatible."]},
      {q:"Un cliente DS1 T3 puede optar a propiedad de:",opts:["UF 500 máximo","Hasta UF 2.600","UF 10.000","Sin tope"],correct:1,whyCorrect:"Tope del tramo.",whyWrong:["Fuera.","","Fuera.","Hay tope."]},
      {q:"La vivienda con DS1 T2/T3 tiene prohibición de venta:",opts:["Ninguna","5 años desde inscripción","10 años","Indefinida"],correct:1,whyCorrect:"Igual que otros tramos DS1.",whyWrong:["Hay.","","Mayor al real.","Finita."]},
      {q:"El perfil típico DS1 T3 es:",opts:["Vulnerable","Joven profesional o pareja consolidando con empleo formal y renta líquida conjunta UF 100+",
        "Jubilado","Inversionista"],correct:1,whyCorrect:"Sector medio con capacidad crediticia.",whyWrong:["Fuera.","","Fuera.","Fuera del perfil primera vivienda."]},
      {q:"Un cliente DS1 T3 con renta $2,5M combinada puede aspirar a:",opts:["UF 500","Hasta UF 2.600 con subsidio + crédito","UF 10.000","Nada"],correct:1,whyCorrect:"Capacidad típica del tramo.",whyWrong:["Subestima.","","Fuera del tope.","Sí accede."]},
      {q:"La postulación DS1 T2/T3 requiere:",opts:["Solo RSH","RSH + ahorro + declaración no propietario + certificado CBR + pre-aprobación bancaria",
        "Solo CI","Solo F22"],correct:1,whyCorrect:"Carpeta completa sector medio.",whyWrong:["Insuficiente.","","Insuficiente.","Insuficiente."]},
      {q:"DS1 T2/T3 combina con DS116:",opts:["No","Sí, si el crédito complementario es con banco adherido (típicamente BancoEstado)",
        "Solo T1","Nunca"],correct:1,whyCorrect:"Complemento compatible para bajar tasa.",whyWrong:["Compatible.","","Compatible en condiciones.","Compatible."]},
      {q:"El monto del subsidio DS1 T3 es:",opts:["UF 1.000","~UF 200-350 (menor que T1 por menor vulnerabilidad)","Cero","UF 5.000"],correct:1,whyCorrect:"Inversamente proporcional a vulnerabilidad.",whyWrong:["Fuera.","","Hay subsidio.","Fuera."]},
      {q:"Una pareja DS1 T3 con 2 rentas combinadas puede postular como:",opts:["2 postulantes","1 postulación conjunta con cónyuge/conviviente civil",
        "Solo uno","Ninguno"],correct:1,whyCorrect:"Postulación conjunta habitual.",whyWrong:["Es conjunta.","","Pueden ambos.","Pueden postular."]},
      {q:"DS1 T2 vivienda nueva se diferencia de usada en:",opts:["No hay diferencia","Montos de subsidio pueden variar; vivienda nueva a veces con mayor aporte MINVU al proyecto",
        "Solo en color","Usada prohibida"],correct:1,whyCorrect:"Estructura varía según llamado.",whyWrong:["Hay diferencia.","","Absurdo.","Ambas elegibles."]},
      {q:"El cliente DS1 T2 en zona distinta a la RM puede aspirar a:",opts:["Menos","Montos similares o superiores según políticas regionales",
        "Nada","Solo rurales"],correct:1,whyCorrect:"Regiones pueden tener montos mayores por equidad territorial.",whyWrong:["Depende zona.","","Accede.","Urbano también."]},
      {q:"Un cliente DS1 T3 que pierde empleo post-postulación pre-aprobada:",opts:["Mantiene","Puede perder aprobación bancaria; subsidio es válido si cumple requisitos MINVU",
        "Automático","No afecta"],correct:1,whyCorrect:"Subsidio y crédito son instrumentos distintos.",whyWrong:["Banco reevalúa.","","No.","Sí afecta ruta."]},
      {q:"La carga financiera máxima al combinar DS1 con crédito sigue siendo:",opts:["50%","25% de renta líquida (regla general)","Sin límite","0"],correct:1,whyCorrect:"Norma bancaria prudencial aplica igual.",whyWrong:["Fuera.","","Hay límite.","No sería viable."]},
      {q:"El rol del corredor en DS1 T2/T3 es:",opts:["Marginal","Central: orienta postulación + perfila cliente + encuentra propiedad + coordina bancos + cierra",
        "Ninguno","Solo firma"],correct:1,whyCorrect:"Asesoría integral del primera vivienda.",whyWrong:["Central.","","Es central.","Más amplio."]},
    ],
    5: [
      {q:"DS19 regula:",opts:["Arriendo","Programa de Integración Social y Territorial (proyectos mixtos)","Subsidio directo","Crédito puro"],correct:1,whyCorrect:"Creado en 2016 para mezclar subsidio y mercado libre en proyectos.",whyWrong:["No es arriendo puro.","","No es subsidio directo a familia.","No es crédito."]},
      {q:"En DS19, el postulante:",opts:["Elige libremente","Postula a un proyecto específico aprobado DS19 por MINVU",
        "Compra sin subsidio","Nada"],correct:1,whyCorrect:"Postulación por proyecto, no genérica.",whyWrong:["Restringido.","","Con subsidio.","Hay postulación."]},
      {q:"La mezcla típica en un proyecto DS19 es:",opts:["100% subsidiado","~50% subsidiado + ~50% mercado libre","100% libre","Sin mezcla"],correct:1,whyCorrect:"Regla general de integración social.",whyWrong:["No es 100%.","","No es 100%.","Hay mezcla."]},
      {q:"La inmobiliaria en DS19:",opts:["No recibe nada","Recibe aporte MINVU al proyecto como incentivo al cumplir criterios sociales",
        "Financia sola","No participa"],correct:1,whyCorrect:"Incentivo para generar proyectos mixtos.",whyWrong:["Hay incentivo.","","MINVU aporta.","Participa central."]},
      {q:"DS19 se postula:",opts:["Todo el año","Cuando la inmobiliaria abre ventas del proyecto con reserva de cupos subsidiados",
        "Nunca","Solo en enero"],correct:1,whyCorrect:"Por proyecto específico.",whyWrong:["Por proyecto.","","Sí hay.","Varía."]},
      {q:"Un comprador DS19 con subsidio:",opts:["Paga más","Accede a unidades reservadas a precio regulado por MINVU",
        "Accede a VIP","Nada"],correct:1,whyCorrect:"Beneficio del programa.",whyWrong:["Al contrario.","","Fuera del programa.","Hay beneficio."]},
      {q:"El comprador sin subsidio en un proyecto DS19:",opts:["No puede","Puede comprar las unidades de mercado libre a precio normal",
        "Solo con subsidio","Gratis"],correct:1,whyCorrect:"Acceso abierto a unidades libres.",whyWrong:["Puede.","","Sin restricción.","Es de mercado."]},
      {q:"DS19 tiene tramos:",opts:["Único","Distintos tramos según proyecto (algunos llamados 'CEIS')",
        "Solo DS1","No hay tramos"],correct:1,whyCorrect:"Distintas modalidades según convocatoria.",whyWrong:["Hay tramos.","","Es propio.","Hay modalidades."]},
      {q:"Un corredor en proyecto DS19 puede trabajar:",opts:["Solo libre","Ambos lados: subsidiados (perfila y postula) y mercado libre (venta estándar)",
        "Solo subsidiados","Ninguno"],correct:1,whyCorrect:"Doble oportunidad comercial.",whyWrong:["Doble.","","Doble.","Es oportunidad."]},
      {q:"Un proyecto DS19 típicamente se ubica en:",opts:["Zonas extremas","Zonas de alta demanda y buen transporte (parte del objetivo de integración)",
        "Rural","Sin criterio"],correct:1,whyCorrect:"Integración social y territorial.",whyWrong:["Al contrario.","","No es foco.","Hay criterio."]},
      {q:"El beneficiario DS19 subsidiado necesita:",opts:["Nada","Calificar con RSH + ahorro + tramo específico del proyecto",
        "Solo CI","Sin calificación"],correct:1,whyCorrect:"Calificación análoga a DS1.",whyWrong:["Se califica.","","Incompleto.","Hay calificación."]},
      {q:"La prohibición de venta en vivienda DS19 subsidiada es:",opts:["Ninguna","5 años similar a DS1","10 años","Indefinida"],correct:1,whyCorrect:"Misma lógica antifraude.",whyWrong:["Hay.","","Mayor al real.","Finita."]},
      {q:"El ahorro mínimo DS19 subsidiado es:",opts:["Cero","Similar al DS1 del tramo correspondiente (30-80 UF)",
        "100 UF","500 UF"],correct:1,whyCorrect:"Análogo al DS1 según tramo.",whyWrong:["Hay.","","Fuera.","Fuera."]},
      {q:"Un proyecto DS19 está identificado en:",opts:["Nunca","Portales MINVU y cartera del SERVIU regional",
        "Solo Google","Registro civil"],correct:1,whyCorrect:"Canales oficiales.",whyWrong:["Está.","","No oficial.","No aplica."]},
      {q:"La inmobiliaria con proyecto DS19 se beneficia por:",opts:["Nada","Aporte MINVU + venta asegurada del cupo subsidiado + incentivo urbano",
        "Solo prestigio","Evita impuestos"],correct:1,whyCorrect:"Incentivo al proyecto social.",whyWrong:["Hay beneficio.","","Es económico.","No es evasión."]},
      {q:"Un corredor que conoce proyectos DS19 activos:",opts:["No le sirve","Tiene ventaja competitiva: perfila clientes DS1 y los vincula a cupos disponibles",
        "Solo al vendedor","Sin diferencia"],correct:1,whyCorrect:"Diferenciación profesional.",whyWrong:["Es ventaja.","","Trabaja ambos.","Hay diferencia."]},
      {q:"El comprador DS19 firma:",opts:["Nada","Promesa con la inmobiliaria + escritura compraventa + subsidio aplica como parte del pie",
        "Solo WhatsApp","No firma"],correct:1,whyCorrect:"Proceso compraventa con subsidio integrado.",whyWrong:["Firma.","","No informal.","Firma."]},
      {q:"DS19 ofrece al sector medio vulnerable:",opts:["Nada","Acceso a vivienda en zonas de mayor valor que sin el programa no alcanzaría",
        "Solo rural","Solo RM"],correct:1,whyCorrect:"Objetivo de integración.",whyWrong:["Hay beneficio.","","No es rural.","Es nacional."]},
      {q:"El proyecto DS19 está aprobado por:",opts:["Municipio","MINVU previo cumplimiento de bases del llamado",
        "SERNAC","Ningún órgano"],correct:1,whyCorrect:"Ministerio responsable.",whyWrong:["No.","","No procede.","Hay aprobación."]},
      {q:"La relevancia del DS19 para el corredor de primera vivienda es:",opts:["Baja","Alta: expande opciones del cliente subsidiado hacia zonas de mayor plusvalía",
        "Ninguna","Sin impacto"],correct:1,whyCorrect:"Ventaja real para el cliente.",whyWrong:["Es alta.","","Hay impacto.","Hay impacto."]},
    ],
    6: [
      {q:"DS116 baja la tasa del crédito hipotecario en:",opts:["0 pp","0,61% a 1,16% aproximado según condiciones del llamado",
        "5 pp","10 pp"],correct:1,whyCorrect:"Rango típico según bases.",whyWrong:["No es cero.","","Fuera.","Excesivo."]},
      {q:"DS116 se aplica durante:",opts:["Toda la vida del crédito","Los primeros años del crédito según bases (varía)",
        "1 día","Nunca"],correct:1,whyCorrect:"Beneficio temporal.",whyWrong:["Finito.","","Imposible.","Sí aplica."]},
      {q:"DS116 se contrata con:",opts:["Cualquier banco","Bancos adheridos al programa (BancoEstado principal)",
        "Mutuaria sin convenio","No se contrata"],correct:1,whyCorrect:"Convenio específico MINVU-banco.",whyWrong:["Requiere adhesión.","","Sin convenio.","Se contrata."]},
      {q:"Arriendo con Promesa de Compra (subsidio):",opts:["No existe","Apoya financiación de leasing habitacional con subsidio",
        "Solo arriendo puro","Sin subsidio"],correct:1,whyCorrect:"Alternativa para perfiles con historial complejo.",whyWrong:["Existe.","","Es arriendo-promesa.","Con subsidio."]},
      {q:"Subsidio de Reparación financia:",opts:["Nueva vivienda","Ampliación, mejoramiento o reparación de vivienda existente",
        "Solo arriendo","Nada"],correct:1,whyCorrect:"Apoyo a propietarios.",whyWrong:["No es compra.","","Es reparación.","Financia."]},
      {q:"Subsidio de Arriendo DS52:",opts:["No existe","Apoyo al pago de arriendo por 5-8 años para familias vulnerables",
        "Compra","Todos los años"],correct:1,whyCorrect:"Instrumento paralelo a DS1 para familias que aún no pueden comprar.",whyWrong:["Existe.","","No es compra.","Tiene plazo."]},
      {q:"Clase Media programa MINVU atiende:",opts:["Solo vulnerables","Familias del tramo medio que no califican a DS1 estricto",
        "Solo ricos","Nadie"],correct:1,whyCorrect:"Ampliación de focalización hacia sector medio.",whyWrong:["Es clase media.","","Fuera.","Atiende."]},
      {q:"Un cliente con crédito hipotecario vigente puede aplicar DS116:",opts:["Siempre","Solo al momento de solicitar el crédito, no retroactivamente",
        "Retroactivo","Sin relación"],correct:1,whyCorrect:"Complemento contemporáneo al crédito.",whyWrong:["No.","","No retroactivo.","Hay relación."]},
      {q:"El DS116 se solicita:",opts:["Separado","Junto con la postulación DS1 y evaluación bancaria del crédito complementario",
        "Al pagar","Después"],correct:1,whyCorrect:"Proceso integrado.",whyWrong:["No separado.","","Al inicio.","En el inicio."]},
      {q:"Un corredor debe orientar sobre DS116 porque:",opts:["Irrelevante","Ahorra al cliente UF 50-120 durante primeros años — argumento de cierre para DS1 T1/T2",
        "No hay efecto","Marketing"],correct:1,whyCorrect:"Impacto económico medible.",whyWrong:["Es clave.","","Hay efecto.","No es marketing."]},
      {q:"Arriendo con Promesa de Compra combina con:",opts:["Solo DS49","DS1 T2/T3 con sociedades de leasing adheridas",
        "Ningún DS","Sin combinar"],correct:1,whyCorrect:"Convenios Tanner / Caja Los Andes.",whyWrong:["DS49 no combina.","","Combinable.","Es combinable."]},
      {q:"Subsidio de Reparación requiere:",opts:["Nuevo propietario","Ser propietario de vivienda que cumple condiciones del llamado",
        "Arrendatario","Nada"],correct:1,whyCorrect:"Apoya al propietario existente.",whyWrong:["Existente.","","Es propietario.","Requisitos."]},
      {q:"DS52 Subsidio de Arriendo aplica para:",opts:["Compra","Pagar arriendo durante periodo definido; no es para compra",
        "Comercial","Inversión"],correct:1,whyCorrect:"Apoyo habitacional temporal.",whyWrong:["No es compra.","","No comercial.","No inversión."]},
      {q:"El corredor con cliente que necesita DS116 debe:",opts:["Nada","Derivar al banco adherido (BancoEstado principal) y documentar en CRM la ruta",
        "Ocultar","Inventar"],correct:1,whyCorrect:"Servicio profesional.",whyWrong:["Activo.","","Fraude.","Ilegal."]},
      {q:"La combinación DS1 + DS116 + leasing en T2/T3:",opts:["No existe","Es posible con sociedades de leasing con convenios; reduce pie efectivo del cliente",
        "Solo banco","Sin efecto"],correct:1,whyCorrect:"Combinaciones con convenio MINVU.",whyWrong:["Existe.","","Hay rutas.","Tiene efecto."]},
      {q:"Subsidio de Reparación se paga:",opts:["Al contado al propietario","A través de entidades técnicas EETEC que ejecutan la obra",
        "Directo sin control","Nunca"],correct:1,whyCorrect:"Mecanismo con control técnico.",whyWrong:["No directo.","","Control exigido.","Se paga."]},
      {q:"Un cliente con propiedad recién comprada puede aplicar Subsidio de Reparación en:",opts:["Nunca","Vivienda propia con cierta antigüedad y cumpliendo requisitos del llamado",
        "Ningún caso","Solo DS49"],correct:1,whyCorrect:"Depende condiciones.",whyWrong:["Puede.","","Hay casos.","No limitado."]},
      {q:"Los cupos DS116 por llamado son:",opts:["Ilimitados","Finitos, asignados según orden de llegada o sorteo",
        "Solo 1","Sin regla"],correct:1,whyCorrect:"Presupuesto acotado por año.",whyWrong:["Finitos.","","Mucho más.","Hay regla."]},
      {q:"Un corredor que no conoce DS116 pierde:",opts:["Nada","Oportunidad de cierre con clientes DS1 al no ofrecer rebaja de tasa complementaria",
        "Solo tiempo","Referido"],correct:1,whyCorrect:"Argumento de cierre profesional.",whyWrong:["Pierde valor.","","Más que tiempo.","Pierde."]},
      {q:"Clase Media programa se diferencia de DS1 T3 en:",opts:["Igual","Tramos de ingreso y RSH que pueden ser más flexibles según llamado específico",
        "Solo en nombre","No es oficial"],correct:1,whyCorrect:"Diferenciación por política MINVU.",whyWrong:["Hay diferencias.","","Más que nombre.","Es oficial."]},
    ],
    7: [
      {q:"El paso 1 de postulación DS1 es:",opts:["Comprar casa","Actualizar RSH en registrosocial.gob.cl y verificar tramo de elegibilidad",
        "Firmar escritura","Nada"],correct:1,whyCorrect:"Fundamento de elegibilidad.",whyWrong:["Prematuro.","","Al final.","Hay trámite."]},
      {q:"La cuenta de ahorro vivienda para subsidios se abre en:",opts:["Cualquier banco","BancoEstado principalmente o cooperativas adheridas",
        "Caja","En efectivo"],correct:1,whyCorrect:"Producto específico para subsidios habitacionales.",whyWrong:["No cualquier.","","Privado no adherido.","No sirve."]},
      {q:"La declaración jurada de no tener vivienda propia se firma:",opts:["Verbalmente","Ante notario o en formato oficial SERVIU",
        "En casa","Nunca"],correct:1,whyCorrect:"Documento oficial formal.",whyWrong:["No sirve.","","No oficial.","Requerido."]},
      {q:"El certificado de dominio vigente CBR (negativo propiedad) se pide:",opts:["Nunca","En el CBR de cada región donde postulante pudo tener propiedad",
        "Solo en Santiago","WhatsApp"],correct:1,whyCorrect:"Validación multiregional.",whyWrong:["Requerido.","","Multiregional.","No oficial."]},
      {q:"Si el cliente tiene Dicom vigente al postular:",opts:["Sin problema","Banco complementario puede rechazar crédito; conviene limpiar antes",
        "Acelera","Gratuito"],correct:1,whyCorrect:"Afecta el crédito complementario.",whyWrong:["Sí afecta.","","Al contrario.","Cuesta."]},
      {q:"Un rechazo DS1 por error administrativo se resuelve con:",opts:["Rendición","Apelación ante SERVIU con respaldo documental dentro del plazo de bases",
        "Juzgado","Nada"],correct:1,whyCorrect:"Procedimiento administrativo.",whyWrong:["No abandonar.","","Administrativo primero.","Hay solución."]},
      {q:"La vigencia del certificado de subsidio para comprar es:",opts:["1 semana","21 meses con prórroga posible","5 años","Indefinida"],correct:1,whyCorrect:"Plazo estándar.",whyWrong:["Imposible.","","Fuera.","Finita."]},
      {q:"Un cliente que elige propiedad fuera del precio tope del tramo:",opts:["Puede igual","No puede usar el subsidio en esa propiedad; debe buscar una dentro del tope",
        "Paga más","Automático"],correct:1,whyCorrect:"Condición básica del subsidio.",whyWrong:["No puede.","","No es pago extra.","Hay validación."]},
      {q:"La objeción típica del cliente 'no voy a ganar el subsidio' se responde con:",opts:["Ignorar","'Postulación es gratuita y demora 20 min, riesgo cero. Si no ganas, postulas al siguiente llamado o vamos a leasing sin subsidio'",
        "Abandonar","Mentir"],correct:1,whyCorrect:"Manejo profesional de objeción.",whyWrong:["Daña.","","Abdica.","Deshonesto."]},
      {q:"La objeción 'el trámite es complicado' se responde con:",opts:["Aceptar","'Yo te acompaño con checklist claro. 90 min totales de gestión. Estoy para eso'",
        "Confirmar","Confirmar"],correct:1,whyCorrect:"Asesoría profesional que convierte la complejidad en servicio.",whyWrong:["Rinde.","","Rinde.","Rinde."]},
      {q:"La objeción 'no tengo ahorro mínimo aún' se responde con:",opts:["Abandonar","'Podemos trabajar plan de ahorro a 6-12 meses; en ese plazo tu RSH puede mejorar y postulamos juntos'",
        "Rechazar","Mentir"],correct:1,whyCorrect:"Cultivo relacional con plan.",whyWrong:["Daña.","","Abdica.","Deshonesto."]},
      {q:"La carpeta SII Carpeta Tributaria se descarga desde:",opts:["Banco","sii.cl con ClaveTributaria del contribuyente","Municipio","MINVU"],correct:1,whyCorrect:"Documento electrónico SII.",whyWrong:["No emite.","","No emite.","Usa pero no emite."]},
      {q:"Un cliente que posta a DS1 y luego encuentra propiedad DS19:",opts:["Pierde subsidio","Puede usar el subsidio DS1 dentro del proyecto DS19 si es compatible con el llamado",
        "No procede","Requiere nueva postulación"],correct:1,whyCorrect:"Compatibilidad operativa.",whyWrong:["No pierde.","","Procede.","No requiere en muchos casos."]},
      {q:"La prórroga de vigencia del certificado de subsidio se solicita con:",opts:["Nada","Justificación por escrito al SERVIU antes del vencimiento",
        "WhatsApp","Informalmente"],correct:1,whyCorrect:"Procedimiento administrativo.",whyWrong:["Requiere.","","No sirve.","No sirve."]},
      {q:"Un cliente que pierde el subsidio por vencimiento debe:",opts:["Comprar igual","Postular al siguiente llamado con requisitos actualizados",
        "Juzgado","Nada"],correct:1,whyCorrect:"Reintento en el siguiente llamado.",whyWrong:["Sin subsidio no hay beneficio.","","No aplica.","Hay solución."]},
      {q:"El ahorro en cuenta vivienda debe demostrarse con:",opts:["Solo dicho","Cartola emitida por BancoEstado o cooperativa adherida con saldo requerido",
        "Efectivo","Nada"],correct:1,whyCorrect:"Documento emitido por entidad adherida.",whyWrong:["Requerida.","","No sirve.","Requerido."]},
      {q:"Un cliente independiente que postula a DS1 debe probar ingresos con:",opts:["Nada","F22 últimos 2 años + carpeta SII + boletas honorarios 12 meses",
        "CI solamente","WhatsApp"],correct:1,whyCorrect:"Igual exigencia que crédito bancario.",whyWrong:["Probar.","","Insuficiente.","No sirve."]},
      {q:"El corredor que acompaña postulación DS1 gana:",opts:["Solo cariño","Comisión si la operación compraventa se cierra con propiedad de mercado dentro del tope",
        "Sólo del vendedor","Nada"],correct:1,whyCorrect:"Operación estándar de compraventa.",whyWrong:["Hay comisión.","","De ambas partes.","Hay comisión."]},
      {q:"Una familia DS1 T3 que compra en DS19 ideal es:",opts:["No existe","Combinación óptima: subsidio + zona de mayor plusvalía + financiamiento complementario",
        "Solo DS49","Fuera"],correct:1,whyCorrect:"Ejemplo de máxima optimización.",whyWrong:["Existe.","","DS49 no combina así.","Es la mejor."]},
      {q:"El mejor momento para iniciar postulación a subsidio con un cliente es:",opts:["Al firmar escritura","Al menos 3-4 meses antes del llamado para armar RSH + ahorro + documentos",
        "Día mismo","Nunca"],correct:1,whyCorrect:"Preparación profesional.",whyWrong:["Tarde.","","Imposible.","Sin gestión."]},
    ],
  },
  finalQuestions: [
    {q:"DS49 financia hasta:",opts:["UF 500","~UF 950 RM (varía zona)","UF 5.000","Ilimitado"],correct:1,whyCorrect:"Referencial 2026.",whyWrong:["Subestima.","","Fuera.","Hay tope."]},
    {q:"RSH máximo DS49:",opts:["90%","40% más vulnerable","100%","Sin tope"],correct:1,whyCorrect:"Focalización.",whyWrong:["Fuera.","","Sin focal.","Sin focal."]},
    {q:"DS1 T1 precio máximo:",opts:["UF 950","UF 1.600","UF 2.600","Sin límite"],correct:1,whyCorrect:"Sector medio-vulnerable.",whyWrong:["DS49.","","T3.","Siempre hay tope."]},
    {q:"DS1 T2 precio máximo:",opts:["UF 1.600","UF 2.200","UF 3.000","Sin tope"],correct:1,whyCorrect:"Tramo intermedio.",whyWrong:["T1.","","Fuera.","Hay tope."]},
    {q:"DS1 T3 precio máximo:",opts:["UF 1.600","UF 2.600","UF 3.500","Sin tope"],correct:1,whyCorrect:"Tramo superior sector medio.",whyWrong:["T1.","","Fuera.","Hay tope."]},
    {q:"Ahorro mínimo DS49:",opts:["10 UF","10 UF en cuenta vivienda","100 UF","Cero"],correct:1,whyCorrect:"Ahorro simbólico.",whyWrong:["Es 10.","","Fuera.","Hay."]},
    {q:"Ahorro mínimo DS1 T1:",opts:["10 UF","30 UF","80 UF","Cero"],correct:1,whyCorrect:"Tramo básico.",whyWrong:["DS49.","","T3.","Hay."]},
    {q:"Ahorro mínimo DS1 T3:",opts:["30 UF","80 UF","500 UF","Cero"],correct:1,whyCorrect:"Tramo alto.",whyWrong:["T1.","","Fuera.","Hay."]},
    {q:"DS49 combina con crédito hipotecario:",opts:["Siempre","No combina; es subsidio directo","Solo un banco","Depende"],correct:1,whyCorrect:"Pago directo a SERVIU.",whyWrong:["No.","","No.","No."]},
    {q:"DS1 combina con crédito:",opts:["No","Obligatoriamente, el crédito completa el precio","Opcional","Nunca"],correct:1,whyCorrect:"Estructura subsidio+ahorro+crédito.",whyWrong:["Obligatorio.","","Es obligatorio.","Se requiere."]},
    {q:"DS116 baja la tasa del crédito en:",opts:["0","0,61-1,16 pp","5 pp","10 pp"],correct:1,whyCorrect:"Rango estándar.",whyWrong:["No.","","Fuera.","Excesivo."]},
    {q:"DS19 es:",opts:["Subsidio directo","Programa de Integración Social y Territorial (proyectos mixtos)","Crédito","Arriendo"],correct:1,whyCorrect:"Proyectos mixtos MINVU.",whyWrong:["No.","","No es crédito.","No es arriendo."]},
    {q:"El RSH se consulta en:",opts:["minvu.cl","registrosocial.gob.cl","SERNAC","SII"],correct:1,whyCorrect:"Plataforma MIDESO.",whyWrong:["No.","","Consumidor.","Tributo."]},
    {q:"SERVIU es:",opts:["Banco","Órgano regional del MINVU","Ministerio","ONG"],correct:1,whyCorrect:"Regional.",whyWrong:["No.","","No es ministerio.","Es estatal."]},
    {q:"La prohibición de venta DS1 es:",opts:["Ninguna","5 años desde inscripción","10 años","Indefinida"],correct:1,whyCorrect:"Antiespeculación.",whyWrong:["Hay.","","Fuera.","Finita."]},
    {q:"DS1 T2/T3 combina con leasing:",opts:["No","Sí (Tanner, Caja Los Andes)","Solo DS49","Ningún caso"],correct:1,whyCorrect:"Convenios MINVU.",whyWrong:["Sí.","","DS49 no.","Sí."]},
    {q:"Vigencia certificado subsidio para comprar:",opts:["5 días","21 meses","5 años","Indefinida"],correct:1,whyCorrect:"Plazo estándar.",whyWrong:["Fuera.","","Fuera.","Finita."]},
    {q:"RSH máximo DS1 T2:",opts:["40%","70%","100%","Sin tope"],correct:1,whyCorrect:"Tramo.",whyWrong:["DS49.","","T3/más.","Sin focal."]},
    {q:"RSH máximo DS1 T3:",opts:["60%","90%","100%","Sin tope"],correct:1,whyCorrect:"Tramo superior.",whyWrong:["T1.","","Sin focal.","Sin focal."]},
    {q:"DS19 postulante postula a:",opts:["Subsidio genérico","Proyecto específico aprobado DS19 por MINVU","Nada","Libre"],correct:1,whyCorrect:"Por proyecto.",whyWrong:["No.","","Sí postula.","Restringido."]},
    {q:"Un rechazo MINVU se apela:",opts:["Nunca","Dentro del plazo de las bases con respaldo","Solo juicio","Automático"],correct:1,whyCorrect:"Procedimiento.",whyWrong:["Hay apelación.","","Administrativa primero.","No automático."]},
    {q:"Chilenos y extranjeros con residencia definitiva pueden postular a DS1:",opts:["Solo chilenos","Sí, si cumplen requisitos","Solo extranjeros","Ninguno"],correct:1,whyCorrect:"Política inclusiva.",whyWrong:["Ambos.","","Ambos.","Pueden."]},
    {q:"El ahorro vivienda se abre en:",opts:["Cualquier banco","BancoEstado o cooperativa adherida","Caja","Privado cualquiera"],correct:1,whyCorrect:"Adheridos al sistema.",whyWrong:["No cualquier.","","No sirve.","Requiere adhesión."]},
    {q:"La carpeta tributaria SII se descarga:",opts:["Banco","sii.cl con ClaveTributaria","Papel","MINVU"],correct:1,whyCorrect:"Electrónica SII.",whyWrong:["No emite.","","Digital.","No emite."]},
    {q:"Un corredor DS1 gana comisión:",opts:["No","Si cierra operación compraventa con propiedad de mercado","No se cobra","Solo 10%"],correct:1,whyCorrect:"Operación estándar.",whyWrong:["Gana.","","Se cobra.","Tramos contractuales."]},
    {q:"DS49 genera prohibición de venta:",opts:["Nunca","5 años desde inscripción","Indefinida","1 año"],correct:1,whyCorrect:"Antiespeculación.",whyWrong:["Hay.","","Finita.","Fuera."]},
    {q:"El rol del corredor con cliente DS1 es:",opts:["Marginal","Central: orienta, acompaña postulación, encuentra propiedad, coordina bancos",
      "Ninguno","Solo firma"],correct:1,whyCorrect:"Integral.",whyWrong:["Central.","","Es central.","Más amplio."]},
    {q:"Arriendo con Promesa (subsidio) combina con:",opts:["Solo DS49","DS1 T2/T3 y sociedades de leasing adheridas",
      "Ningún DS","Sin relación"],correct:1,whyCorrect:"Convenios.",whyWrong:["No combina.","","Combinable.","Hay relación."]},
    {q:"Los llamados DS1 son típicamente:",opts:["Mensuales","Semestrales","Anuales","Nunca"],correct:1,whyCorrect:"Marzo y agosto recientes.",whyWrong:["No.","","Varía.","Hay."]},
    {q:"Un comprador DS1 T3 con $2,5M conjunto aspira a:",opts:["UF 500","Hasta UF 2.600 con subsidio + crédito","UF 10.000","Nada"],correct:1,whyCorrect:"Tope del tramo.",whyWrong:["Bajo.","","Fuera.","Accede."]},
    {q:"Subsidio de Reparación financia:",opts:["Nueva vivienda","Reparación o mejoramiento de vivienda existente",
      "Solo arriendo","Nada"],correct:1,whyCorrect:"Apoyo a propietarios.",whyWrong:["No es compra.","","No arriendo.","Financia."]},
    {q:"DS52 es:",opts:["No existe","Subsidio al Arriendo (apoyo temporal 5-8 años)",
      "Compra","Crédito"],correct:1,whyCorrect:"Instrumento paralelo.",whyWrong:["Existe.","","No compra.","No crédito."]},
    {q:"El corredor que conoce subsidios:",opts:["Nada","Diferenciación profesional; amplía opciones del cliente y cierra más",
      "Menos valor","Irrelevante"],correct:1,whyCorrect:"Ventaja competitiva.",whyWrong:["Es valor.","","Más valor.","Es relevante."]},
    {q:"DS1 T1 admite vivienda usada:",opts:["No","Sí, hasta tope de precio del tramo","Solo nueva","Solo rural"],correct:1,whyCorrect:"Flexibilidad.",whyWrong:["Admite.","","Ambas.","Urbano también."]},
    {q:"La carga financiera total al combinar subsidio con crédito es:",opts:["50%","25% de renta líquida","Sin límite","0"],correct:1,whyCorrect:"Norma bancaria.",whyWrong:["Fuera.","","Hay límite.","No viable."]},
    {q:"La postulación DS1 se hace en:",opts:["Banco","minvu.cl o SERVIU con CI + RSH + ahorro","Cualquier ONG","WhatsApp"],correct:1,whyCorrect:"Canales oficiales.",whyWrong:["No.","","Oficial.","No oficial."]},
    {q:"El cliente DS1 T3 con ahorro 40 UF:",opts:["Califica","No califica al T3 (requiere 80 UF); puede buscar T2 o aumentar ahorro",
      "Sube","Libre"],correct:1,whyCorrect:"Requisito de tramo.",whyWrong:["No califica.","","No sube.","Depende."]},
    {q:"Extranjero con permiso temporal:",opts:["Postula","No puede postular (requiere residencia definitiva)","Sí puede","Solo con cónyuge chileno"],correct:1,whyCorrect:"Requisito legal.",whyWrong:["No puede.","","No puede.","No basta."]},
    {q:"Un cliente DS1 que pierde empleo post pre-aprobación:",opts:["Sin efecto","El banco reevalúa crédito; subsidio se mantiene si cumple RSH",
      "Automático","Nada"],correct:1,whyCorrect:"Crédito y subsidio son instrumentos distintos.",whyWrong:["Hay efecto.","","No automático.","Sí afecta."]},
    {q:"DS49 rural tiene:",opts:["Menos subsidio","Montos superiores por costos de ruralidad","Mismo monto","Nada"],correct:1,whyCorrect:"Equidad territorial.",whyWrong:["Al contrario.","","Diferencia.","Inclusivo."]},
    {q:"Las fuentes oficiales para el corredor son:",opts:["Memoria","MINVU, SERVIU, bcn.cl, chileatiende.gob.cl","Redes","Blog"],correct:1,whyCorrect:"Siempre oficiales.",whyWrong:["No confiable.","","No oficial.","No oficial."]},
    {q:"La inmobiliaria DS19:",opts:["Recibe nada","Recibe incentivo MINVU al cumplir criterios sociales del proyecto",
      "Financia sola","No participa"],correct:1,whyCorrect:"Incentivo.",whyWrong:["Hay.","","MINVU aporta.","Participa."]},
    {q:"DS19 mezcla típica de viviendas:",opts:["100% subsidio","~50% subsidio + ~50% libre","100% libre","Sin mezcla"],correct:1,whyCorrect:"Integración.",whyWrong:["No.","","No.","Hay mezcla."]},
    {q:"La exención impuesto timbres aplica al crédito con subsidio:",opts:["No","Parcial/total según tramo y tope UF","Siempre total","Nunca"],correct:1,whyCorrect:"DL 3.475.",whyWrong:["Aplica.","","Parcial típico.","Sí aplica."]},
    {q:"La cuenta de ahorro vivienda exige:",opts:["Nada","Movimientos periódicos o saldo mínimo según bases del llamado",
      "Anonimato","Ninguna"],correct:1,whyCorrect:"Buenas prácticas.",whyWrong:["Hay.","","No anónima.","Hay."]},
    {q:"El corredor acompaña postulación DS1 para:",opts:["Nada","Ganar el referido + cerrar la operación compraventa resultante",
      "Cobrar por postular","Por ley"],correct:1,whyCorrect:"Estrategia relacional y comercial.",whyWrong:["Hay valor.","","No se cobra postulación.","No ley."]},
    {q:"El plazo evaluación MINVU post-postulación es:",opts:["1 día","2 a 4 meses típicamente","5 años","Indefinido"],correct:1,whyCorrect:"Ventana operativa.",whyWrong:["Imposible.","","Fuera.","Finito."]},
    {q:"La notificación de resultado DS1 se hace por:",opts:["WhatsApp","Nómina oficial minvu.cl y SERVIU regional","Llamada","Ninguna"],correct:1,whyCorrect:"Canales oficiales.",whyWrong:["No oficial.","","No oficial.","Hay notificación."]},
    {q:"El DS49 es compatible con leasing:",opts:["Sí","No combina con leasing ni crédito","Solo leasing","Solo crédito"],correct:1,whyCorrect:"Es subsidio directo.",whyWrong:["No.","","No.","No."]},
  ],
  goldRules: [
    {n:1,title:"Domina los 5 tramos principales",text:"DS49 (vulnerable) · DS1 T1 (medio-vulnerable UF 1.600) · DS1 T2 (medio UF 2.200) · DS1 T3 (medio UF 2.600) · DS19 (proyectos integración)."},
    {n:2,title:"Verifica siempre el llamado vigente",text:"Los montos, topes y fechas cambian por llamado. Consulta minvu.cl antes de orientar al cliente."},
    {n:3,title:"RSH actualizado es el primer paso",text:"Sin RSH correcto no hay postulación. Verifica registrosocial.gob.cl con el cliente en la primera reunión."},
    {n:4,title:"DS49 acompaña pero no genera comisión directa",text:"Construye relación de largo plazo; esa familia podría referir o volver cuando mejore su situación."},
    {n:5,title:"DS1 T2/T3 es tu nicho principal del primera vivienda",text:"Joven profesional y pareja consolidando. Combina subsidio + DS116 + leasing si aplica."},
    {n:6,title:"DS19 expande la zona de tu cliente",text:"Clientes DS1 pueden acceder a zonas de alta plusvalía vía proyectos DS19. Identifícalos en tu territorio."},
    {n:7,title:"DS116 es tu argumento de cierre",text:"Rebaja tasa 0,61-1,16 pp. Ahorra UF 50-120. Nunca lo omitas con cliente DS1."},
    {n:8,title:"Explica la prohibición 5 años honestamente",text:"Vender antes requiere autorización SERVIU y devolver subsidio. Que el cliente lo sepa al firmar evita crisis posterior."},
    {n:9,title:"Acompaña postulación con checklist visual",text:"La objeción 'es complicado' desaparece con un checklist ordenado y tu presencia en 2 videollamadas de 15 min."},
    {n:10,title:"Fuente oficial siempre",text:"MINVU, SERVIU, bcn.cl, chileatiende.gob.cl. Nunca inventes montos ni plazos; verifica antes de citar."},
  ],
};
